### ISSUE TITLE
How to get release hash from Raven.config？

### ISSUE THREAD

**Issue by t1ger-0527** [getsentry/sentry-webpack-plugin#10]
What this plugin actually do? Auto releasing & uploading source map? Do I still need to set the release field in my `Raven.config` like I used to in my own shell script? If so, how do I get the release hash, from environment variables?

**Comment by montogeek** [comment]
This plugin autoreleases and upload the source maps too.
Yes, you need to set a release, from the docs (https://github.com/getsentry/sentry-webpack-plugin#options):
> release [required] - unique name of a release, can be either a string or a function which will expose you a compilation hash as it's first argument, which is 20-char long string, unique for a given codebase.

You can provide your release hash from any source, environment variables is the common way to do it.

**Comment by t1ger-0527** [comment]
Cool, thanks a lot. ❤️

**Comment by t1ger-0527** [comment]
For the record, I choose to use `process.env.Hash` for releasing.
