### ISSUE TITLE
This loader loads sentry-webpack.module.js may destroy the cache

### ISSUE THREAD

**Issue by uuhan** [getsentry/sentry-webpack-plugin#102]
https://github.com/getsentry/sentry-webpack-plugin/blob/d9eaedd2ae73ec18f351670d7a8f379a9e5c9f7c/src/index.js#L232

If you include all '@sentry' into your chunk to cache your dependencies, you should exclude this sentry-webpack-plugin to avoid this plugin to insert release into your chunk, for example:

```javascript
optimization: {
  cacheGroups: {
    'vendor': {
        name: 'vendor',
        test: (module, chunks) => /[\\/]node_modules[\\/]/.test(module.context) &&
           !/@sentry[\\/](?!webpack-plugin)/.test(module.context) // **to exclude the release**
    }
  }
}
```

I do not know why this plugin loads **empty** file [sentry-webpack.module.js](https://github.com/getsentry/sentry-webpack-plugin/blob/master/src/sentry-webpack.module.js) which causes this issue, but it may destroy your cache if you pack this plugin into your chunk.

Related Issue Here: #93

**Comment by kamilogorek** [comment]
Closing due to the issue getting out-dated. Feel free to ping me to reopen it if it's still relevant.
