### ISSUE TITLE
stripPrefix option doesn't seem to work

### ISSUE THREAD

**Issue by Gromph** [getsentry/sentry-webpack-plugin#103]
I'm just getting started with sentry.io and SentryWebpackPlugin. I need it to strip the prefix ~/dist/ when uploading sourcemaps. For example I need the file to be named:
~/app.6d88f068e342b1d46378.js.map
But no matter what I do it is always:
~/dist/app.6d88f068e342b1d46378.js.map
Here is my config:
```
new SentryWebpackPlugin({
  include: '.',
  ignoreFile: '.sentrycliignore',
  ignore: ['node_modules', 'webpack.config.js'],
  configFile: 'sentry.properties',
  stripPrefix: ["~/dist/"],
  release: "test-project@0.0.3",
  rewrite: true,
})
```
I've tried many variations in stripPrefix, none work, ie:
`stripPrefix: ["~", "~/", "~/dist", "~/dist/", "dist", "/dist", "/dist/"],`

It looks like some others have had the same problem with the sentry-clli --strip-prefix option:
https://github.com/getsentry/sentry-cli/issues/436

I am using sentry-webpack-plugin version 1.6.2 installed from npm
Running node v8.11.4 on Windows 10 build 1803

**Comment by coder-guy22296** [comment]
you can use `include: './dist/'`, that worked for me because I only needed to upload items from dist
`new SentryWebpackPlugin({
  include: './dist/',
  ignoreFile: '.sentrycliignore',
  ignore: ['node_modules', 'webpack.config.js'],
  configFile: 'sentry.properties',
  release: "test-project@0.0.3",
  rewrite: true,
})`

**Comment by workgena** [comment]
In my case the `npm run build` puts all files to "./build" directory. For me the working solution is:

```javascript
new SentryWebpackPlugin({
    include: "./build/",
    ignoreFile: ".sentrycliignore",
    ignore: ['node_modules', 'webpack.config.js'],
    configFile: "sentry.properties",
    stripPrefix: ["build"]
}),
```

The build-script pushed new release to the sentry-server and all errors are mapped correctly.

**Comment by kamilogorek** [comment]
This project is just a webpack wrapper around sentry-cli JS API. Please cross-link this issue here https://github.com/getsentry/sentry-cli/ instead. Thanks!

**Comment by skewis6** [comment]
@kamilogorek I'm having the same issue. I understand why the issue has been closed here, but there has been an issue reported on the sentry-cli repo since December and it seems as though no-one is looking into it. Any ideas?

**Comment by kamilogorek** [comment]
I brought this issue up and will try to make it actionable next sprint (week).
