### ISSUE TITLE
--json is ignored, causing corrupted json output from webpack

### ISSUE THREAD

**Issue by roelvanhintum** [getsentry/sentry-webpack-plugin#104]
@sentry/webpack-plugin: 1.6.2

When executing:
`webpack --config webpack.config.server.js --json > dist/stats.json`

The following is prepended to the json file:
```
> Analyzing 2 sources
> Rewriting sources
> Adding source map references
> Uploading source maps for release __HASH__

Source Map Upload Report
  Minified Scripts
    ~/server.js (sourcemap at server.js.map)
  Source Maps
    ~/server.js.map
```

**Comment by couds** [comment]
Hi @roelvanhintum I got the same issue, but seems that the problem its on the Sentry-Cli repo, I added a PR there https://github.com/getsentry/sentry-cli/pull/512 that will be necessary to fix this issue.

**Comment by roelvanhintum** [comment]
@couds Thanks! Hopefully it will get merged soon.

**Comment by roelvanhintum** [comment]
@couds looks like your change is in sentry-cli 1.42.0. Can you update your pull-request with this?
