### ISSUE TITLE
Are suspect commits supported?

### ISSUE THREAD

**Issue by cameronmcefee** [getsentry/sentry-webpack-plugin#105]
I'm using this plugin and am trying to set up suspect commits. Is this possible via the plugin, or do I need to use the CLI directly to do that?

https://docs.sentry.io/workflow/releases/#associate-commits-with-a-release

**Comment by kamilogorek** [comment]
It's not possible right now, but because it's just one sentry-cli command call, it should be trivial to add – https://github.com/getsentry/sentry-webpack-plugin/blob/master/src/index.js#L291-L308

**Comment by crobinson42** [comment]
Has anyone deployed some strategy for associating commits after creating a release with this webpack plugin?

**Comment by BlitZz96** [comment]
Also interested in this

**Comment by blaiz** [comment]
I'm also interested in this. We don't pass any value for release, so this plugin uses the commit hash automatically, but somehow it doesn't associate the commit with the release.

**Comment by kamilogorek** [comment]
@crobinson42 @BlitZz96 is this what you were looking for https://github.com/getsentry/sentry-webpack-plugin#optionssetcommits ?

**Comment by BlitZz96** [comment]
Yes, @kamilogorek, [v1.9.0+](https://github.com/getsentry/sentry-webpack-plugin/releases/tag/v1.9.0) Solved this for me

**Comment by kamilogorek** [comment]
Awesome, thanks! :)
