### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by FuncWei** [getsentry/sentry-webpack-plugin#106]
![image](https://user-images.githubusercontent.com/16984724/52950403-fee68f80-33b9-11e9-8052-2caa5200a21e.png)

**Comment by FuncWei** [comment]
![image](https://user-images.githubusercontent.com/16984724/52950482-45d48500-33ba-11e9-9787-35a1eca3fc60.png)

**Comment by jan-auer** [comment]
Remove the quotes from your release. As you can see in the error message, it quotes twice:

```js
new SentryPlugin({
  release: gitRevisionPlugin.commithash(),
  // ...
})
```
