### ISSUE TITLE
Add types for use in Typescript

### ISSUE THREAD

**Issue by streeter** [getsentry/sentry-webpack-plugin#109]
There are no types defined for the Webpack plugin, which makes it a bit more difficult to use from within Typescript. Note that this means my webpack configuration is written in Typescript.

**Comment by andrerpena** [comment]
Please adapt the options to contain whatever you need. I did not have time to make a full implementation. Also, I will try to find time to finalize the implementation and make a proper pull request to sentry. Meanwhile, here you go:

```js
declare module '@sentry/webpack-plugin' {
  import { Plugin, Configuration } from 'webpack'

  class SentryWebpackPlugin extends Plugin {
    constructor (options?: SentryWebpackPlugin.);
  }

  namespace SentryWebpackPlugin {
    interface Options {
      include?: string | string[],
      ignoreFile?: string | ((webpackConfig: Configuration) => string),
      ignore?: string | string[],
      configFile: string
    }
  }

  export = SentryWebpackPlugin
}

```

**Comment by andrerpena** [comment]
Maintainers, can I make a PR with TypeScript definitions?

**Comment by kamilogorek** [comment]
Definitely @andrerpena

**Comment by kamilogorek** [comment]
Already implemented
