### ISSUE TITLE
Webpack compatibility

### ISSUE THREAD

**Issue by montogeek** [getsentry/sentry-webpack-plugin#11]
Hi!

Is this plugin compatible with webpack 1.14.0?
It is throwing this error: `ERROR in Sentry CLI Plugin: Cannot read property 'include' of undefined`.

When logging `this.options` just before calling SentryCLI I got my webpack configuration instead of just the options in the plugin, I guess in webpack 1.14 `options` it is a reserved key.

My only options would be upgrade webpack, right?

**Comment by montogeek** [comment]
nvm, I introduced a bug, fixing it!

**Comment by daidi** [comment]
me222222222
