### ISSUE TITLE
Ignoring files with negation pattern

### ISSUE THREAD

**Issue by niksy** [getsentry/sentry-webpack-plugin#113]
It seems like ignoring files doesn’t work with negation patterns. For example, if I ignore file `!core*`, I would expect that all files not containing `core` in their name should be published. This is contradictory to statement that `ignoreFile` could point to file in the same format as `.gitignore`, but standard Git ignore file supports negation patterns. Am I doing something wrong?

**Comment by kamilogorek** [comment]
This plugin is just a thin wrapper around https://github.com/getsentry/sentry-cli (in `ignoreFile` case it's just passing this option through), could you please report this issue there? Thanks!
