### ISSUE TITLE
Sourcemaps not working

### ISSUE THREAD

**Issue by afrieder** [getsentry/sentry-webpack-plugin#114]
I've looked at #97, #62, and #83, and despite trying everything in there my sourcemaps still don't work.

The event is:
https://sentry.io/organizations/heap/issues/953074953/?project=1294776&query=is%3Aunresolved&statsPeriod=90d&utc=false

I have sourcemaps for /js/app.js and other things I thought to try:
![image](https://user-images.githubusercontent.com/8473729/54961013-52e61600-4f1c-11e9-8d21-745007787090.png)

Despite this, they're not working. Any ideas on other things to try?

My webpack config is:
```js
new SentryWebpackPlugin({
      include: './front/public/js',
      ignoreFile: './.gitignore',
      debug: true,
      release: '43000',
      urlPrefix: '/js/',
    }),
```

and I'm correctly init'ing Sentry with that same release (`'43000'`).

**Comment by spacemup** [comment]
I believe there should be .map files in your artifacts as well, maybe you ignored them in the `.gitignore` file so they're not uploaded?

**Comment by kamilogorek** [comment]
Closing due to issue being stale. Feel free to ping me and I'll reopen it and try to answer.
