### ISSUE TITLE
The plugin does not follow symlinks.

### ISSUE THREAD

**Issue by o2genum** [getsentry/sentry-webpack-plugin#115]
My main package requires a local package as a dependency.
On `npm install`, NPM does not copy the package to `node_modules/`, but symlinks it instead.
This plugin does not follow the symlink (at least on Windows), and does not upload the sources of that local package.

My temporary solution is to use Yarn, which actually copies local packages to `node_modules/`, but I find it inconvenient for development.

**Comment by kamilogorek** [comment]
Closing due to the issue getting out-dated. Feel free to ping me to reopen it if it's still relevant.
