### ISSUE TITLE
error: project not found

### ISSUE THREAD

**Issue by ashen9** [getsentry/sentry-webpack-plugin#119]
my config is：
```
 new SentryWebpackPlugin({
          include: '.',
          ignoreFile: '.gitignore',
          ignore: ['node_modules', 'vue.config.js'],
          configFile: '.sentryclirc',
          release: `bi-test@${process.env.VUE_APP_VERSION}`,
          debug: true
        })
```

.sentryclirc
```
[defaults]
url = https://sentry.io/
org = ...
project = ...

[auth]
token = ...
```

then i get the result:
`error: project not found`

**Comment by kamilogorek** [comment]
You can install `sentry-cli` directly and run `sentry-cli info` and `sentry-cli projects list` to make sure that your configuration is correct and can talk to the Sentry API – https://docs.sentry.io/cli/configuration/#validating-the-config

**Comment by frankshin** [comment]
eg:
https://sentry.io/organizations/aaa/bbb/
i run the project successfully as following rules: the aaa in the url is org, and the bbb in the url is project

**Comment by gertjanwytynck** [comment]
For people coming here, had the same issue.
I've added as project the project ID (project=`project-id`), when updating to project=`project-string` it worked.

**Comment by kamilogorek** [comment]
Just to summarize. Given this url:
```
https://sentry.io/kamil-ogorek/testing-project/
```
corresponding settings are:
```
https://sentry.io/<org>/<project>/
```
And token is generated here: https://sentry.io/settings/account/api/auth-tokens/

**Comment by semihsezer** [comment]
I found out you need to include org_name. We should add that to docs.
`sentry cleanup --project <org>/<project-name>`

**Comment by leoyb** [comment]
@kamilogorek I still can't solve the problem according to your steps. Is there any other solution?

**Comment by leoyb** [comment]
@kamilogorek 
When I execute the command：
sentry-cli releases -o sentry -p niumei-admin files dev@0.1.0 upload-sourcemaps dist/js --url-prefix ~/

I got the error:
error: project not found

run 'sentry-cli info' show the info:
Sentry Server: ***
Default Organization: sentry
Default Project: niumei-admin

Authentication Info:
Method: Auth Token
User: ***
Scopes:
- event:admin
- event:read
- member:read
- org:read
- project:read
- project:releases
- team:read
- project:write

run 'sentry-cli projects list' show the info
+----+--------------+--------+--------------+
| ID | Slug | Team | Name |
+----+--------------+--------+--------------+
| 1 | internal | Sentry | Internal |
| 4 | niumei-admin | Sentry | niumei-admin |
+----+--------------+--------+--------------+

sentry version:
sentry-cli: 1.51.1
@sentry/browser: 5.12.4
@sentry/integrations: 5.12.4

**Comment by kamilogorek** [comment]
@leoyb can you run it with `--log-level=debug` and provide the logs?

**Comment by leoyb** [comment]
@kamilogorek Thank you for your reply. The problem has been fixed. It was found that the URL was filled incorrectly because I configured HTTPS

**Comment by bazingaedward** [comment]
i finally solve it.
for sentry project url like: http://www.bilibili.co/hello-org/world-project/

your .sentryrc file shoule be like:

`
[defaults]
url = http://www.bilibili.co/
org = hello-org
project = world-project

[log]
level = info

[auth]
token=<your auth token on www.sentry.io>
`

**Comment by xgqfrms** [comment]
```sh
[defaults]
url=https://sentry.io/
org=webgeeker
project=vue-web-app

[auth]
token=6662bf8f5ae42f7b1884e1a67b295eb808c3585b2094913b9404de26c9edxyz
dsn=https://abc20efd5e434dad8ed3e1d0b3156616@o476868.ingest.sentry.io/5574888

[log]
level = info

```

**Comment by TheImpressionist** [comment]
I renamed the project and now cannot deploy at all. Getting same error.

Checked all the variables, project name, organization name, all of them are fine. Nothing works.

**Comment by kamilogorek** [comment]
@TheImpressionist try to reissue auth token maybe?

**Comment by TheImpressionist** [comment]
> @TheImpressionist try to reissue auth token maybe?

Thanks, that resolved the issue.

**Comment by TheImpressionist** [comment]
@kamilogorek I tried that. For a moment I thought that'd succeed, but same issue.

Here's the config:

```javascript
new SentryWebpackPlugin({
  authToken: process.env.SENTRY_AUTH_TOKEN,
  include: './build',
  org: 'reneza',
  project: 'halo',
  ignoreFile: '.sentrycliignore',
  ignore: ['node_modules'],
  debug: true,
})
```

The project exists, I'm sure. Unless I'm coming down with schizophrenia.

![image](https://user-images.githubusercontent.com/11066223/124897979-764b0700-dfe7-11eb-98ab-cced3b6442f9.png)

**Comment by kamilogorek** [comment]
@TheImpressionist can you provide logs for:

```
SENTRY_LOG_LEVEL=debug sentry-cli info
```

and

```
SENTRY_LOG_LEVEL=debug sentry-cli releases list
```

(make sure to strip any confidential data).

**Comment by TheImpressionist** [comment]
@kamilogorek

Here you go:

```
  INFO    2021-07-08 13:14:41.946448 +03:00 Loaded config from /Users/dominykasbartkus/repo/work/reneza-webapp/.sentryclirc
  DEBUG   2021-07-08 13:14:41.947111 +03:00 sentry-cli version: 1.67.1, platform: "darwin", architecture: "x86_64"
  INFO    2021-07-08 13:14:41.947129 +03:00 sentry-cli was invoked with the following command line: "/usr/local/lib/node_modules/@sentry/cli/sentry-cli" "info"
  DEBUG   2021-07-08 13:14:41.947414 +03:00 request GET https://sentry.io/api/0/
  DEBUG   2021-07-08 13:14:41.947439 +03:00 using token authentication
  DEBUG   2021-07-08 13:14:41.947455 +03:00 retry number 0, max retries: 0
  DEBUG   2021-07-08 13:14:42.446550 +03:00 > GET /api/0/ HTTP/1.1
  DEBUG   2021-07-08 13:14:42.446585 +03:00 > Host: sentry.io
  DEBUG   2021-07-08 13:14:42.446595 +03:00 > Accept: */*
  DEBUG   2021-07-08 13:14:42.446602 +03:00 > Connection: TE
  DEBUG   2021-07-08 13:14:42.446609 +03:00 > TE: gzip
  DEBUG   2021-07-08 13:14:42.446616 +03:00 > User-Agent: sentry-cli/1.67.1
  DEBUG   2021-07-08 13:14:42.447083 +03:00 > Authorization: Bearer <Nope>
  DEBUG   2021-07-08 13:14:42.624178 +03:00 < HTTP/1.1 200 OK
  DEBUG   2021-07-08 13:14:42.624226 +03:00 < Server: nginx
  DEBUG   2021-07-08 13:14:42.624242 +03:00 < Date: Thu, 08 Jul 2021 10:14:47 GMT
  DEBUG   2021-07-08 13:14:42.624255 +03:00 < Content-Type: application/json
  DEBUG   2021-07-08 13:14:42.624284 +03:00 < Content-Length: 939
  DEBUG   2021-07-08 13:14:42.624297 +03:00 < Connection: keep-alive
  DEBUG   2021-07-08 13:14:42.624310 +03:00 < allow: GET, HEAD, OPTIONS
  DEBUG   2021-07-08 13:14:42.624322 +03:00 < access-control-allow-methods: GET, HEAD, OPTIONS
  DEBUG   2021-07-08 13:14:42.624341 +03:00 < access-control-allow-headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding
  DEBUG   2021-07-08 13:14:42.624354 +03:00 < access-control-expose-headers: X-Sentry-Error, Retry-After
  DEBUG   2021-07-08 13:14:42.624365 +03:00 < access-control-allow-origin: *
  DEBUG   2021-07-08 13:14:42.624375 +03:00 < vary: Accept-Language, Cookie
  DEBUG   2021-07-08 13:14:42.624386 +03:00 < content-language: en
  DEBUG   2021-07-08 13:14:42.624397 +03:00 < x-frame-options: deny
  DEBUG   2021-07-08 13:14:42.624407 +03:00 < x-content-type-options: nosniff
  DEBUG   2021-07-08 13:14:42.624446 +03:00 < x-xss-protection: 1; mode=block
  DEBUG   2021-07-08 13:14:42.624458 +03:00 < x-envoy-attempt-count: 1
  DEBUG   2021-07-08 13:14:42.624470 +03:00 < x-envoy-upstream-service-time: 23
  DEBUG   2021-07-08 13:14:42.624483 +03:00 < x-served-by: getsentry-web-default-production-7c7cb565bc-rf99k
  DEBUG   2021-07-08 13:14:42.624494 +03:00 < x-served-by: lb-5
  DEBUG   2021-07-08 13:14:42.624505 +03:00 < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  DEBUG   2021-07-08 13:14:42.624552 +03:00 response status: 200
  DEBUG   2021-07-08 13:14:42.624569 +03:00 body: {"version":"0","auth":{"scopes":["event:admin","event:read","member:read","org:read","project:read","project:releases","team:read","org:admin","member:admin","project:admin","team:admin"]},"user":{"id":"717016","name":"<My Name>","username":"<My User Name>","email":"<My Email>","avatarUrl":"https://secure.gravatar.com/avatar/a35b12b45fc2dfae07d68cc54496b043?s=32&d=mm","isActive":true,"hasPasswordAuth":true,"isManaged":false,"dateJoined":"2020-07-03T09:31:02.203369Z","lastLogin":"2021-07-05T07:48:01.764276Z","has2fa":false,"lastActive":"2021-07-08T10:10:12.663159Z","isSuperuser":false,"isStaff":false,"experiments":{},"options":{"theme":"light","language":"en","stacktraceOrder":-1,"timezone":"UTC","clock24Hours":false},"flags":{"newsletter_consent_prompt":false},"avatar":{"avatarType":"letter_avatar","avatarUuid":null},"identities":[],"emails":[{"id":"815775","email":"<email>","is_verified":true}]}}
Sentry Server: https://sentry.io
Default Organization: reneza
Default Project: reneza

Authentication Info:
  Method: Auth Token
  User: dominykas@reneza.com
  Scopes:
    - event:admin
    - event:read
    - member:read
    - org:read
    - project:read
    - project:releases
    - team:read
    - org:admin
    - member:admin
    - project:admin
    - team:admin
```

```
  INFO    2021-07-08 13:15:01.048025 +03:00 Loaded config from /Users/<Me>/repo/work/<Project>/.sentryclirc
  DEBUG   2021-07-08 13:15:01.048625 +03:00 sentry-cli version: 1.67.1, platform: "darwin", architecture: "x86_64"
  INFO    2021-07-08 13:15:01.048641 +03:00 sentry-cli was invoked with the following command line: "/usr/local/lib/node_modules/@sentry/cli/sentry-cli" "releases" "list"
  DEBUG   2021-07-08 13:15:01.048955 +03:00 request GET https://sentry.io/api/0/projects/reneza/reneza/releases/
  DEBUG   2021-07-08 13:15:01.048977 +03:00 using token authentication
  DEBUG   2021-07-08 13:15:01.048992 +03:00 retry number 0, max retries: 0
  DEBUG   2021-07-08 13:15:01.555945 +03:00 > GET /api/0/projects/reneza/reneza/releases/ HTTP/1.1
  DEBUG   2021-07-08 13:15:01.556001 +03:00 > Host: sentry.io
  DEBUG   2021-07-08 13:15:01.556009 +03:00 > Accept: */*
  DEBUG   2021-07-08 13:15:01.556016 +03:00 > Connection: TE
  DEBUG   2021-07-08 13:15:01.556023 +03:00 > TE: gzip
  DEBUG   2021-07-08 13:15:01.556030 +03:00 > User-Agent: sentry-cli/1.67.1
  DEBUG   2021-07-08 13:15:01.556537 +03:00 > Authorization: Bearer <Nope>
  DEBUG   2021-07-08 13:15:01.759103 +03:00 < HTTP/1.1 302 Found
  DEBUG   2021-07-08 13:15:01.759145 +03:00 < Server: nginx
  DEBUG   2021-07-08 13:15:01.759160 +03:00 < Date: Thu, 08 Jul 2021 10:15:06 GMT
  DEBUG   2021-07-08 13:15:01.759173 +03:00 < Content-Type: application/json
  DEBUG   2021-07-08 13:15:01.759201 +03:00 < Content-Length: 156
  DEBUG   2021-07-08 13:15:01.759214 +03:00 < Connection: keep-alive
  DEBUG   2021-07-08 13:15:01.759225 +03:00 < location: /api/0/projects/reneza/halo/releases/
  DEBUG   2021-07-08 13:15:01.759235 +03:00 < allow: GET, POST, HEAD, OPTIONS
  DEBUG   2021-07-08 13:15:01.759245 +03:00 < access-control-allow-methods: GET, POST, HEAD, OPTIONS
  DEBUG   2021-07-08 13:15:01.759265 +03:00 < access-control-allow-headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding
  DEBUG   2021-07-08 13:15:01.759277 +03:00 < access-control-expose-headers: X-Sentry-Error, Retry-After
  DEBUG   2021-07-08 13:15:01.759287 +03:00 < access-control-allow-origin: *
  DEBUG   2021-07-08 13:15:01.759297 +03:00 < vary: Accept-Language, Cookie
  DEBUG   2021-07-08 13:15:01.759353 +03:00 < content-language: en
  DEBUG   2021-07-08 13:15:01.759375 +03:00 < x-frame-options: deny
  DEBUG   2021-07-08 13:15:01.759386 +03:00 < x-content-type-options: nosniff
  DEBUG   2021-07-08 13:15:01.759397 +03:00 < x-xss-protection: 1; mode=block
  DEBUG   2021-07-08 13:15:01.759408 +03:00 < x-envoy-attempt-count: 1
  DEBUG   2021-07-08 13:15:01.759418 +03:00 < x-envoy-upstream-service-time: 42
  DEBUG   2021-07-08 13:15:01.759431 +03:00 < x-served-by: getsentry-web-default-production-7c7cb565bc-rl9zr
  DEBUG   2021-07-08 13:15:01.759444 +03:00 < x-served-by: lb-5
  DEBUG   2021-07-08 13:15:01.759453 +03:00 < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  DEBUG   2021-07-08 13:15:01.759574 +03:00 response status: 302
  DEBUG   2021-07-08 13:15:01.759612 +03:00 body: {"slug":"halo","detail":{"code":"resource-moved","message":"Resource has been moved","extra":{"url":"/api/0/projects/reneza/halo/releases/","slug":"halo"}}}
error: project not found
  DEBUG   2021-07-08 13:15:01.760322 +03:00 client close; no transport to shut down  (from sentry)
```

**Comment by kamilogorek** [comment]
You can see in the docs that request was sent to `https://sentry.io/api/0/projects/reneza/reneza/releases/` which is in form of `https://sentry.io/api/0/projects/<org>/<project>/releases/`/.
Error states that the project has been moved permanently to the slug called `halo` (which is correct).

What happens then, is that `.sentryclirc` stored in `/Users/<Me>/repo/work/<Project>/.sentryclirc` most likely still includes:

```
[default]
org=reneza
project=reneza
```

You can confirm this by issuing `SENTRY_LOG_LEVEL=debug sentry-cli releases -p halo list` command. You should be able to find log containing an entry `request POST https://sentry.io/api/0/projects/reneza/halo/releases/` instead.

Although webpack plugin should pick up your plugin config as well, so not sure why it doesn't.
Just to be sure, can you run your webpack with debug log level (same as above, just with webpack command.

**Comment by TheImpressionist** [comment]
Odd thing is, the project did not include `.sentryclirc` before I tried to get the info with the CLI. I have debug on, but it doesn't output any useful information when trying to deploy. I'll investigate further.

**Comment by TheImpressionist** [comment]
Removed the file, nothing changed. It still throws the same error. I suppose I'll opt out of having sourcemaps for a while until I get the response from support.

**Comment by kamilogorek** [comment]
> Just to be sure, can you run your webpack with debug log level (same as above, just with webpack command.

> So by the looks of it, the plugin is completely ignoring my config passed to it.

We can confirm that by looking at debug logs and where requests are going. Just use some random org/proj values that we can then compare with logs.

**Comment by TheImpressionist** [comment]
The only log I got with debug on was:

```
231 [Sentry Webpack Plugin] DEBUG: Injecting release code
232 [Sentry Webpack Plugin] DEBUG: Loaders:
233 [
234  '<unknown loader>',
235  '/builds/reneza/reneza-webapp/node_modules/eslint-loader/dist/cjs.js',
236  '<unknown loader>',
237  '/builds/reneza/reneza-webapp/node_modules/@sentry/webpack-plugin/src/sentry.loader.js'
238 ]
239 [Sentry Webpack Plugin] DEBUG: Added loaders:
240 [
241  '/builds/reneza/reneza-webapp/node_modules/@sentry/webpack-plugin/src/sentry.loader.js'
242 ]
243 [Sentry Webpack Plugin] DEBUG: Removed loaders:
244 []
245 [Sentry Webpack Plugin] DEBUG: Entry:
246 [
247  '/builds/reneza/reneza-webapp/node_modules/@sentry/webpack-plugin/src/sentry-webpack.module.js',
248  '/builds/reneza/reneza-webapp/src/index.tsx'
249 ]
250[Sentry Webpack Plugin] DEBUG: Added entry:
251 [
252  '/builds/reneza/reneza-webapp/node_modules/@sentry/webpack-plugin/src/sentry-webpack.module.js'
253 ]
254 [Sentry Webpack Plugin] DEBUG: Removed entry:
255 [] 
256 Browserslist: caniuse-lite is outdated. Please run:
257 npx browserslist@latest --update-db
258 Failed to compile.
259 Sentry CLI Plugin: Command failed: /builds/reneza/reneza-webapp/node_modules/@sentry/cli/sentry-cli releases new 795a8d563199eaa734e396e576fbf214e289f683
260 error: An organization slug is required (provide with --org)
```

That's a new error, actually. Same config as above. Nothing has changed:

```javascript
new SentryWebpackPlugin({
  authToken: process.env.SENTRY_AUTH_TOKEN,
  include: './build',
  org: 'reneza',
  project: 'halo',
  ignoreFile: '.sentrycliignore',
  ignore: ['node_modules'],
  debug: true,
})
```

**Comment by kamilogorek** [comment]
`debug: true` is for plugin injection itself, so we don't need it. It's `SENTRY_LOG_LEVEL=debug webpack` that we need.

What plugin version do you use?

**Comment by kamilogorek** [comment]
You can also use config file directly:

```js
new SentryWebpackPlugin({
  include: './build',
  ignoreFile: '.sentrycliignore',
  ignore: ['node_modules'],
  configFile: './.sentryclirc'
})
```

```ini
[default]
org=reneza
project=halo
```

CLI should still be able to read your `SENTRY_AUTH_TOKEN` without it being manually passed just fine thanks to https://github.com/getsentry/sentry-cli/blob/dbfa02d2ac9ad4e25cdbdb0ed1135bd775527205/src/config.rs#L542-L544

**Comment by TheImpressionist** [comment]
> `debug: true` is for plugin injection itself, so we don't need it. It's `SENTRY_LOG_LEVEL=debug webpack` that we need.
> 
> What plugin version do you use?

Running that now with `SENTRY_LOG_LEVEL=debug webpack`

I'm using `1.16.0`. Will try using `sentry.properties` next.

**Comment by TheImpressionist** [comment]
This is all the output that I got using both `sentry.properties`, and the plugin config.

Output:
```
  DEBUG   2021-07-08 18:18:55.084165 +03:00 sentry-cli version: 1.67.1, platform: "darwin", architecture: "x86_64"
  INFO    2021-07-08 18:18:55.085074 +03:00 sentry-cli was invoked with the following command line: "/Users/<ME>/repo/work/<PROJECT>/node_modules/@sentry/cli/sentry-cli" "releases" "new" "1df839ca31cb8cc1b6c4465e5af2d8d0ef598b08"
error: An organization slug is required (provide with --org)
  DEBUG   2021-07-08 18:18:55.120994 +03:00 client close; no transport to shut down  (from sentry)
  DEBUG   2021-07-08 18:18:55.121047 +03:00 skipping update nagger because session is not attended
```

`sentry.properties`
```javascript
new SentryWebpackPlugin({
  include: './build',
  ignoreFile: '.sentrycliignore',
  ignore: ['node_modules'],
  configFile: '../sentry.properties',
}),
```

The file is located in the parent folder. But it really doesn't matter, same thing happens if both files are in the same folder. Just to eliminate that possibility.

**Comment by kamilogorek** [comment]
Tbh I've no clue what's going on here. You are the first person reporting even remotely similar issue :3

**Comment by TheImpressionist** [comment]
> Tbh I've no clue what's going on here. You are the first person reporting even remotely similar issue :3

I'll have a look at the `@sentry/cli` lib in the near future just in case. But I feel like I may just have been cursed or something.

**Comment by robinson90** [comment]
> @leoyb can you run it with `--log-level=debug` and provide the logs?

Sentry CLI Plugin: Command failed: /Users/robin/Documents/xyh/mobile-teacher-welfare/node_modules/@sentry/cli/sentry-cli releases new 0.0.1
  INFO    2021-09-23 23:13:36.190199 +08:00 Loaded config from /Users/robin/Documents/xyh/mobile-teacher-welfare/.sentryclirc
  DEBUG   2021-09-23 23:13:36.191566 +08:00 sentry-cli version: 1.68.0, platform: "darwin", architecture: "x86_64"
  INFO    2021-09-23 23:13:36.191860 +08:00 sentry-cli was invoked with the following command line: "/Users/robin/Documents/xyh/mobile-teacher-welfare/node_modules/@sentry/cli/sentry-cli" "releases" "new" "0.0.1"
  DEBUG   2021-09-23 23:13:36.193471 +08:00 request POST https://sentry-test.xiaoyuanhao.com/api/0/projects/sentry/mobile-micro-teacher-welfare/releases/
  DEBUG   2021-09-23 23:13:36.193788 +08:00 using token authentication
  DEBUG   2021-09-23 23:13:36.194154 +08:00 json body: {"version":"0.0.1","projects":["mobile-micro-teacher-welfare"],"dateStarted":"2021-09-23T15:13:36.193452Z"}
  DEBUG   2021-09-23 23:13:36.194168 +08:00 retry number 0, max retries: 0
  DEBUG   2021-09-23 23:13:36.247661 +08:00 > POST /api/0/projects/sentry/mobile-micro-teacher-welfare/releases/ HTTP/1.1
  DEBUG   2021-09-23 23:13:36.247699 +08:00 > Host: sentry-test.xiaoyuanhao.com
  DEBUG   2021-09-23 23:13:36.247709 +08:00 > Accept: */*
  DEBUG   2021-09-23 23:13:36.247717 +08:00 > Connection: TE
  DEBUG   2021-09-23 23:13:36.247725 +08:00 > TE: gzip
  DEBUG   2021-09-23 23:13:36.247733 +08:00 > User-Agent: sentry-cli/1.68.0
  DEBUG   2021-09-23 23:13:36.248155 +08:00 > Authorization: Bearer bacd7431***
  DEBUG   2021-09-23 23:13:36.248167 +08:00 > Content-Type: application/json
  DEBUG   2021-09-23 23:13:36.248173 +08:00 > Content-Length: 107
  DEBUG   2021-09-23 23:13:36.276757 +08:00 < HTTP/1.1 404 Not Found
  DEBUG   2021-09-23 23:13:36.276785 +08:00 < Date: Thu, 23 Sep 2021 15:15:06 GMT
  DEBUG   2021-09-23 23:13:36.276793 +08:00 < Content-Type: application/json
  DEBUG   2021-09-23 23:13:36.276811 +08:00 < Content-Length: 50
  DEBUG   2021-09-23 23:13:36.276817 +08:00 < Connection: keep-alive
  DEBUG   2021-09-23 23:13:36.276829 +08:00 < Access-Control-Allow-Headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding
  DEBUG   2021-09-23 23:13:36.276836 +08:00 < X-Content-Type-Options: nosniff
  DEBUG   2021-09-23 23:13:36.276843 +08:00 < Content-Language: en
  DEBUG   2021-09-23 23:13:36.276848 +08:00 < Access-Control-Expose-Headers: X-Sentry-Error, Retry-After
  DEBUG   2021-09-23 23:13:36.276856 +08:00 < Vary: Accept-Language, Cookie
  DEBUG   2021-09-23 23:13:36.276863 +08:00 < X-XSS-Protection: 1; mode=block
  DEBUG   2021-09-23 23:13:36.276869 +08:00 < Allow: GET, POST, HEAD, OPTIONS
  DEBUG   2021-09-23 23:13:36.276875 +08:00 < Access-Control-Allow-Origin: *
  DEBUG   2021-09-23 23:13:36.276882 +08:00 < Access-Control-Allow-Methods: GET, POST, HEAD, OPTIONS
  DEBUG   2021-09-23 23:13:36.276887 +08:00 < X-Frame-Options: deny
  DEBUG   2021-09-23 23:13:36.276913 +08:00 response status: 404
error: project not found
  DEBUG   2021-09-23 23:13:36.279012 +08:00 client close; no transport to shut down  (from sentry)
  DEBUG   2021-09-23 23:13:36.279404 +08:00 skipping update nagger because session is not attended

**Comment by chris-mactavis** [comment]
I fixed mine by checking the sentry.properties file, making sure the defaults.project is the actual project name

**Comment by SashaMihalache** [comment]
@chris-mactavis Thank you, this fixed it.

In my case, the sentry project was renamed in the portal by a colleague and we forgot to update the sentry.properties to point to the new name.

**Comment by phoenixeliot** [comment]
Just chiming in in case this helps anyone else: This happened when someone updated the organization slug in Sentry's web interface. I had to update the environment variable on Vercel manually, and update `sentry.properties`.

**Comment by lumenwrites** [comment]
@phoenixeliot Thank you so much for posting this, this helped!

**Comment by wachidmudi** [comment]
> Just chiming in in case this helps anyone else: This happened when someone updated the organization slug in Sentry's web interface. I had to update the environment variable on Vercel manually (the one created by the integration), and update `sentry.properties`.

Thank you, confused due to message "project not found" and it's actually organization value that doesn't match 😂. Instead of relying on org name now i use org slug.

**Comment by phoenixeliot** [comment]
(Hilariously, I ran into this again when I changed a project name and in the end it was my own comment that reminded me what I needed to do to fix it)

**Comment by EngineerYhLee** [comment]
I was stupid. I didn't change my project name in next.config.js. I realized that after deleting the project...
