### ISSUE TITLE
Sentry Webpack Plugin ENOENT

### ISSUE THREAD

**Issue by lemonlesi** [getsentry/sentry-webpack-plugin#120]
Hi, I'm trying to upload source maps to Sentry using the Webpack plugin. I have followed the original documentation. We are using Node Serverless run through Webpack 4.25.1, using Sentry CLI 1.41.1 and Sentry Webpack Plugin 1.6.2. When running `yarn build` I get the following error.

```
ERROR in Sentry CLI Plugin: spawn /Users/alexandru/Documents/leonql/node_modules/@sentry/cli/sentry-cli ENOENT
 
  Error --------------------------------------------------
 
  Webpack compilation error, see above
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           11.6.0
     Serverless Version:     1.32.0
 
error Command failed with exit code 1.
```

Once I checked the folder to see if sentry-cli is installed properly I found that there is nothing at the path mentioned in the error. Rather the path /Users/alexandru/Documents/leonql/node_modules/@sentry/cli/**bin**/sentry-cli seems to be the correct one. Looks like there might be some misconfiguration somewhere. Any suggestions how to solve this?

**Comment by zlwaterfield** [comment]
I am also running into this @kamilogorek, any idea what may be wrong here?

**Comment by xiaoyanzheng** [comment]
I also encountered the same problem，@sentry/cli/sentry-cli can not install

**Comment by kamilogorek** [comment]
`sentry-cli` uses npm's `install` script to create a correct binary for the given environment - https://github.com/getsentry/sentry-cli/blob/7cc79fe8b8a88118be855f83ef6f562763d1a75c/package.json#L6

https://github.com/getsentry/sentry-cli/blob/master/scripts/install.js

![image](https://user-images.githubusercontent.com/1523305/57220323-2c2afd00-6ffb-11e9-9101-63d0c16f806b.png)

`./bin/sentry-cli` is used to directly talk with the binary through JS api and it's not necessary for the webpack-plugin itself.

There's a chance that serverless has `ignore-scripts` configured by default and you have to either re-enable it or build the binary yourself, see: https://blog.npmjs.org/post/141702881055/package-install-scripts-vulnerability

**Comment by lemonlesi** [comment]
It turns out that my issue was most likely related to an empty js file. While I'm not 100% sure this is in fact what solved it for me I can no longer reproduce it at least.

**Comment by JensKolb** [comment]
> There's a chance that serverless has `ignore-scripts` configured by default and you have to either re-enable it or build the binary yourself, see: https://blog.npmjs.org/post/141702881055/package-install-scripts-vulnerability

Thanks, that was the issue for me!

Just for google, the error for me (with expo) was:
`Error uploading sourcemaps to Sentry: spawn [OUR PROJECT]/node_modules/@sentry/cli/sentry-cli ENOENT`

**Comment by tobbbe** [comment]
Deleting package-lock.json was the solution for me:
https://github.com/getsentry/sentry-webpack-plugin/issues/273#issuecomment-823693970
