### ISSUE TITLE
upload progress is always stuck

### ISSUE THREAD

**Issue by frankshin** [getsentry/sentry-webpack-plugin#123]
![image](https://user-images.githubusercontent.com/10525454/58476902-c0b0f700-8184-11e9-9f79-12bd0ecbbdda.png)
the upload progress is always stuck when near finished

**Comment by kamilogorek** [comment]
@frankshin try to remove the plugin, purge the cache and reinstall it (without lock file). In the recent version of sentry-cli, we improved upload speed by ~40x and the file size limit is now in GB rather than tens of MBs. It should help to resolve your issue
