### ISSUE TITLE
How does the release get injected in to compiled react code?

### ISSUE THREAD

**Issue by dte** [getsentry/sentry-webpack-plugin#126]
I have configured Sentry webpack and it all looks good. However, when I init Sentry in my React top-level code with `Sentry.init({ dsn: 'https://xxx@sentry.xxxx.io/123' });` it is not clear if I also need to specify the release here as well or if it is introspected automatically. 

With this webpack tool do I also need to add `release` to `Sentry.init()`?

**Comment by kamilogorek** [comment]
> if I also need to specify the release here as well or if it is introspected automatically.

You don't need to. From README.md:

> By default, the release will be injected into all entry points.

> With this webpack tool do I also need to add release to Sentry.init()?

No, it's done automatically based on you release settings in `webpack.config.js`

All entries are passed through this modifier https://github.com/getsentry/sentry-webpack-plugin/blob/master/src/sentry.loader.js which attaches the snippet inside to the file itself.

**Comment by dte** [comment]
Awesome, thank you. Unfortunately it is not working for me (as in the release is not passed in with errors that are generated). I can attach the network request but it is not actually passing the release version. Any ideas on how to start debugging?

**Comment by kamilogorek** [comment]
Are you using node or browser package? First, you have to confirm whether the entry point gets correctly modified (just grep for `SENTRY_RELEASE` in the produced bundle).
If it's a browser, see whether `window.SENTRY_RELEASE` is a thing, if so, then you can attach network request if it's still not working fine.

**Comment by dte** [comment]
In react I have `import * as Sentry from '@sentry/browser';` I do not see `SENTRY_RELEASE` in the compiled bundle. 

The webpack config is:
```
entry: {
     console: './client/scripts/react/containers/console/Page.js',
}
```
```
output: {
	path: path.resolve(__dirname, 'public', 'bundle'),
	filename: '[name].bundle.js',
	publicPath: '/bundle/',
},
```
```
new SentryWebpackPlugin({
	include: './public/bundle',
	ignoreFile: '.sentrycliignore',
	ignore: ['node_modules', 'webpack.config.js', 'public'],
	configFile: 'sentry.properties',
}),
```

**Comment by dte** [comment]
Any ideas? I can try to manually set `entrypoints` but it looks like that should work without being manually set.

**Comment by kamilogorek** [comment]
Does it work with manually specified entrypoints? If so, then it's definitely a bug we'll have to fix.

**Comment by dte** [comment]
Manually adding:

```javascript
new SentryWebpackPlugin({
	include: ['./public/bundle/console.bundle.js', './public/bundle/console.bundle.js.map', './public/bundle/commons.bundle.js', './public/bundle/commons.bundle.js.map'],
	ignoreFile: '.sentrycliignore',
	entries: ['console'],
	ignore: ['node_modules', 'webpack.config.js', 'public'],
	configFile: 'sentry.properties',
}),
```

does show the release being entered in to the bundle
<img width="773" alt="Screen Shot 2019-06-17 at 1 27 30 PM" src="https://user-images.githubusercontent.com/585865/59624036-bfc81100-9103-11e9-9d65-ebb3e8372234.png">

That said, I'm still getting `release = n/a` even with this variable is being populated.

**Comment by kamilogorek** [comment]
I just tested it locally with the same config and wasn't able to reproduce, it works just fine with both `entries` and with no `entries`. Can you provide a repro case for it?
As for release being not included in the events, make sure that this loader's code is actually evaluated _before_ `Sentry.init` call, not after, as it's assigned only once.

**Comment by tstirrat15** [comment]
I don't see `window.SENTRY_RELEASE` referenced anywhere in the `@sentry/browser` code, nor do I see `global.SENTRY_RELEASE` referenced anywhere in the `@sentry/node` code. I saw that you can set it via the `SENTRY_RELEASE` env var on the backend, but it seems like you'd have to explicitly grab the global `SENTRY_RELEASE` variable and pass it to the `init` call for each of the SDKs.

Contrast this with `raven-js`, where it is [pulled in automatically](https://github.com/getsentry/sentry-javascript/blob/a01b4ee7f7ba03167d7424daae2fb2f2206687cb/packages/raven-js/src/raven.js#L81). Was this an intentional decision, or is this a place where the new SDKs haven't reached feature parity yet?

**Comment by tstirrat15** [comment]
See getsentry/sentry-javascript#2107. There should probably be an issue in Node as well.
