### ISSUE TITLE
feature request: set sourceMappingURL to sentry artifacts location

### ISSUE THREAD

**Issue by jamime** [getsentry/sentry-webpack-plugin#130]
I'd like to utilise sentry's authentication to protect my source maps. 

After the sourcemaps have been uploaded I would like sourceMappingURL to point to the sentry artifact location.

This would allow authenticated users to debug.

[Reference article.](https://itnext.io/using-sourcemaps-on-production-without-revealing-the-source-code-%EF%B8%8F-d41e78e20c89)

**Comment by kamilogorek** [comment]
Sounds good, however, this repo it's just a webpack wrapper around CLI JS API. Can you link this issue here https://github.com/getsentry/sentry-cli/ ? Thanks!
