### ISSUE TITLE
Sourcemaps not applied (minimal repo)

### ISSUE THREAD

**Issue by verekia** [getsentry/sentry-webpack-plugin#138]
Hi,

I am trying to get the client-side source maps applied on Sentry without success. I made a minimal repo to illustrate the problem: https://github.com/verekia/sentry-sourcemaps

Here is a link to an event: https://sentry.io/organizations/jonathan-verrecchia/issues/1223237123/

And some screenshots:

<img width="752" alt="Screenshot 2019-09-14 01 19 52" src="https://user-images.githubusercontent.com/522007/64878766-3c30a880-d68f-11e9-9f69-90fe1ea84028.png">

<img width="577" alt="Screenshot 2019-09-14 01 20 08" src="https://user-images.githubusercontent.com/522007/64878773-42268980-d68f-11e9-8b98-3c47b645a351.png">

<img width="1212" alt="Screenshot 2019-09-14 01 31 40" src="https://user-images.githubusercontent.com/522007/64878851-726e2800-d68f-11e9-8625-64dcf6f8e7f5.png">

<img width="865" alt="Screenshot 2019-09-14 01 19 11" src="https://user-images.githubusercontent.com/522007/64878872-7b5ef980-d68f-11e9-8a83-f39f0fd1d07e.png">

<img width="885" alt="Screenshot 2019-09-14 01 19 18" src="https://user-images.githubusercontent.com/522007/64878875-7dc15380-d68f-11e9-89b5-323df91c1eb5.png">

What am I doing wrong here? :)

I've tried `urlPrefix`, putting my files at the root. Nothing seems to affect the result on Sentry.

Thank you very much.

**Comment by kamilogorek** [comment]
Hey @verekia, unfortunately (or fortunately?) it's not the issue with Sentry itself, but rather with Webpack producing incorrect builds.
When running your repro, notice that Chrome itself is not even able to read them, despite detecting them correctly:

![image](https://user-images.githubusercontent.com/1523305/64961526-ff82ce00-d895-11e9-90a4-980ee44c3f25.png)

There is currently an open issue in Webpack repo, as the old one has been closed. See: https://github.com/webpack/webpack/issues/9461 and https://github.com/webpack/webpack/issues/4560

**Comment by verekia** [comment]
I've been able to fix my issue! While the Webpack thing was certainly an issue, I think the main problem was that I was including the root folder while my files were in `dist`.

After rewriting the code with `require`, the following configuration worked for me:
```js
new SentryWebpackPlugin({ include: 'dist', urlPrefix: '~/dist' })
```

<img width="837" alt="Screenshot 2019-09-17 00 35 08" src="https://user-images.githubusercontent.com/522007/64972139-bce7e280-d8e3-11e9-9753-fb2e3613f77d.png">

I've updated the repo in case someone has the same problem.

By the way, regarding `urlPrefix`, I would suggest documenting what the `~` means, which is quite unclear :)

Thank you for your help!

**Comment by verekia** [comment]
Also, the `import` syntax works correctly on Sentry after a Babel transformation.

**Comment by kamilogorek** [comment]
Thanks for the writeup @verekia! Regarding the `~` sign, have you read https://docs.sentry.io/cli/releases/ as well? If no, is this still not clear enough after reading? If so, I'll try to fix that :)

**Comment by verekia** [comment]
I guess it helps. Maybe having a link to that specific section of this page on the Webpack plugin's Readme would help. It's just that in this kind of project, there are so many different "paths" of everything, that it's easy to lose track.

- The path on the file system
- The path of the `output` of Webpack
- The public URL, starting with `/`
- The Sentry Webpack plugin `urlPrefix`, starting with `~/`
- The Sentry Webpack plugin `include`
- The path showed on Sentry errors, which is not `~/` but `/`

It easily gets mixed up and can be quite confusing. I feel like it's better to over-document than under-document these things.

**Comment by kamilogorek** [comment]
Thanks!
