### ISSUE TITLE
Sentry can't find my electron sourcecode

### ISSUE THREAD

**Issue by stoefln** [getsentry/sentry-webpack-plugin#146]
I successfully set up the plugin, and it's uploading sources and source maps without any issues:

```
Source Map Upload Report
  Scripts
    ...
    ~/app/worker.js
    ~/cli/start.js
    ~/index.js
  Minified Scripts
    ~/static/main-bundle.js (sourcemap at main-bundle.js.map)
    ~/static/worker-bundle.js (sourcemap at worker-bundle.js.map)
  Source Maps
    ~/static/main-bundle.js.map
    ~/static/worker-bundle.js.map

```

However, when I crash my electron app it complains about not finding source code. The stacktraces are not translated either.
I wonder why this is. The only issue I might see is that the stacktraces refer to file `app:///static/main-bundle.js` and the asset is listed as `~/static/main-bundle.js`

See screenshots:

<img width="1107" alt="Screenshot 2019-10-09 at 21 04 00" src="https://user-images.githubusercontent.com/562800/66549343-6452e080-eb43-11e9-938b-4984d0343b45.png">
<img width="1411" alt="Screenshot 2019-10-09 at 21 00 52" src="https://user-images.githubusercontent.com/562800/66549344-6452e080-eb43-11e9-83e0-44a13e25e4d7.png">

**Comment by kamilogorek** [comment]
Can you provide a link to the event from the screenshots?

**Comment by stoefln** [comment]
@kamilogorek https://sentry.io/organizations/stephan-petzl/issues/1262807278/?project=1554144&query=is%3Aunresolved

**Comment by kamilogorek** [comment]
@stoefln you didnt' specify a correct release for the upload.
https://sentry.io/organizations/stephan-petzl/releases/Repeato0.4.1/?project=1554144&statsPeriod=14d vs.
See: https://sentry.io/organizations/stephan-petzl/releases/Repeato0.4.1/artifacts/

**Comment by stoefln** [comment]
OK, I figured it out: For some reason the sentry js sdk uses AppName+Version as the release name and the webpack upload plugin uses the current githash by default -> mismatch.
What I did to make it work is to use also AppName+Version in the webpack upload configuration:

```
const package = require('./package.json')
...
new SentryCliPlugin({
      release: 'Repeato' + package.version,
      include: '.',
      ignoreFile: '.sentrycliignore',
      ignore: ['node_modules', 'webpack.config.js', 'webpack.production.config.js'],
      configFile: 'sentry.properties',
      urlPrefix: '~/',
      debug: true
    })
```

You can close this issue, thanks for your help!
