### ISSUE TITLE
Adding "ext: '.css' " or "ext: 'css'" excludes .js and .map.* from upload

### ISSUE THREAD

**Issue by marco-fp** [getsentry/sentry-webpack-plugin#15]
The following config uploads the bundle.js, bundle.map.js and bundle.css.map effectively:
```
    new SentryCliPlugin({
      release: (hash) => hash,
      include: buildPath,
      ignore: ['.'],
      configFile: 'sentry.properties',
    }),
```

But adding either  `ext: '.css'` or `ext: 'css'` excludes those files from being uploaded, and bundle.css is uploaded. 
Am I doing something wrong?

**Comment by jan-auer** [comment]
Good point, docs are a bit misleading here. The `ext` option sets the full list of considered extensions, replacing the default. If you want to upload CSS in addition to javascript, then you should use: `ext: ['js', 'map', 'jsbundle', 'bundle', 'css']`.

@mitsuhiko [docs](https://docs.sentry.io/learn/cli/releases/#upload-source-maps) are a bit misleading here:
> Adds an additional file extension to be considered

The current behavior is probably fine - i.e. we still want users to be able to override that list - so I'd propose to change docs. What do you think?

**Comment by mitsuhiko** [comment]
@jan-auer agreed. Let’s update the docs
