### ISSUE TITLE
No valid versions available for https-proxy-agent-snyk-fork

### ISSUE THREAD

**Issue by flymecca** [getsentry/sentry-webpack-plugin#150]
- `node -v`: `8.9.3`
- `npm -v`: `5.5.1`
- `OS`: `Windows 10`

When installing @sentry/webpack-plugin I'm suddenly running into the same issue that I see here: https://github.com/getsentry/sentry-react-native/issues/681

### Expected behaviour 
npm install correctly installs the webpack-plugin package and all dependencies.

### Actual behaviour
````
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for https-proxy-agent-snyk-fork
````

Attempting to find the bad package directly yields:
`'https-proxy-agent-snyk-fork@*' is not in the npm registry`

### Steps to reproduce
package.json: `"@sentry/webpack-plugin": "^1.9.1"`

Run the following command  
`npm install`

**Comment by velser** [comment]
Hi. As for temporary solution while this package is not updated with fixed snyk version I've installed on top "snyk": "^1.237.1" as it's semantically supported by plugin and everything is fine now. 

Hope it will help if you still have a problem.

**Comment by flymecca** [comment]
@velser thank you that worked for me as well!

**Comment by javiergarciagonzalez** [comment]
This needs to be fixed asap by Sentry 🙏
