### ISSUE TITLE
Source maps not showing original code

### ISSUE THREAD

**Issue by yuanyuanlimaggie** [getsentry/sentry-webpack-plugin#158]
Hi, I have tried to upload source maps using webpack several times, but it looks like sentry still can't find the original code. 

Here is what I have for webpack config:

```
new SentryWebpackPlugin({
          include: './build/',
          whitelistUrls: [/.*analytics\.min\.js$/],
          ignoreFile: '.sentrycliignore',
          ignore: ['node_modules', 'webpack.config.js', 'segment.js'],
          configFile: 'sentry.properties',
          release: process.env.COMMIT_SHA,
        })
```

```
devtool: 'cheap-source-map',
```

One example: https://sentry.io/organizations/two-sigma/issues/1341551814/?project=1815774&referrer=slack

<img width="1260" alt="Screen Shot 2019-11-18 at 2 31 37 PM" src="https://user-images.githubusercontent.com/44100783/69083523-40bb6980-0a10-11ea-8429-1763134a66e0.png">

In the release artifacts, we do have both source files and map files:

![image](https://user-images.githubusercontent.com/44100783/69083599-69436380-0a10-11ea-985e-bcd0bf8d3fbc.png)

**Comment by kamilogorek** [comment]
Hey, `cheap-source-map` doesn't provide original content – https://webpack.js.org/configuration/devtool/
You have to upload a map that does that.

**Comment by Hzzz** [comment]
@kamilogorek I got the same problem, my sourcemaps not showing original code too.
![image](https://user-images.githubusercontent.com/6794355/69396623-d4957a00-0d1d-11ea-9d48-d31bc4582f42.png)
![image](https://user-images.githubusercontent.com/6794355/69396638-e4ad5980-0d1d-11ea-8a61-7359927eb042.png)

here is my `vue.config.js`:

```javascript
configureWebpack: config => {
    if (process.env.NODE_ENV === 'production') {
      config.devtool = 'source-map'
      config.plugins.push(
        new SentryWebpackPlugin({
          include: './dist',
          release: process.env.VUE_APP_RELEASE_VERSION,
          configFile: 'sentry.properties',
          urlPrefix: '~/static/js',
          ignoreFile: '.sentrycliignore',
          debug: true,
          rewrite: true,
          ignore: [
            'node_modules',
            'vue.config.js',
            'babel.config.js',
            'postcss.config.js',
            '.eslintrc.js'
          ]
        })
      )
    } 
  }
```

**Comment by kamilogorek** [comment]
@Hzzz your artifacts are uploaded incorrectly (you dont need `urlPrefix` if the files you upload (dist in this case) already have the same directory structure). See that it says `~/static/js/static/js/app.cffeefe7.js`, but should be `~/static/js/app.cffeefe7.js` instead.

**Comment by yuanyuanlimaggie** [comment]
i used `devtool: source-map` instead and it works! Thanks @kamilogorek
