### ISSUE TITLE
Assets Accessible at Multiple Origins

### ISSUE THREAD

**Issue by dorianrod** [getsentry/sentry-webpack-plugin#159]
Hi,

Sentry doc talks about assets accessible at multiple origin and I don't find the parameter to use. Is it doable with this webpack plugin?

In my use case, I have the same file which is  fetched with different origins.
Ex: file://www/app.js, https://mysite.fr/subsite1/app.js, https://mysite.fr/subsite2/app.js.
When an error is raised, one is created by file, but I'd like to group them as it's the same file.

Have a good day,
DR

**Comment by kamilogorek** [comment]
It's not possible through the plugin, but you can use our custom grouping settings to achieve that - https://docs.sentry.io/data-management/event-grouping/server-side-fingerprinting/
