### ISSUE TITLE
Source map doesn't work

### ISSUE THREAD

**Issue by YahngSungho** [getsentry/sentry-webpack-plugin#164]
![sentrySourcemap](https://user-images.githubusercontent.com/29212791/73480471-4c96b500-43dd-11ea-9fb1-52e2ff342cd4.png)

I don't know what to try anymore.

I use Webpack and set devtool to 'source-map'.
And my sentry-webpack-plugin configuration is like this
```

          include: './build/assets/',
          ignoreFile: '.gitignore',
          ignore: ['node_modules', 'webpack.config.js'],
          configFile: 'sentry.properties',
          // validate: true,
          // ext: ['js', 'jsx', 'map'],
          urlPrefix: '~/assets',
          setCommits: {
            repo: 'YahngSungho/LearnObit',
            commit: '8775b2e86fa6a5c6633bae24fa3a7af1bf2e4f6a'
          }
        
```

**Comment by kamilogorek** [comment]
Can you provide a link to the event above?

**Comment by YahngSungho** [comment]
The link is here:
https://sentry.io/organizations/learnobit/issues/1481310140
And sourcemap doesn't work for all issues.

**Comment by kamilogorek** [comment]
@YahngSungho it displays correctly for me ¯\_(ツ)_/¯ 

![image](https://user-images.githubusercontent.com/1523305/73641145-d9f13800-466f-11ea-81c2-88d5bc3a9931.png)

**Comment by YahngSungho** [comment]
Yes. I'm not sure why, but it's working fine now.
