### ISSUE TITLE
Cannot pass .sentryclirc 

### ISSUE THREAD

**Issue by phihochzwei** [getsentry/sentry-webpack-plugin#167]
Hi there, 

we are trying to integrate Sentry into our Ionic project. All works fine for now, except the assignment of the source maps. We found that, that we have to pass the urlPrefix to achieve this. However, when we create the .sentryclirc we receive the following error: 

```
error:` 15:0 Expecting "[Some('='), Some(':')]" but found EOF.

thread 'unnamed' panicked at 'Config not bound yet': src/libcore/option.rs:1166

stack backtrace:
   0: backtrace::backtrace::trace::h2213474b34a196b0 (0x1066aeb65)
   1: backtrace::capture::Backtrace::new::h6a584f0d685f03ae (0x1066adda8)
   2: sentry_cli::utils::system::init_backtrace::{{closure}}::h4eb92c9f4b593455 (0x1062af3d6)
   3: std::panicking::rust_panic_with_hook::hd3c20890ac648923 (0x10672f191)
   4: std::panicking::continue_panic_fmt::hf444d349a369432b (0x10672ebed)
   5: rust_begin_unwind (0x10672ead9)
   6: core::panicking::panic_fmt::h7bf9e431fd27d405 (0x10674eaf2)
   7: core::option::expect_failed::h8cc2002011e49ec5 (0x10674eb5e)
   8: sentry_cli::config::Config::current::h3477b6765832c575 (0x1061f88f7)
   9: sentry_cli::utils::system::print_error::h2adddb235eb9be22 (0x1062aeccf)
  10: sentry_cli::commands::main::h586b93c3ff3ef423 (0x1062aaaa3)
```

I checked the file but I don't understand, what exactly is the problem here or even IF there is a problem. The file looks like this:

```
const SentryWebpackPlugin = require('@sentry/webpack-plugin');

module.exports = {
  plugins: [
    new SentryWebpackPlugin({
      include: '.',
      ignore: ['node_modules', 'webpack.config.js'],
      configFile: 'sentry.properties',
      urlPrefix: '~/build/'
    })
  ]
}
```

Is this a bug or am I straight dumb?

**Comment by kamilogorek** [comment]
> error:` 15:0 Expecting "[Some('='), Some(':')]" but found EOF.

It looks like there was an error parsing your config file. Can you provide your `sentry.properties`? (of course sanitized)

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
