### ISSUE TITLE
error: API request failed   caused by: sentry reported an error: unknown error (http status: 405)

### ISSUE THREAD

**Issue by EvalGitHub** [getsentry/sentry-webpack-plugin#171]
i get an error described by follow words , can you help me?

> ERROR in Sentry CLI Plugin: Command failed: 
error: API request failed
  caused by: sentry reported an error: unknown error (http status: 405)
Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

**Comment by kamilogorek** [comment]
@EvalGitHub can you provide the debug log mentioned in the message?

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
