### ISSUE TITLE
Can you add automatic deletion after uploading? eg. deleteAfterCompile

### ISSUE THREAD

**Issue by ctq123** [getsentry/sentry-webpack-plugin#174]
### 1 ) background
I want to delete source-map files automatically after upload. and I do not want to use sentry-cli to delete them. just use webpack plugin. e.g webpack-sentry-plugin. it has a property name deleteAfterCompile，when I set it as true. It can help me to delete source-map files automatically

### 2）new requriement
add automatic deletion after uploading. eg. deleteAfterCompile

**Comment by kylemh** [comment]
This would be awesome.

I'm going to just manually do this as part of CI/CD in `rm`ing the sourcemaps after build, but it would be awesome to upload sourcemaps without shipping them.

**Comment by Realybig** [comment]
i want it !!! must be add !!! please !!!

**Comment by webxmsj** [comment]
期待此功能

**Comment by b-zurg** [comment]
From my cursory reading the sentry sourcemap upload happens in the `afterEmit` webpack compiler hook.

It's easy enough to add a custom plugin that happens on the `done` event. With glob and fs-extra this becomes quite simple.

In this example I'm showing a snippet from the webpack config focused on the plugins.  `dist` in the glob pattern is my output directory.

I think this is more reliable than any other option (running postbuild etc.) as it runs in the context of the webpack compilation.

e.g. 

```js
const glob = require("glob");
const { removeSync } = require("fs-extra");

...
plugins: [
  ...
  {
    apply: compiler =>
      compiler.hooks.done.tap("CleanJsMapPlugin", () =>
        glob("dist/**/*.js.map", (err, files) => files.forEach(f => removeSync(f)))
      ),
  },
  ...
]
```

**Comment by h0gar** [comment]
You need to call the callback so that the build process continues.

```
const glob = require("glob");
const { removeSync } = require("fs-extra");

...
plugins: [
  ...
  {
    apply: compiler =>
      compiler.hooks.done.tap("CleanJsMapPlugin", (compilation, cb) => {
        glob.sync(".webpack/**/*.js.map").forEach(f => removeSync(f));
        cb();
      }),
  },
  ...
]
```

**Comment by kamilogorek** [comment]
This webpack plugin doesn't know which files will be uploaded, so it has no idea which files would have to be removed. It's all base on the configs and defaults from `sentry-cli` itself.

There are also already plenty of ways to achieve this behavior, eg.:
https://github.com/johnagan/clean-webpack-plugin
https://github.com/getsentry/sentry-webpack-plugin/issues/174#issuecomment-660864788

Thus I believe it should not be the responsibility of this plugin to perform a cleanup, as it's a destructive operation.

**Comment by AlexBeauchemin** [comment]
I created a webpack plugin to easily do this if anyone stumble on that issue
https://github.com/AlexBeauchemin/webpack-delete-sourcemaps-plugin

It will clean up all the sourcemaps after the sentry upload
