### ISSUE TITLE
Multiple Webpack configurations with a different configFile causes only latest to be used

### ISSUE THREAD

**Issue by sman591** [getsentry/sentry-webpack-plugin#175]
I'm using a Webpack configuration that exports two configurations from my webpack config (rather than a single one). Loosely, this looks like:

```js
// webpack.config.js

export default () => {
  return [
    { 
      ...server-side bundle config,
      plugins: [new SentryPlugin({ configFile: 'server.properties' })],
    },
    {
      ...client-side bundle config,
      plugins: [new SentryPlugin({ configFile: 'client.properties' })],
    },
}
```

However, when Webpack runs to build both of these, Sentry's Webpack plugin uploads both the server- and client-side source maps & release information to the **client-side** Sentry project. The server-side sentry project doesn't receive anything.

Looking at the source for sentry-webpack-plugin, it looks like this is caused because SentryPlugin's constructor initializes SentryCli, whose initializer mutates `process.env.SENTRY_PROPERTIES`: https://github.com/getsentry/sentry-cli/blob/master/js/index.js#L34

Do you all have any thoughts on a good way to fix or work around this?

If we could defer initializing `SentryPlugin()` (or at least `SentryCli()`) until the plugin actually runs, I think that would work -- but I'm not sure if that is possible.

**Comment by kamilogorek** [comment]
Fixed in https://github.com/getsentry/sentry-cli/pull/667

**Comment by cola119** [comment]
I encountered this issue. Could you check?
https://github.com/getsentry/sentry-cli/pull/667#issuecomment-604875652

**Comment by sman591** [comment]
Thanks for reporting -- follow-up in https://github.com/getsentry/sentry-cli/pull/700

**Comment by kamilogorek** [comment]
Merged original issue, will release on Monday.
