### ISSUE TITLE
Debug mode not debugging?

### ISSUE THREAD

**Issue by strass** [getsentry/sentry-webpack-plugin#177]
Hi Sentry, had good success with this plugin at my last job and looking to set it up again. I remember it as being pretty simple, but am having some trouble this time - my releases aren't showing up and there is very little output from Sentry in my webpack logs.

- Dry run mode displays something: `[Sentry Webpack Plugin] DRY Run Mode` + `[Sentry Webpack Plugin] Proposed version: '955f17e7d0eddd0589682459bcf6232c66f1b6e7'` but this is the only sentry-specific output I can find
- Debug mode isn't displaying anything extra at all?

Is there a plugin ordering requirement? Something else I'm missing? I'm supplying configs via environment variable not via a file but I figured I would see more logs if it wasn't getting required config.

**Comment by kamilogorek** [comment]
Debug mode of the plugin itself only shows what changes it done to the local webpack config.
If you want a fully fledged debug logs, you need to as sentry-cli itself for it.

```terminal
$ SENTRY_LOG_LEVEL=info webpack
or
$ SENTRY_LOG_LEVEL=debug webpack
```

or in `.sentryclirc`

```ini
[log]
level=debug
```

**Comment by strass** [comment]
Thanks :)
