### ISSUE TITLE
configFile not being read

### ISSUE THREAD

**Issue by piotrblasiak** [getsentry/sentry-webpack-plugin#181]
This is my plugin config:

```
new SentryCliPlugin({
        release: `${name}@${version}`,
        include: outputPath,
        urlPrefix: "~/js",
        configFile: "sentry.properties",
      })
```

And my sentry.properties:

```
[defaults]
org=myorg
project=myproject
```

(I also tried without the [defaults]).

All I get is:

error: An organization slug is required (provide with --org)

It does work if I put it in my home directory .sentryclirc where I do have my auth.

**Comment by comm1x** [comment]
How did you fix it?

**Comment by piotrblasiak** [comment]
I had to make a sentry.properties file and use keys like auth.token= instead

**Comment by kamilogorek** [comment]
`.sentryclirc` is using `ini` format, where `.properties` file has a separate one.
