### ISSUE TITLE
configFile does not take effect and will conflict with the default

### ISSUE THREAD

**Issue by 5kinna** [getsentry/sentry-webpack-plugin#183]
1. Problem Description:
- After configuring configFile, but there is no .sentryclirc file in the root path, an error will be reported
- The root path contains the .sentryclirc file and the configFile option is configured to point to different files, and the items in the default file and the items in configFile

2. Use version
"@sentry/webpack-plugin": "^1.9.3"

3. Expect
Configure the value of configFile according to different environments without error

**Comment by kamilogorek** [comment]
Sorry, but I dont fully understand the issue. Regarding the error, make sure that `configFile` you are pointing to is using `properties` format, eg` auth.token=xyz` and not `ini` format as `.sentryclirc` eg. `[auth] token=`

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
