### ISSUE TITLE
Add release deploy 

### ISSUE THREAD

**Issue by ChaerilM** [getsentry/sentry-webpack-plugin#184]
can `releases deploys VERSION new -e ENVIRONMENT` be added?, 
maybe something like
`deploys: process.env.NODE_ENV`

**Comment by kamilogorek** [comment]
Hey, sure! Unfortunately, I don't have any spare time right now and I'm not sure when I'll be able to work on it.
Feel free to submit a PR and ask any questions along the way, I'll try to help.

Things that need to be changed:
- plugin options: https://github.com/getsentry/sentry-webpack-plugin/blob/master/src/index.js
- CLI public API: https://github.com/getsentry/sentry-cli/blob/master/js/releases/index.js
- docs for reference: https://docs.sentry.io/cli/releases/

**Comment by kamilogorek** [comment]
Ref: https://github.com/getsentry/sentry-cli/issues/713

**Comment by julien1619** [comment]
Hey!

I've just opened a PR https://github.com/getsentry/sentry-cli/pull/730 to add a `deploys` command on the public Node API.
Concerning webpack, I think `deploys` should be called only on deployment and not on restart for example. How do you think it should be exposed? I can see multiple solutions.

- Expose the sentry-cli command through the webpack plugin to let the developer calling `deploys` at the right time (using a dedicated script in package.json for example)
- Automate it when running a built version, but in this case it would need to generate and read a cache file.

**Comment by ChaerilM** [comment]
i personally compile webpack using CI then push the artifact to test / production with `yarn run prod` or something

**Comment by TheHolyWaffle** [comment]
https://github.com/getsentry/sentry-cli/pull/741 javascript deploy command was added, so this can now be integrated in sentry-webpack-plugin
