### ISSUE TITLE
Sentry CLI: Unable to determine version

### ISSUE THREAD

**Issue by njbarrett** [getsentry/sentry-webpack-plugin#185]
Hello,
I am deploying a Nuxt.js / Vue app on Zeit Now/Vercel and have setup my webpack config as follows:

```
...

const release = process.env.COMMIT_SHA || process.env.NOW_BITBUCKET_COMMIT_SHA || process.env.BUILD_STAGE;
// eslint-disable-next-line no-console
console.log('🚀 releasing', release);

if (process.env.SENTRY_PUBLISH_SOURCEMAPS === 'true') {
  config.build.plugins.push(new SentryWebpackPlugin({
    debug: true,
    release,
    include: '.',
    ignoreFile: '.sentrycliignore',
    ignore: [
      'node_modules',
      'node_modules_dev',
      'node_modules_prod',
      'tests',
      '*.config.js',
      '.eslintrc.js',
    ],
  }));
}
```

I have confirmed via the console.log command that "release" is being set to a valid commit sha,
however in the build I still see this error. 

ERROR in Sentry CLI Plugin: Unable to determine version. Make sure to include `release` option or use the environment that supports auto-detection https://docs.sentry.io/cli/releases/#creating-releases

**Comment by njbarrett** [comment]
Ive found this is also an issue locally when Git is not present.

**Comment by kamilogorek** [comment]
@njbarrett can you run the command with `LOG_LEVEL=debug` and paste the output? eg.

```terminal
LOG_LEVEL=debug webpack
```

**Comment by njbarrett** [comment]
@kamilogorek Here you go: https://pastebin.com/BiBLkKWc

You'll notice that it successfully uploads the source maps for client and server, but then seemingly the `finalizeRelease` function is called again by webpack but without all the options I defined

```

    attachAfterEmitHook(compiler, (compilation, cb) => {
      this.finalizeRelease(compilation).then(() => cb());
    });

```

**Comment by TheHolyWaffle** [comment]
I'm having the same error with version 1.11.1 . Here's my relevant portion of `next.config.js` configuration:
```
                config.plugins.push(
                    new SentryWebpackPlugin({
                        release: VERCEL_GITHUB_COMMIT_SHA,
                        include: ".next",
                        ignore: ["node_modules"],
                        urlPrefix: "~/_next",
                    })
                );
```

**Comment by goranefbl** [comment]
had the same issue, used options.buildId for the release version. next.js config file:

```
const withSass = require('@zeit/next-sass');
const withCSS = require('@zeit/next-css');
const withVideos = require('next-videos');
const withPlugins = require('next-compose-plugins');
const withSourceMaps = require('@zeit/next-source-maps')();
const SentryWebpackPlugin = require('@sentry/webpack-plugin');

module.exports = withPlugins(
	[
		[
			withSass,
			{
				cssModules: true,
				cssLoaderOptions: {
					importLoaders: 1,
					localIdentName: '[name]__[local]___[hash:base64:5]'
				}
			}
		],
		[withCSS, {}],
		[withVideos, {}],
		[withSourceMaps]
	],
	{
		webpack(config, options) {
			config.module.rules.push({
				test: /\.(woff|woff2|eot|ttf|otf)$/,
				use: [
					{
						loader: 'url-loader',
						options: {
							limit: 8192,
							fallback: 'file-loader',
							publicPath: `/_next/static/chunks/fonts/`,
							outputPath: `${options.isServer ? '../' : ''}static/chunks/fonts/`,
							name: '[name]-[hash].[ext]'
						}
					}
				]
			});
			config.module.rules.push({
				test: /\.(jpe?g|png|svg|gif|ico|webp)$/,
				use: [
					{
						loader: 'url-loader',
						options: {
							limit: 8192,
							fallback: 'file-loader',
							publicPath: `/_next/static/images/`,
							outputPath: `${options.isServer ? '../' : ''}static/images/`,
							name: '[name]-[hash].[ext]'
						}
					}
				]
			});

			config.module.rules.push({
				test: /\.(mp3)$/,
				use: [
					{
						loader: 'url-loader',
						options: {
							limit: 8192,
							fallback: 'file-loader',
							publicPath: `/_next/static/sound/`,
							outputPath: `${options.isServer ? '../' : ''}static/sound/`,
							name: '[name]-[hash].[ext]'
						}
					}
				]
			});
			config.module.rules.push({
				test: /\.scss$/,
				use: [
					{
						loader: 'sass-loader',
						options: {
							prependData: '@import "./static/scss/globals.scss";',
							sourceMap: true
						}
					}
				]
			});
			// Ask Webpack to replace @sentry/node imports with @sentry/browser when
			// building the browser's bundle
			if (!options.isServer) {
				// eslint-disable-next-line no-param-reassign
				config.resolve.alias['@sentry/node'] = '@sentry/browser';
			}
			// The Sentry webpack plugin gets pushed to the webpack plugins to build
			// and upload the source maps to sentry.
			config.plugins.push(
				new SentryWebpackPlugin({
					include: '.next',
					configFile: 'sentry.properties',
					release: options.buildId,
					ignore: ['node_modules'],
					urlPrefix: '~/_next'
				})
			);

			return config;
		},
		publicRuntimeConfig: {
			APP_ENV: process.env.APP_ENV
		}
	}
);

```

**Comment by TheHolyWaffle** [comment]
@goranefbl Is there anything relevant configured in your `sentry.properties` that we should know?

**Comment by vitalbone** [comment]
I had a similar issue where I was unable to build a next.js app on Vercel. Turns out following @goranefbl's [snippet](https://github.com/getsentry/sentry-webpack-plugin/issues/185#issuecomment-624401139) helped resolve my issue.

```js
require('dotenv').config();

const withPlugins = require('next-compose-plugins');
const withSourceMaps = require('@zeit/next-source-maps')();
const SentryWebpackPlugin = require('@sentry/webpack-plugin');
const withImages = require('next-images');

const nextConfiguration = {
  env: {
    SENTRY_DSN: process.env.SENTRY_DSN,
  },
  webpack: (config, options) => {
    if (!options.isServer) {
      config.resolve.alias['@sentry/node'] = '@sentry/browser';
    }

    if (
      process.env.SENTRY_DSN &&
      process.env.SENTRY_ORG &&
      process.env.SENTRY_PROJECT &&
      process.env.SENTRY_AUTH_TOKEN &&
      process.env.NODE_ENV === 'production'
    ) {
      config.plugins.push(
        new SentryWebpackPlugin({
          include: '.next',
          configFile: 'sentry.properties',
          release: options.buildId,
          ignore: ['node_modules'],
          urlPrefix: '~/_next',
        })
      );
    }
    return config;
  },
};

module.exports = withPlugins([withImages, withSourceMaps], nextConfiguration);

```

**Comment by goranefbl** [comment]
> @goranefbl Is there anything relevant configured in your `sentry.properties` that we should know?

Just: 
defaults.org = company
defaults.project = project

auth.token = token

Also for some reason .sentryclirc wasn't being found even tho it was in root dir.

**Comment by churichard** [comment]
I'm using Next.js and was running into this issue when following the `with-sentry-simple` example. Adding `release: options.buildId` to the `SentryWebpackPlugin` options like @vitalbone has in his code snippet fixed this issue for me.

**Comment by kamilogorek** [comment]
Closing the issue, as it seems like the original issue has been resolved.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by sambokai** [comment]
From https://github.com/zeit/next.js/issues/12454#issuecomment-626612603

> Using release: options.buildId in SentryWebpackPlugin fixes the upload issue indeed.
> 
> However, the Sentry.init(...) snippet in _app.js must also be updated. In there, the same release variable must be used as defined in next.config.js. This is to ensure that Sentry can link tracked errors to the correct corresponding release/sourcemaps. See https://docs.sentry.io/error-reporting/configuration/?platform=browsernpm#release

Which sounds more trivial than it is, because accessing the buildId within the nextjs runtime seems difficult.

**Comment by kamilogorek** [comment]
> Why do we have do specify a release, when using the sourcemap uploading in the first place?

@sambokai because artifacts that you are uploading are scoped per release. Otherwise we'd not be able to tell which version of the file to use when resolving sourcemaps.
