### ISSUE TITLE
Sourcemap bundled 0 files for upload (typescript & nextjs)

### ISSUE THREAD

**Issue by zyqxd** [getsentry/sentry-webpack-plugin#186]
Looking to debug what's going wrong here;

We're using next and typescript. Also using `@zeit/next-source-maps` to compile sourcemaps (by default it sets `devtools: source-map`:

##### Output:
``` 
Creating an optimized production build ...> Rewriting sources
> Adding source map references
> Bundled 0 files for upload
> Uploaded release files to Sentry
> File upload complete

Source Map Upload Report
Creating an optimized production build .> Rewriting sources
> Adding source map references
> Bundled 0 files for upload
> Uploaded release files to Sentry
> File upload complete
Creating an optimized production build .
Source Map Upload Report
Creating an optimized production build
```
Seems like 0 files are being bundled here

##### webpack config:
```js
const withSourceMaps = require('@zeit/next-source-maps');
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: process.env.BUNDLE_ANALYZE === '1',
});
const SentryWebpackPlugin = require('@sentry/webpack-plugin');

module.exports = withBundleAnalyzer({
  ...withSourceMaps({
    webpack(config, options) {
      ...

      if (process.env.SENTRY_RELEASE === '1') {
        config.plugins.push(
          new SentryWebpackPlugin({
            include: '.',
            ignore: [
              '.sentrycli',
              'node_modules',
              'public',
              'styles',
              '*.config.js',
              'next.config.runtime.js',
              'utils/external/FullStory/loadFullStory.js',
            ],
          }),
        );
      }

      return config;
    },
  }),
  ...
});
```

##### tsconfig.json
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    ...
    "sourceMap": true,
    "inlineSources": true,
    "sourceRoot": "/",
    "baseUrl": ".",
    "typeRoots": ["./node_modules/@types", "./types/"],
    "paths": {
      "~/*": ["./*"]
    },
    ...
  },
  "include": ["./**/*"],
  "exclude": [".next/**/*", "server/**/*", "node_modules/**/*"]
}

```

**Comment by kamilogorek** [comment]
We had some reports of `include: '.'` not handling dot-directories correctly.
Can you try to explicitly add `.next` to it? Thanks!

```js
include: ['.', '.next']
```

**Comment by zyqxd** [comment]
Perfect!

> We had some reports of `include: '.'` not handling dot-directories correctly.
> Can you try to explicitly add `.next` to it? Thanks!
> 
> ```js
> include: ['.', '.next']
> ```

**Comment by AssisrMatheus** [comment]
@zyqxd Did you manage to make sourcemaps work with next and typescript?

I followed the [with-sentry](https://github.com/vercel/next.js/tree/canary/examples/with-sentry) example and it looks like my files are uploaded, when I look at the "Releases" tab.

But when an exception is thrown, the sourcemap is not there:
![image](https://user-images.githubusercontent.com/12276174/86479283-38efd180-bd22-11ea-85ce-cc5bad2cde1a.png)

This is my next.config:
```
const withSourceMaps = require('@zeit/next-source-maps')();
const SentryWebpackPlugin = require('@sentry/webpack-plugin');

module.exports = withSourceMaps({
  webpack: (config, { webpack, buildId, isServer }) => {
    if (!isServer) {
      config.resolve.alias['@sentry/node'] = '@sentry/react';
    }

    if (
      process.env.NEXT_PUBLIC_SENTRY_DSN &&
      process.env.SENTRY_ORG &&
      process.env.SENTRY_PROJECT &&
      process.env.SENTRY_AUTH_TOKEN &&
      process.env.NODE_ENV !== 'development'
    ) {
      config.plugins.push(
        new SentryWebpackPlugin({
          include: ['.', '.next', 'pages', 'src'],
          ignore: [
            'node_modules',
            'public',
            '.awcache',
            '.circleci',
            '.storybook',
            'docs',
            'cypress',
            '.vscode',
            'docker-compose*'
          ],
          urlPrefix: '~/_next',
          release: buildId
        })
      );
    }

    return config;
  }
});
```

My tsconfig.json also has the correct configuration:
```
    "sourceMap": true,
    "inlineSources": true,
    "sourceRoot": "/"
```

And i'm using:
```
    "@sentry/browser": "^5.19.0",
    "@sentry/node": "^5.19.0",
    "@sentry/react": "^5.19.0",
    "@sentry/webpack-plugin": "^1.12.0",
    "@zeit/next-source-maps": "0.0.4-canary.1",
```

**Comment by AssisrMatheus** [comment]
@kamilogorek Regarding the above error. Do you think the reason might be that the path sent to Sentry is *encoded*? Like: `/_next/static/EK0mpBHd7QSxVevlbtOx5/pages/%5Blocale%5D.js`

And in the release artifacts it's not encoded? (note the brackets `[]`):
![image](https://user-images.githubusercontent.com/12276174/86480492-79e8e580-bd24-11ea-9cb1-79d96191e8b5.png)

**Comment by kamilogorek** [comment]
Can you provide a shared link to the event you used as an example above?

**Comment by AssisrMatheus** [comment]
@kamilogorek This one? https://sentry.io/share/issue/1720ebb792c7411a9f2bb8ce2952a9e4/

**Comment by kamilogorek** [comment]
Yes, thanks. And you are correct, the issue is that your stack trace frames are URI encoded (which is odd, as browsers don't do that by default).

Regular event (no brackets, or encoding):

![image](https://user-images.githubusercontent.com/1523305/86587514-0ba55c80-bf8a-11ea-9ffa-3b4ce819bdc9.png)

Event with brackets, not encoded:

![image](https://user-images.githubusercontent.com/1523305/86587547-19f37880-bf8a-11ea-81c3-ee06d8f45c1f.png)

Event with brackets, encoded:

![image](https://user-images.githubusercontent.com/1523305/86587569-22e44a00-bf8a-11ea-9ca2-1c4d621045a0.png)

If you think this should be handled differently, you can report an issue in the product itself here - https://github.com/getsentry/sentry

Cheers!

**Comment by AssisrMatheus** [comment]
@kamilogorek I think the path should at least be decoded before the service tries to match it with the source files. I submitted https://github.com/getsentry/sentry/issues/19713 for that. Thank you for your support!
