### ISSUE TITLE
Incorrect type definition

### ISSUE THREAD

**Issue by mjswensen** [getsentry/sentry-webpack-plugin#188]
In `@sentry/webpack-plugin@1.11.1`, the type definition in `index.d.ts` and the module in `src/index.js` do not match.

The type definition states that `SentryCliPlugin` is the default export for the module, but in `index.js`, `SentryCliPlugin` is simply assigned to `module.exports`.

Related to #144 and #145 .

I believe the solution is to change `index.js` as follows:

```js
module.exports.default = SentryCliPlugin;
```

and leave `index.d.ts` as-is.

Example usage with TypeScript:

```ts
import SentryCliPlugin from '@sentry/webpack-plugin';

const config = {
  plugins: [
    new SentryCliPlugin({...}),
  ],
};
```

Example usage with JavaScript (note the addition of `.default` on the `require` line):

```js
const SentryCliPlugin = require('@sentry/webpack-plugin').default;

const config = {
  plugins: [
    new SentryCliPlugin({...}),
  ],
};
```

The alternative would be to change `SentryCliPlugin` to a named export.

# Current workaround

TypeScript users must instruct TypeScript to ignore the false error:

```ts
import { Configuration } from 'webpack';
import * as SentryCliPlugin from '@sentry/webpack-plugin';

const config: Configuration = {
  plugins: [
    // @ts-ignore
    new SentryCliPlugin({...})
  ]
};

export default config;
```

Minor side note: The [documentation page for source maps](https://docs.sentry.io/platforms/javascript/sourcemaps/) appears to be out-of-date as it references `SentryWebpackPlugin` from this package rather than `SentryCliPlugin`.

**Comment by mjswensen** [comment]
Looking at [this comment](https://github.com/Microsoft/TypeScript/issues/2719#issuecomment-92167037) in the TypeScript repository, apparently the original syntax before #145 (`export = ...`) would have also worked.

TS input:

```ts
declare class SentryCliPlugin extends Plugin {}
export = SentryCliPlugin;
```

Transplied JS output (matches what is currently in `index.js`):

```js
"use strict";
module.exports = SentryCliPlugin;
```

Here's a [TypeScript playground](https://www.typescriptlang.org/play/index.html?module=1&ssl=2&ssc=26&pln=1&pc=1#code/CYUwxgNghgTiAEkoGdnwMogHYBcYE8BhCASwAUIBXAcxK3hAA8dtg0Ka74BvAXwCgmABwD2MHPAC8GbHiKkOtLAG5+QA) with this code in it.

**Comment by mjswensen** [comment]
So there are some options for resolution:

1. Merge #189 and update any documentation elsewhere
2. Decline #189 and instead revert the change in #145 

Thanks for your time, Sentry team!

**Comment by kamilogorek** [comment]
@mjswensen thanks for detailed report and PR. Can you check whether this solution would work for you? https://github.com/getsentry/sentry-webpack-plugin/pull/190

Looking at https://github.com/webpack-contrib/ this is how everyone is delivering their webpack plugins, with only difference being es6+babel instead of `module.exports.default` directly.

**Comment by mjswensen** [comment]
Thanks for the reply @kamilogorek . We ended up simply publishing our source maps publicly as that was more straightforward and has a few other benefits for us. But after a cursory look at #190 I suspect that you are right that it would solve the problem. Feel free to close this and #189 , and thanks again for your work.

**Comment by kamilogorek** [comment]
Thanks! I'll merge #190 after a review. Cheers!
