### ISSUE TITLE
API request failed, Couldn't resolve host name

### ISSUE THREAD

**Issue by rastogiachyut** [getsentry/sentry-webpack-plugin#193]
I'm trying to use this plugin so that I can use source-maps without exposing them. But I get this error when I try to create a new release.

The logs are:
```
INFO    2020-06-09 16:48:17.202613 +05:30 Loaded       
config from /Users/300070023/.sentryclirc                
INFO    2020-06-09 16:48:17.204011 +05:30 sentry-cli   
was invoked with the following command line: "/Users/3000
70023/myntra/spectrum-dexter/node_modules/@sentry/cli/sen
try-cli" "releases" "new" "2bf08cf22d8113d0be7eaf3b0b5ab6
7fb2963fc0"                                              
error: API request failed                                
  caused by: [6] Couldn't resolve host name
```

This is my webpack config:
```  
new SentryWebpackPlugin({
      include: '.',
      ignoreFile: '.sentrycliignore',
      ignore: ['node_modules', 'webpack.config.js'],
      configFile: 'sentry.properties',
      debug: true
    })
```

My .sentryslirc looks like:

```
[auth]
token=XXXX

[defaults]
url = https://sentry.xxx.com/
project=xyz
org=abc

[log]
level=info
```

**Comment by kamilogorek** [comment]
The error says it all: `Couldn't resolve host name`.
This means that your local machine/server is unable to communicate with whatever value you put in your `defaults.url` config.

**Comment by rastogiachyut** [comment]
@kamilogorek Thanks for the prompt reply, I can open https://sentry.xxx.com/ in my browser without using VPN,  can you suggest a way for me to debug what is blocking it?

**Comment by kamilogorek** [comment]
Change log level to `debug` first, and let's see if we get more details in there. (in your sentryclirc)

**Comment by rastogiachyut** [comment]
@kamilogorek I found the issue, there was another sentry.properties file with an incorrect URL, it gets higher priority then sentryslirc. Thanks for the help.

**Comment by orenmagen100** [comment]
> @kamilogorek I found the issue, there was another sentry.properties file with an incorrect URL, it gets higher priority then sentryslirc. Thanks for the help.

Can u plz reference where did you find the other sentry.properties? we're struggling with the same issue here
Thanks

**Comment by kamilogorek** [comment]
@orenmagen100 when you call `sentry-cli` with `SENTRY_LOG_LEVEL=debug` or `--log-level=debug` you should see an entry similar to:

```
  INFO    2020-07-08 10:48:50.931440 +02:00 Loaded config from /Users/kamilogorek/.sentryclirc
```
