### ISSUE TITLE
npm install gives error => Received 403: Forbidden

### ISSUE THREAD

**Issue by karna41317** [getsentry/sentry-webpack-plugin#194]
node --version
v12.16.1

Mac OS: 10.15.5

npm install --save-exact @sentry/webpack-plugin@latest

> @sentry/cli@1.54.0 install /Users/karant/Documents/Sites/code/blazar-core/node_modules/@sentry/cli
> node scripts/install.js

Error: Received 403: Forbidden
npm WARN acorn-jsx@5.2.0 requires a peer of acorn@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN connected-react-router@6.8.0 requires a peer of immutable@^3.8.1 || ^4.0.0-rc.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-blazar@1.4.1 requires a peer of eslint@^5.14.1 but none is installed. You must install peer dependencies yourself.
npm WARN The package handlebars-loader is included as both a dev and production dependency.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sentry/cli@1.54.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @sentry/cli@1.54.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/karant/.npm/_logs/2020-06-09T15_13_48_549Z-debug.log

**Comment by kamilogorek** [comment]
Hey, it looks like you have a connection issues to our CDN. You can resolve the issue by pointing the installer to an external mirror, like github releases. Cheers!

```
SENTRYCLI_CDNURL=https://github.com/getsentry/sentry-cli/releases/download/ npm install --save-exact @sentry/webpack-plugin@latest
```
