### ISSUE TITLE
How to use next to CompressionPlugin

### ISSUE THREAD

**Issue by emilsedgh** [getsentry/sentry-webpack-plugin#195]
Hi there.

According to the documentation [Sentry doesn't support GZip Artifacts](https://docs.sentry.io/platforms/javascript/sourcemaps/#verify-artifacts-are-not-gzipped).

Now, if you are using Webpack, there's a very good chance that you have CompressionPlugin enabled like I do (who  doesn't compress their assets?)

Is there any way to run this plugin next to CompressionPlugin?

Loading this plugin first doesn't seem to be effective.

**Comment by sibiraj-s** [comment]
Try this plugin. It can help. [copy-asset-in-memory-webpack-plugin](https://github.com/sibiraj-s/copy-asset-in-memory-webpack-plugin). We do this internally, just published it as a plugin.

```js
{
  plugins: [
    new CopyAssetInMemoryPlugin({
      test: /.js(.map)?$/,
      transformPath: (fileName) => {
        return fileName.replace("js/", "sentry/"); // <-- writing all files into sentry folder from js folder
      },
    }),
    new CompressionPlugin({
      filename: "[file]",
      exclude: /sentry/, // <-- exclude sentry
      minRatio: 10,
      deleteOriginalAssets: true,
    }),
    new SentryCliPlugin({
      release: APP_VERSION,
      include: PATHS.outDir + "/sentry/", // <-- uploading only the uncompressed files
      urlPrefix: "~/js", // <-- correcting url prefix to match the original assets
    }),
  ];
}
```
Note: The plugin only supports webpack 5

**Comment by grug** [comment]
Is there any chance this can be reopened? Not everyone is able to serve their application behind a CDN or server that can do the compression for us and not being able to use the compression plugin without the in-memory-copy solution in this thread seems a bit disappointing for a library that gets 4,000,000 downloads a month.

**Comment by lforst** [comment]
Hi @grug, not gonna promise anything on this because the team's priorities are somewhere else right now, but if we were to tackle this, how would it be solved best in your opinion?

My solution brainstorm rn:
- Uncompress files before uploading to Sentry?
- Accept gzipped files on Sentry backend

If you wanna take a stab at this yourself - PRs are always welcome!

**Comment by kamilogorek** [comment]
@lforst we already have the necessary functionality in the CLI, you can pass custom headers to all requests, so it should only require changes to the plugin itself. However, this one should be only applied to upload requests, not release creation/finalization.
If we decide to update a plugin to v2 (cc @lobsterkatie), we should also improve cli's JS-api, so it allow for multiple headers (which is possible in the binary itself).

**Comment by grug** [comment]
Thanks for getting back to me so quickly on this everyone. This is amazing.

@kamilogorek when you say the functionality is already in the CLI, does that mean there's a way today to add `Accept-Encoding: gzip` to file uploads to Sentry via the CLI? I'd be happy to switch to that until something was ready in the `sentry-webpack-plugin`

**Comment by kamilogorek** [comment]
> @kamilogorek when you say the functionality is already in the CLI, does that mean there's a way today to add Accept-Encoding: gzip to file uploads to Sentry via the CLI? 

Yup.

```terminal
sentry-cli sourcemaps upload ./dist --release=foo --header="Content-Encoding: gzip"
```

Note that its probably `Content-Encoding`, not `Accept-Encoding`, as you are the sender. Also make sure that if you use it, you also specify `deflate`.

**Comment by grug** [comment]
Ah yep, I meant `Content-Encoding: gzip` - my bad 😂 

This is great - I really appreciate such a quick turnaround on this. Is there anywhere I can follow for progress on the webpack plugin, or will this thread be fine?

Regarding specifying `deflate`, where am I specifying that? I wouldn't have imagined I'd need to specify it in the `Content-Encoding` header when sending up the files?

**Comment by kamilogorek** [comment]
> Is there anywhere I can follow for progress on the webpack plugin, or will this thread be fine?

Yup, should be fine with the reopened status.

> Regarding specifying deflate, where am I specifying that?

You need to list them in the same header, and in order the compression was applied, eg. `Content-Encoding: deflate, gzip`

**Comment by grug** [comment]
Am I correct in assuming that I can roll this all up into the following command: `sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps dist --url-prefix '~/foo/bar' --header="Content-Encoding: gzip"` - I assume so but just wanted to check since the example given was using the `sentry-cli sourcemaps upload` command :)

**Comment by grug** [comment]
We're fetching the CLI in our pipelines via the recommended way in [the docs](https://docs.sentry.io/product/releases/setup/release-automation/circleci/). Looking at the script at `https://sentry.io/get-cli/` it looks fairly unlikely we're going to get an old major release, I believe!

**Comment by grug** [comment]
You are a legend. Thank you so much for giving so much of your time. I hope other people stumbling across this thread find it helpful, too.

One other thing I can think of is that the [docs on troubleshooting sourcemaps](https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/) reflect the previous state of our conversation where artefacts couldn't be compressed. I assume this will be on the todo list to reflect the current state but just wanted to point it out 😄

**Comment by kamilogorek** [comment]
I take my words back. I found some time, and unfortunately cannot make it work. It appears that the header itself is not picked up. I'll schedule some time to debug this and will get back to you soon.

**Comment by kamilogorek** [comment]
@grug you should be able to update cli to `2.4.0`, pass `--decompress` flag and give it a go now :)

**Comment by grug** [comment]
Hey @kamilogorek - very cool. I've just had a look at the [release notes](https://github.com/getsentry/sentry-cli/pull/1277) and was just wondering if I still need to add `--header="Content-Encoding: gzip"` to my CLI command or if replacing that with `--decompress` is enough?

**Comment by kamilogorek** [comment]
No, you can skip all headers work entirely now, its being decompressed prior to sending.

**Comment by grug** [comment]
Excellent. Out of curiosity - will the webpack plugin also eventually support this?

**Comment by kamilogorek** [comment]
For sure, but only once they upgrade the cli to v2. Cannot tell the exact date, as updating it means dropping support for Node <12, but we're already discussing the move here.

**Comment by grug** [comment]
That's cool - I appreciate the info 😄
