### ISSUE TITLE
Is it possible not to inject release into chunk?

### ISSUE THREAD

**Issue by dimaqq** [getsentry/sentry-webpack-plugin#196]
Somewhat similar to #93 but simpler request:

I had beautiful reproducible builds, then I wanted to push map files up to sentry the easy way, and tried `@sentry/webpack-plugin`, and lo and behold, it injects `release` git has into the largest chunk that webpack outputs.

Here's the beautified diff:
```diff
@@ -1,4 +1,4 @@
-/*! For license information please see 2.0ccaa625.chunk.js.LICENSE.txt */
+/*! For license information please see 2.d819ca89.chunk.js.LICENSE.txt */
 (this.webpackJsonpXXX = this.webpackJsonpXXX || []).push([
     [2],
     [function(e, t, n) {
@@ -11453,7 +11453,7 @@
             ("undefined" !== typeof window ? window : "undefined" !==
                 typeof e ? e : "undefined" !== typeof self ? self : {})
             .SENTRY_RELEASE = {
-                id: "acb1212d2e588cf8c71f9608e5ca99f6c0add460"
+                id: "71a1cf60123d0c252552cf2ba146bf8ebed08dc0"
             }
         }).call(this, n(43))
     }, function(e, t, n) {
@@ -29769,4 +29769,4 @@
         }(r.a)
     }]
 ]);
-//# sourceMappingURL=2.0ccaa625.chunk.js.map
\ No newline at end of file
+//# sourceMappingURL=2.d819ca89.chunk.js.map
\ No newline at end of file
```

Is there a switch to not do that?

**Comment by dimaqq** [comment]
After some deliberation, trial and error I've decided to drop the plugin and `npx @sentry/cli` instead.

**Comment by kamilogorek** [comment]
This is one of the responsibilities of the plugin, as uploaded artifacts code (specifically `Sentry.init` call) has to use a matching release identifier, with the one used to create a release itself. Otherwise, files won't be used to resolve sourcemaps for all the events sent for this specific release.

**Comment by dimaqq** [comment]
ok then, feel free to close.

**Comment by aiphee** [comment]
@dimaqq 
Hi, would you be please willing to share how you cli upload code looks?

**Comment by dimaqq** [comment]
I do this after `yarn build` (and deployment):

```
npx @sentry/cli releases --org XX --project XX new "${CIRCLE_SHA1:0:7}"
npx @sentry/cli releases --org XX --project XX files "${CIRCLE_SHA1:0:7}" upload-sourcemaps --rewrite build
npx @sentry/cli releases --org XX --project XX finalize "${CIRCLE_SHA1:0:7}"
```

IIRC `--rewrite` actually modifies files in `build/`, so I do this at the very end.
