### ISSUE TITLE
`release` string starting with a `-` does not seem to be possible

### ISSUE THREAD

**Issue by bowswung** [getsentry/sentry-webpack-plugin#197]
We are using the `nextjs` buildId as our release tag when uploading source maps.

Sometimes this buildIdis generated with a `-` as the first character. The CLI plugin does not seem to support this. 

![image](https://user-images.githubusercontent.com/38782436/84790679-4acf3600-affa-11ea-82fa-04e87f98deda.png)

I have tried escaping the release string in various ways but due to the way `-` is handled on the command line it does not seem to be possible to escape in such a way that Sentry ends up with the correct release string (i.e. if the buildId is `-foo` I would expect the release in Sentry to be exactly the same: `-foo`.)

**Comment by Multiply** [comment]
Can confirm the same issue, also with next.js.
We've just prefixed the release with a short string for now, but would definitely love to see it fixed.

**Comment by kamilogorek** [comment]
The patch is already in place, but I need to write some tests for the rest of commands. Should be release next week. Thanks for your patience.

**Comment by kamilogorek** [comment]
New version should be available within 1-2 hours, so I'll close this issue. Cheers!
