### ISSUE TITLE
install error on:  linux arm64 4.18.0-80.7.2.el7.aarch64 

### ISSUE THREAD

**Issue by hao5743** [getsentry/sentry-webpack-plugin#198]
I'm using this plugin on my arm64 machine, and got this error in pictures. Can somebody help me ?  
$ cnpm install @sentry/cli@^1.52.3
![image](https://user-images.githubusercontent.com/11691827/85494277-eec46d00-b60a-11ea-9464-8e24734efdef.png)

**Comment by kamilogorek** [comment]
sentry-cli doesnt support ARM yet, see - https://github.com/getsentry/sentry-cli/issues/676
