### ISSUE TITLE
setCommits.repo should be optional

### ISSUE THREAD

**Issue by rchl** [getsentry/sentry-webpack-plugin#199]
I believe that `setCommits.repo` should be optional since with `auto: true` it's not required. Current types make it impossible to pass only `auto: true` as it will complain about missing `repo` property.

https://github.com/getsentry/sentry-webpack-plugin/blob/8f8fcb0a6deb3c43bb3b94b4ffca0638158b2097/index.d.ts#L120-L124

**Comment by kamilogorek** [comment]
You are correct. PR welcome :)
