### ISSUE TITLE
Disable sourcemaps

### ISSUE THREAD

**Issue by robianmcd** [getsentry/sentry-webpack-plugin#201]
I'm trying to integrate this into a Next.js app where we use live reload while running locally. I noticed that adding this plugin added about 10 seconds to the build that gets triggered every time a file is edited. It seems to be because source maps need to be regenerated and uploaded.

Is it possible to disable source maps while I am running this locally?

**Comment by kamilogorek** [comment]
You can either add the plugin conditionally (as webpack config is just a `js` file) or set `dryRun: true` for your dev env.

**Comment by robianmcd** [comment]
Alright thanks!
