### ISSUE TITLE
Does include and ignore support * (wildcards)?

### ISSUE THREAD

**Issue by birdwell** [getsentry/sentry-webpack-plugin#204]
I'm trying to use the following format
```
include: '~/dist/*.js.map',
 ignore: [ 'config/*']
```

I want to do this so I don't have to manually exclude each file.

**Comment by birdwell** [comment]
I'm having issues with the ignoreFile as I tried that out. Our release only filled up with source maps when I had include: '.', and the ignore filled out. Our ignore file looks like this.

apollo.config.js
config/
cypress/
generatePossibleTypes.js
jest.config.js
__mocks__/
src/lib/instana.js
__tests__/

**Comment by kamilogorek** [comment]
It does support it. What's your directory structure and what exactly do you want to achieve? Keep in mind that `include` points to directories that we'll scan for source maps, not files themselves.

**Comment by birdwell** [comment]
@kamilogorek I'm having issue with the following setup no source maps are being found now. In the dist folder it was spitting out source maps when it was just include and no ignoreFile
```
      new SentryCliPlugin({
        include: '.',
        ignoreFile: '.sentrycliignore',
        release: env.CI_COMMIT_SHA,
        deploy: {
          env: env.ENV
        }
      }),
```

``` sentrycliignore
~/config/webpack.common.js
~/config/webpack.dev.js
~/cypress/fixtures/graphQL.js
~/cypress/plugins/index.js
~/cypress/support/commands.js
~/cypress/support/index.js
~/cypress/temp/scroll_spec.js
~/generatePossibleTypes.js
~/jest.config.js
~/__mocks__/pubnub.js
~/__tests__/fake-js-file.js
~/__tests__/setupFile.js
~/__tests__/unit/hooks/userWindowSize.test.js
~/__tests__/unit/selectors/schedule.test.js
```

**Comment by kamilogorek** [comment]
I assume the second part is what's being uploaded to your sentry release? If so, what's your project directory structure?

**Comment by birdwell** [comment]
With the current files and seutp with the ignore nothing is coming through. We know the env variables are pulled in correctly because without the ignore we had 28 source maps. We just wanted to trim the list down. Thanks @kamilogorek 

.sentrycliignore
.sentryclirc
./config/webpack.config.js
./src

Our valid maps come through as:
~/dist/main.3208217dea4005fdc04c.js
~/dist/main.3208217dea4005fdc04c.js.map
~/dist/runtime.3208217dea4005fdc04c.js
~/dist/runtime.3208217dea4005fdc04c.js.map
~/dist/vendor.3208217dea4005fdc04c.js
~/dist/vendor.3208217dea4005fdc04c.js.map

**Comment by birdwell** [comment]
I went with a include: './dist' and remove the ignoreFile. I now have the outcome I want. However, I was never able to get ignoreFile to work correctly.
