### ISSUE TITLE
Sentry CLI fails with "Enter a valid email address"

### ISSUE THREAD

**Issue by carestad** [getsentry/sentry-webpack-plugin#212]
After upgrading to a newer version of this plugin, our builds are now failing with the following errors:

```
ERROR in Sentry CLI Plugin: Command failed: /var/www/***/build/node_modules/@sentry/cli/sentry-cli releases set-commits
 xxx-version-xxx --auto
error: API request failed
  caused by: sentry reported an error: request failure (http status: 400)
  Object({"commits": Object({"author_email": Array([String("Enter a valid email address.")])})})

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
```

Running with `--log-level=debug` I see a full dump of the JSON with the latest commits in the branch, and since we use dependabot (not entirely uncommon I suppose), I see that its `author_email` is set to `<ID>+dependabot-preview[bot]@users.noreply.github.com`. It is the only `author_email` I see that includes special characters of some sorts. The rest of them contain plain `[a-z0-9]` characters in the username part of the email address.

Is there any way of working around this? According to [Wikipedia](https://en.wikipedia.org/wiki/Email_address#Local-part), the local-part _can_ contain `[]` though (although it needs to be in a quoted string, which it appears it isn't in this case?).

Edit: workaround for now for us is just disabling (commenting out) the `setCommits` object.

**Comment by kamilogorek** [comment]
Thanks for the report. I'll close this issue in favor of https://github.com/getsentry/sentry-cli/issues/803 as it's coming from the upstream. Cheers!
