### ISSUE TITLE
Dont reupload sourcemaps if they exist already

### ISSUE THREAD

**Issue by Herz3h** [getsentry/sentry-webpack-plugin#214]
Is there a way to tell the plugin to not reupload sourcemaps if they already exist for current release ?

**Comment by kamilogorek** [comment]
No, release updates always override artifacts with the same name by design.

**Comment by Herz3h** [comment]
In my case, the webpack build will run for same release on multiple dockers, so it is unnecessary to upload sourcemaps every time. It also slows down webpack build (150mb of sourcemaps uploaded atm every build)

**Comment by kamilogorek** [comment]
Can you select which docker images will upload them? If so, you can do `dryRun: process.env.UPLOAD_SOURCEMAPS` (or any other key) or include plugin conditionally in the webpack config.
