### ISSUE TITLE
Paths for index.js files are incorrect and `stripPrefix` doesn't work

### ISSUE THREAD

**Issue by wrgoto** [getsentry/sentry-webpack-plugin#215]
I have an electron `dist` directory with the following structure:

- `dist`
    - `main`
        - `index.js`
    - `renderer`
        - `index.js`

My artifacts are uploaded as:

`app:///main/main.js`
`app:///renderer/renderer.js`

However, the errors on my Sentry dashboard are reporting URLs that look like:

`app:///main.js`
`app:///renderer.js`

In my Webpack config I have:

```js
new SentryWebpackPlugin({
  include: 'dist',
  ignore: ['node_modules'],
  urlPrefix: `app:///`,
  release: SOURCE_VERSION,
})
```

I tried including the `stripPrefix` key, but it's not working, and there isn't much documentation on the option:

```js
stripPrefix: ['/main', '/renderer']
```

I think the artifacts _should_ be uploaded as:

`app:///main.js`
`app:///renderer.js`

**Comment by kamilogorek** [comment]
Are you sure the data you provided is correct? I'm not sure how `dist/main/index.js` and` dist/rendere/index.js` could end up as `main.js` and `renderer.js` 🤔

Two things until then:
- you can remove `urlPrefix`. `~/` which is a default, will work just fine in this scenario
- if your files are not served directly from `dist`, then your `include` should be more specific, eg, `['dist/main`, 'dist/renderer']`, which should take care of correcting the paths (but they'll end up both being `index.js` anyway, so let me wait for more details first

**Comment by wrgoto** [comment]
Thanks @kamilogorek, after working on this a bit more, `sentry-webpack-plugin` is working as intended. I believe the issue is with `electron-webpack` and `electron-builder` with their default configurations.

I did confirm that `electron-webpack` in this configuration will rename `/main/index.js` in your source to `/main/main.js` in your dist.

When you do production builds with `electron-builder`, you'll create HTML files for your entry points and inside these files they reference your bundles via `/renderer.js` and not the build dist directory structure i.e. `dist/renderer/renderer.js`.

This means that Sentry will report the stack track as `app:///main.js`.

For anyone who is running into a similar issue, one hack to temporarily solve the issue is:

```jsx
const beforeSend = event => {
  if (
    !event.exception ||
    !event.exception.values ||
    !event.exception.values[0]
  ) {
    return event;
  }

  const { stacktrace } = event.exception.values[0];

  if (stacktrace && stacktrace.frames) {
    stacktrace.frames.forEach(frame => {
      if (frame.filename === 'app:///main.js') {
        frame.filename = 'app:///main/main.js';
      }

      if (frame.filename === 'app:///renderer.js') {
        frame.filename = 'app:///renderer/renderer.js';
      }
    });
  }

  return event;
};

Sentry.init({
  dsn: SENTRY_DSN,
  beforeSend
});
```

**Comment by kamilogorek** [comment]
Thanks for the writeup!
