### ISSUE TITLE
Invalid release version

### ISSUE THREAD

**Issue by AmauryLiet** [getsentry/sentry-webpack-plugin#22]
Hi and thanks for the lib!

I'm getting an error when the plugin tries to create a release:
```
ERROR in Sentry CLI Plugin: Command failed: [my project path]/node_modules/@sentry/cli/sentry-cli releases new c38d[...]f04

error: Invalid value for '<VERSION>': Invalid release version. Releases must not contain leading or trailing spaces.
```

although running this command by hand works:
```
> [my project path]/node_modules/@sentry/cli/sentry-cli releases new c38d[...]f04
Created release c38d[...]f04
```

Could it be an error in the plugin or a wrong configuration on my side?

My config:
```
    new SentryCliPlugin({
      include: './public',
      ignore: ['node_modules', 'webpack.common.js'],
    }),
```

**Comment by HazAT** [comment]
Hey, just to make sure, which version of `sentry-webpack-plugin` are you running, latest `1.2.0`?

**Comment by AmauryLiet** [comment]
Exactly, I just installed the last version `1.2.0` today

**Comment by AmauryLiet** [comment]
After having a look, it seems that sentry returns the proposed-version with a trailing '\n'. Looks like you fixed it here https://github.com/AmauryLiet/sentry-webpack-plugin/commit/81b6af7c6bc989412724f8cbcd5135fd0d91a4b6#diff-1fdf421c05c1140f6d71444ea2b27638R104
Waiting for the next release ;)

**Comment by HazAT** [comment]
@AmauryLiet 
Oh
 I thought we released it already  🤦‍♂️  
`1.3.0` is now available, sorry for the inconvenience.
