### ISSUE TITLE
Can't get the sourcemap to show original files

### ISSUE THREAD

**Issue by finppp** [getsentry/sentry-webpack-plugin#229]
Hey all,

I've tried to set this up both On-premise and on Sentry.io with the same results. To keep things easier, I'll use the Sentry.io version.

I have successfully uploaded project to Sentry which includes the `src` folder with the original .js files and the `dist` folder which includes the bundle.js and the bundle.js.map, which is generated with devTool: 'source-map'. See below
![image](https://user-images.githubusercontent.com/15324432/95225463-be888f00-07f3-11eb-9aae-689629def822.png)
![image](https://user-images.githubusercontent.com/15324432/95225522-cc3e1480-07f3-11eb-8c2b-7ffe7572a092.png)

I have tested the sitemap using [source-map-explorer](https://www.npmjs.com/package/source-map-explorer), which discovers all the seperate js files.

My plugin config:

**Comment by kamilogorek** [comment]
Dup of https://github.com/getsentry/sentry-webpack-plugin/issues/230

**Comment by finppp** [comment]
Thanks for the help - worked great!
