### ISSUE TITLE
Sentry not reading sourcemap correctly

### ISSUE THREAD

**Issue by finppp** [getsentry/sentry-webpack-plugin#230]
Hey all,

I've tried to set this up both On-premise and on Sentry.io with the same results. To keep things easier, I'll use the Sentry.io version.

I have successfully uploaded project to Sentry which includes the `src` folder with the original .js files and the `dist` folder which includes the bundle.js and the bundle.js.map, which is generated with devTool: 'source-map'. See below

![image](https://user-images.githubusercontent.com/15324432/95225463-be888f00-07f3-11eb-9aae-689629def822.png)

![image](https://user-images.githubusercontent.com/15324432/95225522-cc3e1480-07f3-11eb-8c2b-7ffe7572a092.png)

I have tested the sitemap using [source-map-explorer](https://www.npmjs.com/package/source-map-explorer), which discovers all the seperate js files.

My plugin config:       
```
sourceMaps('source-map'),
uglify({ sourceMap: true }),
new SentryWebpackPlugin({
        debug: true,
        release: '1.1',
        authToken: 'myauthtoken',
        org: 'myorg',
        project: 'myproject',
        include: '.',
        ignore: ['node_modules', 'webpack.config.js'],
      }),
```

Still no links to files/lines. Only the old bundle.js:

![image](https://user-images.githubusercontent.com/15324432/95229395-715aec00-07f8-11eb-8b7e-9d6d00e68128.png)

Let me know if any other information is needed
Thanks

**Comment by finppp** [comment]
Another question: Is it possible to upload a sourcemap with lines only (no code). Then either upload my assets, e.g. Src folder as an artifact, to reveal the original source code, or link github to reveal the orignal souce code?

**Comment by kamilogorek** [comment]
>  Is it possible to upload a sourcemap with lines only (no code). Then either upload my assets, e.g. Src folder as an artifact, to reveal the original source code

It _should_ work fine as long as `.js` file has a correct map reference at the bottom.

> or link github to reveal the orignal souce code?

That's unfortunatelly not possible.

As for the original issue, your frames have to match artifacts path. So `/assets/bundle...js` has to be uploaded as `~/assets/bundle...js`, without `dist` prefix. You can achieve this using `stripPrefix` or by including more granular paths, `include: ['dist']`, as it'll change the upload root for that directory.
