### ISSUE TITLE
i have sentry-cli installed on global, but sentry-webpack-plugin always re-downloads a cli everytime

### ISSUE THREAD

**Issue by qianL93** [getsentry/sentry-webpack-plugin#24]
hi!
how can i make sentry-webpack-plugin use a global sentry-cli not re-download sentry-cli everytime i install sentry-webpack-plugin? because downloading sentry-cli-binary does take too much time

**Comment by HazAT** [comment]
Hey, sorry there is currently no workaround for this.
This is the way how NPM works, we already tried a few things in the past and none of them worked.

**Comment by kamilogorek** [comment]
@qianL93 you "should" be able to use globally installed `sentry-cli` package within your local project. We don't have an official docs for this, as it's not default behaviour of `npm` or `yarn`, but you can give it a go.

```sh
$ npm install --save @sentry/cli
# or
$ yarn add @sentry/cli
```

and then follow this official guide how to require a package from global directory https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders
