### ISSUE TITLE
build sourceMap sentry reported an error: bad request (http status: 400)

### ISSUE THREAD

**Issue by EvansAlien** [getsentry/sentry-webpack-plugin#242]
error: API request failed
  caused by: sentry reported an error: bad request (http status: 400)
⠼  Building for test1...
Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

**Comment by kamilogorek** [comment]
If you could attach that debug log that would be great :)

**Comment by EvansAlien** [comment]
caused by internal deployment of http and https
