### ISSUE TITLE
tests included in the package

### ISSUE THREAD

**Issue by janczizikow** [getsentry/sentry-webpack-plugin#247]
`__tests__` folder is included in the package on npm. jest picks this up, unless the jest.config specifies to ignore `node_modules` directory. Would be happy to open a PR for this if it's something that maintainers want 🙂 

<img width="475" alt="Screenshot 2020-12-15 at 16 12 15" src="https://user-images.githubusercontent.com/13835666/102235499-acf9ec80-3ef2-11eb-930c-46e362f612a3.png">

**Comment by kamilogorek** [comment]
Good catch, fixed it, thanks! :)
