### ISSUE TITLE
plugin reports upload successful, but Sentry shows zero artifacts

### ISSUE THREAD

**Issue by vitalybaev** [getsentry/sentry-webpack-plugin#248]
# Environment
* Self-hosted Sentry: **20.10.1** `78833d9`
* @sentry/webpack-plugin - `1.13.0`

I try to use Sentry Webpack Plugin to upload artifacts for our Next.js application:

```js

// next.config.js

// The following variables exists with correct values
// process.env.SENTRY_AUTH_TOKEN = ***;
// process.env.SENTRY_URL = ***;

webpackConfig.plugins.push(
  new SentryWebpackPlugin({
    include: '.next',
    ignore: ['node_modules'],
    urlPrefix: `~/_next`,
    release: version.Commit, // This is commit number
    org: 'myorg',
    project: 'my-shop',
    debug: true,
    setCommits: {
      auto: true,
    },
  }),
);
```

## Full log
https://gist.github.com/vitalybaev/84da34fb747fe55d01c3cd5ee17a0c1d

But as you can see:
1. `Sentry Release: 2ba4eaf205f3bd0611b201fd253389a2b8145586` on build stage
2. Sentry Webpack Plugin reports about hundreds files to upload and successfully uploads it
3. In Sentry the release appears, but  no source maps showed:

![CleanShot 2020-12-28 at 22 01 51@2x](https://user-images.githubusercontent.com/724423/103237358-637cb900-4958-11eb-8218-72f1a64eecd3.png)

Thanks! 🙏

**Comment by kamilogorek** [comment]
It's most likely on-premise configuration issue. Please see https://forum.sentry.io/t/upload-the-sourcemap-the-sentry-console-has-a-release-record-but-the-number-of-artifacts-is-0/12380/4 and post on our forum if it won't resolve it.
Cheers!
