### ISSUE TITLE
Strip prefix from uploaded source paths

### ISSUE THREAD

**Issue by Methuselah96** [getsentry/sentry-webpack-plugin#253]
In the web app that I'm working on, we have Webpack outputting the build in `./public/` (e.g., `./public/app.js` and `./public/app.js.map`). When the app is actually deployed it is served from `~/` (e.g., `~/app.js`).

At first I assumed that the `stripPrefix` option would resolve this issue by stripping the prefix from the uploaded source paths, but instead it only modifies the paths within the sourcemaps. Upon further investigation, this behavior is documented in [the `@sentry/cli` documentation](https://docs.sentry.io/product/cli/releases/#sentry-cli-sourcemaps) under the `--strip-prefix` argument where it says:

> This will not modify the uploaded sources paths. To do that, point the upload or upload-sourcemaps command to a more precise directory instead.

How do I get the Webpack plugin to run the upload-sourcemaps command from a more precise directory so that the prefix can be stripped from the uploaded source paths? Or is there another way to resolve this issue using the Webpack plugin?

**Comment by kamilogorek** [comment]
Making your includes more specific should do just that `include: './public/'`

**Comment by Methuselah96** [comment]
Thanks, that does it! I figured that the `include` option would just narrow which files were uploaded, but not change which directory they were uploaded from (i.e., not change the path).
