### ISSUE TITLE
Support DSN in Webpack config

### ISSUE THREAD

**Issue by bholtbholt** [getsentry/sentry-webpack-plugin#257]
We're running a Rails app using Sprockets and switching over to Webpack. Source Maps aren't working so I'm [following the instructions](https://docs.sentry.io/platforms/javascript/sourcemaps/?_ga=2.109644933.1025190271.1612469578-1047508239.1610406217) to configure this plugin.

I need to:
- create an AuthToken
- fill in the org name
- fill in the project name

We already have these setup in an environment variable, `SENTRY_DSN`, and now I need to add/reconfigure more.

It would be nice if the plugin supported `SENTRY_DSN` so I could use that.

**Comment by krutoo** [comment]
@kamilogorek it would be very convenient to use one - SDS instead of several options, since SDS is usually responsible for other interactions with Sentry in the project

can we add some utility that converts ds to config for webpack plugin? or just add dsn option

**Comment by kamilogorek** [comment]
I'm still not sure what you'd like to use that DSN for?

**Comment by kamilogorek** [comment]
DSN is a unique identifier that can be used to deliver the public payload to a given project/org. However, it's not possible to use it to perform any token-authenticate requests, and one such request is uploading release artifacts or creating the release itself.
We need organization and project slugs to be set explicitly for this, as we don't have API that'd allow any other authentication - https://docs.sentry.io/api/releases/upload-a-new-organization-release-file/

**Comment by krutoo** [comment]
@kamilogorek But in CLI there is an option auth.dsn (env var SENTRY_DSN) 

Can you suggest what it is for?

**Comment by kamilogorek** [comment]
For sending locally stored events and envelopes using `send-event` and `send-envelope` commands respectively :)

**Comment by krutoo** [comment]
@kamilogorek  is there any plan to add DSN to send artifacts in the future?

**Comment by krutoo** [comment]
@kamilogorek For example postgres DSN supports authorization

anyway this is what I needed to find out, thanks
