### ISSUE TITLE
Webpack 5 types issue

### ISSUE THREAD

**Issue by knownun** [getsentry/sentry-webpack-plugin#258]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
"@sentry/react": "^6.1.0",
"@sentry/tracing": "^6.1.0",
"@sentry/webpack-plugin": "^1.14.0",

### Steps to Reproduce

1. Project using webpack5 and TypeScript files for webpack configs
2. Use SentryWebpackPlugin
3. Try to run webpack config with `tsc`
4. Get an error

### Expected Result

It will work

### Actual Result

```
node_modules/@sentry/webpack-plugin/index.d.ts:1:10 - error TS2305: Module '"../../webpack/types"' has no exported member 'Plugin'.

1 import { Plugin, Compiler } from 'webpack';
           ~~~~~~
```

**Comment by kamilogorek** [comment]
Fixed in https://github.com/getsentry/sentry-webpack-plugin/pull/259
