### ISSUE TITLE
Apple M1 chip

### ISSUE THREAD

**Issue by gintsmurans** [getsentry/sentry-webpack-plugin#262]
Hi!

"@sentry/webpack-plugin": "^1.14.1", depends on "@sentry/cli": "^1.58.0" which does not yet have M1 chipset support. Are there plans to update dependecy to 1.63.1 via [this](https://github.com/getsentry/sentry-cli/issues/676#issuecomment-788945357)?

**Comment by kamilogorek** [comment]
Published as `1.14.2`. Cheers!

**Comment by gintsmurans** [comment]
Nice, thanks.
