### ISSUE TITLE
Source code was not found

### ISSUE THREAD

**Issue by stoefln** [getsentry/sentry-webpack-plugin#268]
### How are you running Sentry?
Saas (sentry.io)

### Versions:
"@sentry/electron": "^0.17.4",
"@sentry/webpack-plugin": "^1.12.0",

## Description

I used the sentry webpack plugin to upload sources. Since I used a different release key for upload, it seems that sentry had issues with linking the stacktraces with my source maps. Now I deleted all the source maps and uploaded again, using the original release param. However: The web interface still shows "Source code was not found", even though the release name matches exactly the source maps release name ("Repeato0.9.3").

## Steps to Reproduce

1. Delete source maps
2. Reupload sources with sentry webpack plugin
3. Check reported issue
4. "Souce code was not found" error

### What you expected to happen

Sentry should find the source maps

### sentry JS sdk config:

```
const { app } = require('electron')
const dsn = 'https://7099.....'
const release = 'Repeato-' + app.getVersion()
const sentryConf = {dsn, release}

if (process.env.NODE_ENV != 'development') {
  Sentry.init(sentryConf)
}
```

### webpack.production.config.js:

https://gist.github.com/stoefln/f2e86f0e64cb1c74eb18dbae75196f0c

### Example issue:

https://sentry.io/organizations/stephan-petzl/issues/2303567159/?environment=production&project=1554144&query=firstRelease%3ARepeato0.9.3&sort=user&statsPeriod=14d

### Source maps:

https://sentry.io/settings/stephan-petzl/projects/repeato/source-maps/Repeato0.9.3/

**Comment by kamilogorek** [comment]
We do not reprocess events unless you opt-in into that feature.

![image](https://user-images.githubusercontent.com/1523305/113739289-ef447500-96ff-11eb-8a4d-03005cedfd45.png)

Once turned on, you will be able to trigger event reprocessing from the UI once you upload new source maps.

https://docs.sentry.io/product/issues/reprocessing/

**Comment by stoefln** [comment]
@kamilogorek I opted in for "Early adopter" and turned on "Reprocessing". Still the issues don't show a reprocess button. Whats wrong?

**Comment by stoefln** [comment]
I also reuploaded the source maps btw..

**Comment by untitaker** [comment]
Sorry @stoefln reprocessing is only available for native/C/C++ events. You'll have to wait for new events in the case of JS and most other platforms.
