### ISSUE TITLE
Introduced breaking change in minor version update (webpack 4 unsupported)

### ISSUE THREAD

**Issue by untoldone** [getsentry/sentry-webpack-plugin#271]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
When moving to 1.14.1 from 1.14.0

### Steps to Reproduce

Update package in project from 1.14.0 to 1.14.1 or higher with webpack version ^4.0.0 of a project which uses typescript.

### Expected Result

Minor version change continued to work with webpack 4.

### Actual Result

Does not. At build time, we saw:

```
Mon 10:47:57.791 <REDACTED>> ERROR in <REDACTED>/node_modules/@sentry/webpack-plugin/index.d.ts(1,20):
Mon 10:47:57.791 <REDACTED>> 1:20 Module '"../../@types/webpack"' has no exported member 'WebpackPluginInstance'.
Mon 10:47:57.791 <REDACTED>>   > 1 | import { Compiler, WebpackPluginInstance } from 'webpack';
Mon 10:47:57.791 <REDACTED>>       |                    ^
Mon 10:47:57.791 <REDACTED>>     2 |
Mon 10:47:57.791 <REDACTED>>     3 | export interface SentryCliPluginOptions {
Mon 10:47:57.791 <REDACTED>>     4 |   // general configuration for sentry-cli
Mon 10:47:57.791 <REDACTED>> Version: typescript 3.9.9
```

Note that a prior similar PR noted explicitly that this was a breaking change https://github.com/getsentry/sentry-webpack-plugin/pull/233 -- https://github.com/getsentry/sentry-webpack-plugin/pull/259 notes this same change should work in version 4. We're specifically locked to webpack 4.42.1 and saw the above issue.

Assuming this does indicate a breaking change in a minor version update, best case, support for webpack 4 is re-added in a future version and this breaking change is documented in the changelog... if it is deemed not possible to support both, at a minimum, I'd think the changelog should pretty explicitly note the breaking change in the minor version update.

**Comment by kamilogorek** [comment]
Webpack v4 has a `WebpackPluginInstance` type available - https://github.com/webpack/webpack/blob/webpack-4/declarations/WebpackOptions.d.ts and it was introduced in `4.20.` - https://github.com/webpack/webpack/commit/3a896c96b64abb993b83f15dec460faf8d9bf2b3#diff-4071bbceb2f239cf48da48d19fd9b724509294980b4142a5a75e9a6478009498R672

Please verify the type definitions your project is using. Cheers!

**Comment by untoldone** [comment]
For anyone else who comes across this issue. It turns out we were using `html-webpack-plugin@4.0.4` which depended on `@types/webpack` version `^4.41.8` even though I believe the type specifications were present that version of `webpack`.

Our project had locked to version `4.41.10` of `@types/webpack` which appears to have outdated types which excluded `WebpackPluginInstance`...  Letting the lock update to version `4.41.27` fixed this issue.
