### ISSUE TITLE
error with thread-loader

### ISSUE THREAD

**Issue by lishichao1002** [getsentry/sentry-webpack-plugin#272]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

Which SDK and version?

macos node12

### Steps to Reproduce

```
{
        test: /\.js$/,
        include: path.resolve("src"),
        use: [
          "thread-loader",
          "expensive-loader"
        ]
}
```

### Expected Result

webpack build success

### Actual Result

```
node_modules/@sentry/webpack-plugin/src/sentry-webpack.module.js
Thread Loader (Worker 1)
releasePromise.then is not a function
```

https://github.com/getsentry/sentry-webpack-plugin/issues/176

![image](https://user-images.githubusercontent.com/13584162/114516857-603fdb80-9c70-11eb-8785-12c2cedcbd82.png)

**Comment by kamilogorek** [comment]
> Unfortunately without providing a concrete repro-case which i can run locally it's very hard to tell what went wrong. It'd be great if you could provide something of that sort.

**Comment by lishichao1002** [comment]
I'm will give you a demo laster

**Comment by lishichao1002** [comment]
@kamilogorek 

## the git repo
https://github.com/lishichao1002/sentry-webpack-plugin

## the error log
https://github.com/lishichao1002/sentry-webpack-plugin/blob/master/example/yarn_build.log

## the webpack config
https://github.com/lishichao1002/sentry-webpack-plugin/blob/master/example/webpack.config.js#L17

**Comment by Saran010** [comment]
Same issue. I cant build my project. I created project via vue/cli. When I try build project with SentryWebpackPlugin it crash.
I dont know why `query.releasePromise` is empty object in `sentry.loader.js`. But method `getReleasePromise` return Promise.

`query.project` and `query.org` return string

**Comment by fengyuanchen** [comment]
@Saran010 Just found a solution, set the [`parallel`](https://cli.vuejs.org/config/#parallel) option to `false` to disable the `thread-loader`:

```js
// vue.config.js
module.exports = {
  // Not to use `thread-loader`.
  parallel: false,
  // ...
};
```

**Comment by Saran010** [comment]
> @Saran010 Just found a solution, set the [`parallel`](https://cli.vuejs.org/config/#parallel) option to `false` to disable the `thread-loader`:
> 
> ```js
> // vue.config.js
> module.exports = {
>   // Not to use `thread-loader`.
>   parallel: false,
>   // ...
> };
> ```

Thanks a lot! It works for me! :)

**Comment by hognevevle** [comment]
> @Saran010 Just found a solution, set the [`parallel`](https://cli.vuejs.org/config/#parallel) option to `false` to disable the `thread-loader`:
> 
> ```js
> // vue.config.js
> module.exports = {
>   // Not to use `thread-loader`.
>   parallel: false,
>   // ...
> };
> ```

Doesn't work for me :(

```
ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
         - configuration has an unknown property 'parallel'. These properties are valid:
           object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, experiments?, externals?, externalsPresets?, externalsType?, ignoreWarnings?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, snapshot?, stats?, target?, watch?, watchOptions? }
```
