### ISSUE TITLE
Sentry CLI Plugin: this.cli.releases.execute is not a function

### ISSUE THREAD

**Issue by aliveghost04** [getsentry/sentry-webpack-plugin#275]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
JavaScript 6.3.3

### Steps to Reproduce

1. npm i -P @sentry/browser @sentry/tracing
2. npm run serve

### Expected Result

```
[DONE] Compiled successfully in 16944ms

  App running at:
  - Local:   http://localhost:8000/
```

### Actual Result

```
[ERROR]  Failed to compile with 1 error
[error]

Sentry CLI Plugin: this.cli.releases.execute is not a function
```

### Webpack configuration

under the `configureWebpack` key is the current configuration.

```js
plugins: [
      new SentryWebpackPlugin({
        // sentry-cli configuration
        authToken: process.env.VUE_APP_SENTRY_AUTH_TOKEN, // auth_token
        org: process.env.VUE_APP_SENTRY_ORG, // company-name
        project: process.env.VUE_APP_SENTRY_PROJECT, // project-name
        release: process.env.VUE_APP_SENTRY_RELEASE, // company-name-project-name@4.3.1
        dryRun: process.env.NODE_ENV !== 'production',
        cleanArtifacts: true,
        setCommits: {
          auto: true,
        },

        // webpack specific configuration
        include: "./dist",
        ignore: [
          "node_modules",
          "webpack.config.js",
        ],
      }),
],
```

**Comment by aliveghost04** [comment]
The issue disappears when removing the `cleanArtifacts` key from options but I would like to understand why this happens.

Initially, I thought was a permission-related issue but I created a token with all the permissions and was facing the same error.

**Comment by kamilogorek** [comment]
To be honest I have no clue, so I wont be able to tell you without the repr-case.

**Comment by Fxlr8** [comment]
Found the same problem. Looks like this happens when you use `cleanArtifacts` and `dryRun` at the same time.

You can use this as a temporary fix
```
cleanArtifacts: process.env.NODE_ENV === 'production'
```

**Comment by sin-ack** [comment]
This issue should be reopened, it persists with @sentry/cli 1.71.0 and @sentry/webpack-plugin 1.18.3. I have the same situation with @Fxlr8. `@sentry/nextjs` provides a `withSentryConfig` function which automatically enables dry run mode when the development server is run. When `dryRun` is enabled, I get the same error. Disabling `cleanArtifacts` fixes the issue.

**Comment by sarunast** [comment]
Can confirm it on `1.19.0`.
