### ISSUE TITLE
Uploads happening on `npm run serve`/`vue-cli-service serve`

### ISSUE THREAD

**Issue by iyerusad** [getsentry/sentry-webpack-plugin#280]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
`package.json`
```
    "@sentry/browser": "^6.4.1",
    "@sentry/integrations": "^6.4.1",
    "@sentry/webpack-plugin": "^1.15.1",
    "create-file-webpack": "^1.0.2",
    "@vue/cli": "^4.4.5",
    "@vue/cli-plugin-babel": "^4.4.1",
    "@vue/cli-plugin-eslint": "^4.4.1",
    "@vue/cli-plugin-pwa": "^4.5.12",
    "@vue/cli-service": "^4.4.1",
```

### Steps to Reproduce

1. Ran `npm run serve` (which is aliased to `vue-cli-service serve`)

### Expected Result

No uploads to sentry during development.

### Actual Result

Sentry uploaded during dev server start up:
![image](https://user-images.githubusercontent.com/25647368/120394450-ab7d7e80-c2f0-11eb-8e66-334333593855.png)

### Other info

`vue.config.js`
```
module.exports = {
  css: {
    sourceMap: true
  },
  configureWebpack: {
    devtool: "source-map",
    plugins: [
      new VuetifyLoaderPlugin(),
      new CreateFileWebpack({
        // path to folder in which the file will be created
        path: "./dist",
        // file name
        fileName: "build.json",
        // content of the file
        content: JSON.stringify(buildJSON)
      }),
      new SentryWebpackPlugin({
        // sentry-cli configuration
        authToken: process.env.SENTRY_AUTH_TOKEN,
        org: "myorg",
        project: "snipped",
        release: process.env.SENTRY_RELEASE_VERSION,

        // webpack specific configuration
        include: "./dist",
        ignore: ["node_modules", "webpack.config.js"]
      })
    ]
  },
//snipped remainder
```

**Comment by kamilogorek** [comment]
You added the plugin to webpack config, so why would you expect it to not run? 🤔 
If you want want to run it in dev, add it conditionally based on `process.env.NODE_ENV` or something else that Vue is using.

**Comment by iyerusad** [comment]
Ah that would make sense - I didn't understand it worked that way.

I moved the plugin injection to the end of the vue-config.js and now it functions as expected (not running during `npm run serve`, and running during `npm run build`):
```js
//rest of vue.config.js above ^^

if (process.env.NODE_ENV === "production") {
  //SentryWebpackPlugin - Uploads src maps to sentry, per release
  module.exports.configureWebpack.plugins.push(
      new SentryWebpackPlugin({
        // sentry-cli configuration
        authToken: process.env.SENTRY_AUTH_TOKEN,
        org: "myorg",
        project: "snipped",
        release: process.env.SENTRY_RELEASE_VERSION,

        // webpack specific configuration
        include: "./dist",
        ignore: ["node_modules", "webpack.config.js"]
      })
  );
}

```

**Comment by hyperknot** [comment]
This should be mentioned in the docs, as all the guides on the website hard-code SentryWebpackPlugin into the static part of the Webpack configuration.
