### ISSUE TITLE
Support for --ignore-missing

### ISSUE THREAD

**Issue by dscdac** [getsentry/sentry-webpack-plugin#281]
Hey,

In the last Sentry-cli version they [this --ignore-missing option](https://docs.sentry.io/product/cli/releases/#dealing-with-missing-commits) so it doesn't break when Sentry cannot figure the current or last commit. I faced this kind of issues when deploying from Github Actions for some reason (even when checking out with fetch-depth: 0).
Would be cool to add it as an option in the Webpack config.

Cheers!

**Comment by dscdac** [comment]
I've created a 'placeholder' for how the code would look like:
https://github.com/getsentry/sentry-webpack-plugin/compare/master...dscdac:ignore-missing
Unfortunately, the new `--ignore-missing` option is not included on their types:
https://github.com/getsentry/sentry-cli/blob/c8fccb57f0aca1298ff7566997958fee78bc1862/js/index.d.ts#L39

**Comment by kamilogorek** [comment]
Fixed
