### ISSUE TITLE
Plugin not uploading all source maps to Sentry

### ISSUE THREAD

**Issue by ffxsam** [getsentry/sentry-webpack-plugin#284]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
```
    "@sentry/integrations": "^6.5.1",
    "@sentry/serverless": "^6.5.1",
    "@sentry/webpack-plugin": "^1.15.1"
```

### Steps to Reproduce

1. `sls deploy`

### Expected Result

I have 37 Lambda functions. I'd expect all of their source maps to be uploaded.

### Actual Result

Only 2 were uploaded:

```
Source Map Upload Report
  Minified Scripts
    ~/adminGetUsers/src/functions/admin-get-users/handler.js (sourcemap at handler.js.map)
    ~/createEmbed/src/functions/create-embed/handler.js (sourcemap at handler.js.map)
  Source Maps
    ~/adminGetUsers/src/functions/admin-get-users/handler.js.map
    ~/createEmbed/src/functions/create-embed/handler.js.map
```

## webpack.config.js
```js
const path = require('path');
const slsw = require('serverless-webpack');
const nodeExternals = require('webpack-node-externals');
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');
const SentryCliPlugin = require('@sentry/webpack-plugin');

module.exports = {
  context: __dirname,
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  entry: slsw.lib.entries,
  devtool: slsw.lib.webpack.isLocal
    ? 'eval-cheap-module-source-map'
    : 'source-map',
  resolve: {
    extensions: ['.mjs', '.json', '.ts'],
    symlinks: false,
    cacheWithContext: false,
    plugins: [
      new TsconfigPathsPlugin({
        configFile: './tsconfig.paths.json',
      }),
    ],
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
    devtoolModuleFilenameTemplate: 'app:///[resource-path]',
  },
  optimization: {
    concatenateModules: false,
  },
  target: 'node',
  externals: [nodeExternals()],
  module: {
    rules: [
      {
        test: /\.(tsx?)$/,
        loader: 'ts-loader',
        exclude: [
          [
            path.resolve(__dirname, 'node_modules'),
            path.resolve(__dirname, '.serverless'),
            path.resolve(__dirname, '.webpack'),
          ],
        ],
        options: {
          transpileOnly: true,
          experimentalWatchApi: true,
        },
      },
    ],
  },
  plugins: [
    ...(slsw.lib.webpack.isLocal
      ? []
      : [
          new SentryCliPlugin({
            org: 'reelcrafter',
            project: 'v2-api',
            // release is automatic, no need to include here
            include: './.webpack',
            runOnce: true,
          }),
        ]),
  ],
};
```

**Comment by kamilogorek** [comment]
Can you use `debug:true` in the plugin config? I wonder if it's the plugin itself that's not picking up those files (there is a chance they are not there yet when it's traversing for them I assume) or the sentry-cli itself. Were you able to  maybe create some small repro of this issue? I've never experienced it before and not sure how to reproduce it.

**Comment by ffxsam** [comment]
@kamilogorek I'll try to circle back to this when I have some time. I actually wound up getting rid of `serverless-webpack` and replacing it with `serverless-esbuild`. My deploys are now 12x faster! I'm also working on an esbuild plugin to automatically upload Sentry source maps, which I'm happy to share once it's done and fully tested.

**Comment by kamilogorek** [comment]
Last time I checked `esbuild` in 2020 I was blown away. Unfortunately it didn't cover all our needs back then, but we'll definitely try it again soon!

**Comment by rememberlenny** [comment]
@ffxsam Can you share the code for your esbuild integration? We are using ViteJS for our builder and are hoping to implement source map integration as well.

**Comment by ffxsam** [comment]
@rememberlenny I haven't gotten an esbuild plugin working yet. I can't figure out a way for esbuild to just run a plugin _once_ at the end of a build (it seems to run for every file).

So I'm using this deploy script right now:

```sh
#!/bin/sh
set -ex

export SENTRY_RELEASE=$(git rev-parse --short HEAD)
sls deploy $*
yarn sentry-cli releases --org YOUR_ORG --project YOUR_PROJECT files $SENTRY_RELEASE upload-sourcemaps .sentry/sourcemaps
rm -rf .sentry
```
