### ISSUE TITLE
React Typescript source maps doesn't work

### ISSUE THREAD

**Issue by RoyChen4212** [getsentry/sentry-webpack-plugin#293]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
Sentry Saas (sentry.io)

Which SDK and version?

"react": "16.14.0",
"typescript": "3.9.7",

### Steps to Reproduce

1. Create a repository with react extension starter(https://github.com/abhijithvijayan/web-extension-starter)
2. Integrate sentry as well as sentry webpack plugin.
In package.json
```
    "@sentry/browser": "6.9.0",
    "@sentry/react": "6.9.0",
    "@sentry/tracing": "6.9.0",
    "@sentry/webpack-plugin": "1.16.0",
```

In index.tsx
```
Sentry.init({
  dsn: process.env.SENTRY_DSN,
  integrations: [new Integrations.BrowserTracing()],
  tracesSampleRate: 1.0,
  environment: 'production',
  release: 'test-4',
})
```

In webpack
```
new SentryWebpackPlugin({
    // sentry-cli configuration
    authToken: process.env.SENTRY_AUTH_TOKEN,
    org: process.env.SENTRY_ORG,
    project: process.env.SENTRY_PROJECT,
    release: 'test-4',

    // webpack-specific configuration
    include: '.',
    ignore: ['node_modules', 'webpack.config.js', 'lib'],
  })
```
3. Add additional properties to `compilerOptions` of `tsconfig.json` to support the Typescript files.
```
    "sourceMap": true, 
    "inlineSources": true,
    "sourceRoot": "/"
```
### Expected Result

What you thought would happen.
I should be able to trace the issues with the correct source codes.
### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?

1. Bundle files are uploaded correctly but no actual source codes(.ts, .tsx) are uploaded(maybe this is a desired behavior?)
<img width="1205" alt="Screen Shot 2021-07-15 at 6 00 53 AM" src="https://user-images.githubusercontent.com/34854380/125792526-b4e16fec-1862-4b5e-8d8a-67ed63a96324.png">

2. I'm not able to trace the issue with the correct sources.

<img width="1432" alt="Screen Shot 2021-07-15 at 6 01 59 AM" src="https://user-images.githubusercontent.com/34854380/125792532-66f421d7-5dcb-401e-ae40-2b5ca1a668f3.png">

**Comment by RoyChen4212** [comment]
Thank you very much @kamilogorek 
It worked!
<img width="1131" alt="Screen Shot 2021-07-15 at 7 25 15 AM" src="https://user-images.githubusercontent.com/34854380/125804615-7c6ff7d8-370a-4e59-9caf-66dc65b0a082.png">

However, I can only trace via `bundle.js` files instead of actual source codes. Is it possible to track the issues with actual source codes instead of bundle files?

**Comment by kamilogorek** [comment]
Sure, just upload corresponding `.js.map` files alongside your `.js` files and it'll work out of the box

**Comment by kamilogorek** [comment]
It "should" work just fine with `inlineSources` but just to be sure, can you try to produce and upload `.js` and `.js.map` separately? (just remove `inlineSources` from `tsconfig.json`).

**Comment by RoyChen4212** [comment]
<img width="1114" alt="Screen Shot 2021-07-15 at 8 05 29 AM" src="https://user-images.githubusercontent.com/34854380/125811158-11279be8-1811-45d7-af92-ad3ea1b46c1f.png">

That makes sense but it still doesn't work though I uploaded map files exactly.

**Comment by kamilogorek** [comment]
There's something wrong with their generation. `.js.map` files should be way bigger than the `.js` files themselves. You can use https://www.npmjs.com/package/source-map-cli to confirm they are working locally.

**Comment by RoyChen4212** [comment]
Alright, I'll figure out it myself later. Thanks for your support @kamilogorek
