### ISSUE TITLE
Webpack 5 + TS compatibility

### ISSUE THREAD

**Issue by Chrischuck** [getsentry/sentry-webpack-plugin#296]
This package imports webpack 4 and uses webpack 4 typedefs which are incompatible w/ webpack 5 and typescript.

Getting this error (But with sentry-webpack-plugin) - https://github.com/jantimon/html-webpack-plugin/issues/1383

**Comment by belgattitude** [comment]
This is also important for @sentry/nextjs ... it seems sourcemaps will be generated twice on v10.2+

**Comment by kamilogorek** [comment]
This issue has been already fixed in v1.14.1. It requires v4.41.23 of webpack to work. See: https://github.com/webpack/webpack/issues/11630#issuecomment-712995421

ref: https://github.com/getsentry/sentry-webpack-plugin/issues/258
ref: https://github.com/getsentry/sentry-webpack-plugin/pull/259
