### ISSUE TITLE
Mistaken "warning: could not determine a source map reference"

### ISSUE THREAD

**Issue by javierguzman** [getsentry/sentry-webpack-plugin#312]
Hello all,

I put this as a feature request as I do not believe is a bug. I am getting several warnings similar to the one below:
`warning: could not determine a source map reference `

This seems like a legitimate warning message. However, I am getting some bundle chunks from Webpack that do not have a corresponding map file. As far as I can see, these are related to dynamic import of files, e.g.
```
      const PrivacyPolicyFile = await import(
        /* webpackChunkName: "privacypolicy" */
        `./markdown/PrivacyPolicy.${currentLanguage}.md`
      );
```
I do not understand the details but for some reason, webpack does not generate maps for these chunks.

Then, my feature request would be to have Sentry query Webpack (if it is possible) how many map files have been created. From my ignorant point of view, this looks like Sentry just looking at the directory and trying to figure out on its own how many bundles and maps are around without asking Webpack.

Does this make sense? For now, I will have to start ignoring that warning :(

Thank you in advance and regards

**Comment by kamilogorek** [comment]
> From my ignorant point of view, this looks like Sentry just looking at the directory and trying to figure out on its own how many bundles and maps are around without asking Webpack.

That's basically it. We either go through listed files or scan included directories for `.js` files and try to find their corresponding `.js.map` files.

`sentry-cli` has no knowledge of webpack or anything that actually runs it, so it won't be possible to make it happen there. We'd need to do it on the plugin layer.

However, I believe you should be able to achieve what you want with `sourceMapReference: false`.

**Comment by javierguzman** [comment]
Thanks @kamilogorek!

So, could this be done in the plugin layer in future? or it is not possible due to Webpack not providing this kind of information to other plugins?

I have taken a look at the docs in regards to sourceMapReference and it says the default is false, so I must be using that already. However, the description says: 
```
Prevents the automatic detection of sourcemap references. 
```
So is it not false by default? 😕 Just asking because I am getting those warnings so I am assuming that warning is related to the automatic detection

**Comment by kamilogorek** [comment]
Could you try it? It indeed is kinda opposite, as its “preventing” the detection, which is responsible for those warnings. My comment is also incorrect, it should be set to `true` to silence these warnings 😶

**Comment by javierguzman** [comment]
I have run with the option set to true and it did not make any difference. However, if I set it to false, then the warnings do not appear. So this looks like the default value from the docs is incorrect I would say as I was getting warnings when I did not specify the option.

Also, what are the implications of setting this to false? Documentation shows "Prevents the automatic detection of sourcemap references". So what happens if I prevent the automatic detection? I mean, Sentry still works as far as I can tell. Is this some kind of verification? Could this option be described as "It checks if all bundles have a corresponding source map if set to true"?

**Comment by kamilogorek** [comment]
@javierguzman sorry for the confusion, you are correct. I verified it within the CLI itself and updated the docs accordingly - https://github.com/getsentry/sentry-webpack-plugin/pull/318/

If you are not relying on `Sourcemap` header within Sentry (which as long as your JS files contain `sourceMappingURL` you don't), then you are not missing anything by disabling it.

**Comment by javierguzman** [comment]
Thanks for the quick response @kamilogorek ! 

I have double-checked and it seems that my Webpack generates my bundles with sourceMappingURL included, so I guess that if I leave the aforementioned option disabled I do not miss anything if I have understood you correctly.

One last question, just out of curiosity. What would happen if I leave the option disabled and sourceMappingURL is not specified in my bundles? My bet is that Sentry then would not be able to find the matching map files, is my understanding correct?

**Comment by kamilogorek** [comment]
>  My bet is that Sentry then would not be able to find the matching map files, is my understanding correct?

Exactly this. Here is how we do it https://github.com/getsentry/sentry/blob/master/src/sentry/lang/javascript/processor.py#L150-L212

**Comment by javierguzman** [comment]
All clear then @kamilogorek ! I will leave the option disabled so I avoid a couple of warning messages. Thank you as always for your help. Have a nice day
