### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by liuxsen** [getsentry/sentry-webpack-plugin#315]
### Environment
nodejs   v12.16.2

### Steps to Reproduce

npm install @sentry/webpack-plugin -D

### Expected Result

What you thought would happen.

![image](https://user-images.githubusercontent.com/12598696/135398403-bf136bbc-267d-432e-86a6-dc8861031491.png)

this is should be report from @sentry/cli@1.69.0 when install it!

```js
"dependencies": {
    "@sentry/cli": "^1.68.0"
  },
```

**Comment by kamilogorek** [comment]
Issue tracked at https://github.com/getsentry/sentry-cli/issues/1037
