### ISSUE TITLE
Releases and Source Maps not Working

### ISSUE THREAD

**Issue by yordis** [getsentry/sentry-webpack-plugin#330]
### Environment

How do you use Sentry?

Self-hosted: 21.8.0 e1ddac6

Which SDK and version?

```yaml
{
  "@sentry/nextjs": "6.14.1"
}
```

### Steps to Reproduce

1. Add the following configuration to your NextJS in both files (client and server):
  ```ts
  import * as Sentry from '@sentry/nextjs';
  
  const SENTRY_DSN = process.env.SENTRY_DSN || process.env.NEXT_PUBLIC_SENTRY_DSN;
  
  Sentry.init({
    dsn: SENTRY_DSN,
    tracesSampleRate: 1.0,
    environment: process.env.NEXT_PUBLIC_ENV,
    release: process.env.NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA,
  });
  ```
2. Configure Vercel Environment Variables.

### Expected Result

Only one release should be created with the git commit SHA, and the source maps should work.

### Actual Result

We configured Vercel Environment with the proper configurations (as far as I can tell).

![Screen Shot 2021-11-07 at 2 35 46 PM](https://user-images.githubusercontent.com/4237280/140659731-70232c00-9b53-4e99-a266-402b8508d65c.png)

Although I also see the right releases being created correctly. I see a lot of random releases, I am not sure if the setup is creating two releases per deployment (it looks like).

And such random releases are the ones listed in the Source Maps, but I don't see any from the actual releases that are working.

The Source Maps are missing as well, no artifacts are created

![Screen Shot 2021-11-07 at 2 48 44 PM](https://user-images.githubusercontent.com/4237280/140659739-e99c8d9e-1a9c-4871-81ce-a4443edfa182.png)

**Comment by yordis** [comment]
Is there any way to run `next build` without creating releases, and only uploading the source maps?

**Comment by vimalHuber** [comment]
I also have the same problem. when we have some tests running on CICD pipeline from there it creates releases. 
is there any option that allows us to restrict create releases based on environment ?

**Comment by kamilogorek** [comment]
The CLI wont re-create already existing release, so if you want to only upload the files, you need to configure `release` value to be something that already matches previous release.

**Comment by yordis** [comment]
@kamilogorek let me try something around the topic then.

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!

**Comment by usrrname** [comment]
I've had this exact problem for days and I'm combing through a ton of docs on sentry, vercel and also next!
