### ISSUE TITLE
Sentry can not understand sources from sourcemaps

### ISSUE THREAD

**Issue by rubenaprikyan** [getsentry/sentry-webpack-plugin#331]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

`original project url`: https://github.com/aimhubio/aim/tree/feature/sentry-integration-on-ui/aim/web/ui
`actual files to see`: https://github.com/aimhubio/aim/blob/feature/sentry-integration-on-ui/aim/web/ui/config-overrides.js
Version
`@sentry-webpack-plugin`: `1.18.3`
`@sentry/react`: `^6.14.3`,
`@sentry/tracing": `^6.14.3"`
### Steps to Reproduce
````js 
new SentryCliPlugin({
      include: '.',
      ignore: ['node_modules', 'config-override.js', 'tasks'],
      dryRun: process.env.NODE_ENV !== 'production',
      project: 'test-vn0',
      org: 'test-vn0',
      authToken: env.SENTRY_AUTH_TOKEN,
      release: version,
      validate: true,
    }),
````

### Expected Result
artifacts uploaded successfully

<img width="1378" alt="Screen Shot 2021-11-18 at 4 21 46 PM" src="https://user-images.githubusercontent.com/21033329/142414533-9fbcbdea-de9b-4dd0-b392-f6a7513930eb.png">

Should recognize source files

### Actual Result
<img width="1358" alt="Screen Shot 2021-11-18 at 4 13 22 PM" src="https://user-images.githubusercontent.com/21033329/142413531-57ff827f-7c6a-45ca-b1d7-ded9b241df25.png">

**Comment by Amoodaa** [comment]
Same!
![image](https://user-images.githubusercontent.com/8256872/142868329-2efdafaf-8fb9-4dc4-9448-4f3f171386b6.png)
![image](https://user-images.githubusercontent.com/8256872/142868371-277bd033-4a90-4eb9-961c-ad470aeefe99.png)

**Comment by kamilogorek** [comment]
@rubenaprikyan your uploaded artifacts and stacktrace frames paths are not matching up, thus they are not getting resolved.

@Amoodaa can you provide your webpack config? It looks like you overwrote a `~/` prefix, which acts as a wildcard matcher for the url host - https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/#using-the-

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!
