### ISSUE TITLE
Source maps not applied to stack trace on Sentry

### ISSUE THREAD

**Issue by JordanAdedeji** [getsentry/sentry-webpack-plugin#335]
### Environment

Which SDK and version?
@sentry/webpack-plugin": "^1.18.3
@sentry/react": "^6.11.0",
@sentry/tracing: "^6.11.0",

### Steps to Reproduce

Sentry Plugin:

![Screenshot 2021-12-18 at 13 07 29](https://user-images.githubusercontent.com/43893080/146642207-ed75ace2-b275-4efe-8dae-ab50c0882d1f.png)

Artifacts uploaded:

![Screenshot 2021-12-18 at 13 09 29](https://user-images.githubusercontent.com/43893080/146642252-35252e55-129a-4890-86db-1fd681b7dffd.png)

### Expected Result

<img width="846" alt="2021-09-sentry-sourcemap-header" src="https://user-images.githubusercontent.com/43893080/146642717-63f35200-6776-4cf1-9147-64790a05fadd.png">

### Actual Result

Failed to fetch error and no source maps applied:

![Screenshot 2021-12-18 at 13 26 24](https://user-images.githubusercontent.com/43893080/146642703-3a3d11f8-4e1b-4278-9b7e-3e008253be14.png)

![Screenshot 2021-12-18 at 13 11 13](https://user-images.githubusercontent.com/43893080/146642277-f3b1a1ef-93d6-4b7d-a809-b314de9e6c18.png)

Event JSON:

![Screenshot 2021-12-18 at 13 13 40](https://user-images.githubusercontent.com/43893080/146642582-f22ba87e-8787-4ec2-a633-fa0c0b3a65b2.png)

**Comment by kamilogorek** [comment]
Change `urlPrefix` to `~/rewards/user-journey/static/js`, as your paths don't match.
