### ISSUE TITLE
error: An organization slug is required (provide with --org)

### ISSUE THREAD

**Issue by talaikis** [getsentry/sentry-webpack-plugin#337]
### Core or SDK?

Platform/SDK

### Which part? Which one?

@sentry/webpack-plugin

### Description

```
..\\..\\..\\AppData\\Roaming\\npm-cache\\sentry-cli\\5c4041-sentry-cli-Windows-x86-64.exe releases finalize blah-blag
```

gives

```
error: An organization slug is required (provide with --org)
```

### Suggested Solution

Mmaybe not use "wizards", CLIs and `sentry.properties` in webpack where simple json config should be enough?

**Comment by talaikis** [comment]
My bad, it was due to changed webpack requires.

**Comment by lobsterkatie** [comment]
Also, @talaikis, FWIW, you _can_ actually provide the org in the JSON config if you'd rather: https://github.com/getsentry/sentry-webpack-plugin.
