### ISSUE TITLE
Uploading sourcemaps issue: An organization slug is required (provide with --org)

### ISSUE THREAD

**Issue by nikolasp** [getsentry/sentry-webpack-plugin#34]
Hi, 

I'm using these versions of sentry webpack plugin and cli

```
"@sentry/cli@^1.28.1":
  version "1.30.2"
  resolved "https://registry.yarnpkg.com/@sentry/cli/-/cli-1.30.2.tgz#ead724c661920acda9b37779613dab7b0be9d828"
  dependencies:
    https-proxy-agent "^2.1.1"
    node-fetch "^1.7.3"
    progress "2.0.0"
    proxy-from-env "^1.0.0"

"@sentry/webpack-plugin@^1.3.3":
  version "1.3.3"
  resolved "https://registry.yarnpkg.com/@sentry/webpack-plugin/-/webpack-plugin-1.3.3.tgz#017bd7a89c8c9277d79c6c5feb51c1e6c6832b1b"
  dependencies:
    "@sentry/cli" "^1.28.1"
```

My sentry.properties file looks like this
```
[defaults]
url=https://sentry.io/
org=<YourOrgShortname>
project=<YourProjectShortname>

[auth]
token=<YourToken>
```

In webpack.config I've added plugin, where configFile is path to `sentry.properties` file

```
      new SentryCliPlugin({
        release: process.env.LAST_BUILD_TIME,
        configFile: process.env.SENTRY_PROPERTIES_FILE,
        include: './app/dist'
      }),
```
However, I always get this error below, but as you can see above I've added all required properties to `sentry.properties` file. Obviously `sentry.properties` file is correct because if I remove all lines I get different message `error: http error: Authentication credentials were not provided. (401)
`

```
./node_modules/@sentry/cli/sentry-cli releases new 1520006165 error: An organization slug is required (provide with --org)
```

I've opened stackoverflow question earlier just in case I'm doing something wrong...
https://stackoverflow.com/questions/49073088/issue-with-uploading-sourcemaps-with-sentry-webpack-plugin

Thanks for help.

**Comment by suancarloj** [comment]
I have the same problem, after looking around for a while I tried the cli directly at version 1.30.2 with:

```SENTRY_PROPERTIES=/path/to/sentry.properties npx sentry-cli info```

and it worked without a problem. I think this package might need to update the sentry-cli version

**Comment by ebuchmann** [comment]
I also run into the same issue. The plugin seems to run the sentry-cli command, but never includes any configuration like org, project, or auth token on it. If I run the sentry-cli command myself and include the options for all of these I can get it to work fine, but can't seem to find anyway for the webpack plugin to include the same arguments on the command.

**Comment by pfulop** [comment]
Yes from the look of it the configFile is not passed [here](https://github.com/getsentry/sentry-webpack-plugin/blob/ac191f1b7d925cc6d974e8b80a0f497f6958fe79/src/index.js#L83) since is not assigned in the constructor.

Setting config in .sentryclirc works tho.

**Comment by nikolasp** [comment]
Hi @jan-auer,
Thanks for answer. 😃 
I'll try this asap, but maybe you can do something with docs, it would be really helpful for others to see full `.property` example like you wrote above in README. 
I've seen just a partially config at https://docs.sentry.io/learn/cli/configuration/#properties-files, as you stated in readme and it's my mistake that I've formatted wrongly `.property` file, but docs is really confusing, at least for me.

**Comment by pfulop** [comment]
@jan-auer Sorry my bad. I should have looked better.

**Comment by nikolasp** [comment]
I've tested and everything works as it should with valid `.property` file...

**Comment by Waltari10** [comment]
For me defining project in .sentryclirc helped, even though it was complaining about the org.

**Comment by onurykaya** [comment]
Hi, I have a same problem, even though I changed the file name, the problem did not go away.

The problem occurs when i get build on my local.

my folder name -> .sentryclirc

       `
          defaults.url=xxx
          defaults.org=xxx
          defaults.project=xxx
          auth.token=xxx
      `

![image](https://user-images.githubusercontent.com/40173569/156246782-c1a3cd65-81c1-4e9a-8887-1a7fe756ce79.png)

Can you help me?

**Comment by kamilogorek** [comment]
@onurykaya this is not the format we are using in `.sentryclirc`. You need an `ini` file format, see: https://docs.sentry.io/product/cli/configuration/#configuration-file

It should be

```ini
[defaults]
url=xxx
org=xxx
project=xxx

[auth]
token=xxx
```
