### ISSUE TITLE
How to create a new release without uploading any artifacts?

### ISSUE THREAD

**Issue by vesper8** [getsentry/sentry-webpack-plugin#341]
I am uploading my artifacts manually after the build process, I'm doing this because I'm using codepush and this is the only way I could get it to work with the unique and dynamic url-prefix that codepush requires. So I want the release to be created during the build process but I don't want any artifacts to be uploaded.

I tried setting an empty array inside the `include` parameter but artifacts are still being for some reason.

**Comment by kamilogorek** [comment]
An empty array is treated as "no-value" and it will fallback to `output.path` value if absent.
I'm not sure why would you want an empty release to be created prior to upload though?

**Comment by vesper8** [comment]
@kamilogorek it's  related to https://github.com/getsentry/sentry-webpack-plugin/issues/342, I'm pulling my hair out trying to get the sourcemap paths to be readable. So I was attempting to upload the sourcemaps after the initial release creation and specifying the absolute path, but I ran into issues because on IOS the absolute path changes for every user. If I can resolve the issue by using `RewriteFrames` and removing the absolute path from the traces then that will solve my problem.. unfortunately I can't get this to work either, please see my latest comment. Hope you can help!

**Comment by kamilogorek** [comment]
Got it. Lets move the discussion there, or even better, you could ping us on our discord channel here - https://discord.gg/Ww9hbqr
