### ISSUE TITLE
How to prevent sentry from adding the full absolute path to files in stack traces?

### ISSUE THREAD

**Issue by vesper8** [getsentry/sentry-webpack-plugin#342]
I'm using Vue and Cordova and CodePush. I don't want to use the cordova sentry-cordova plugin.

I'm very close to having sourcemaps working now, it works well for the web version as well as for the Android version.

But on IOS whenever there is an error the file path for the stack trace is this really long absolute path that looks like this:

```

file:///var/mobile/Containers/Data/Application/080D7B3E-5D65-477E-B5FE-7BF040817F45/Library/NoCloud/codepush/deploy/versions/5c138750c5087f82862fd4c921de3f777c4fd87a865264cc5e31f6b14eabafc1/www'
```

But my sourcemaps that I've uploaded in the release all start with `~/`

I guess what I need is a way to have Sentry's webpack-plugin flatten/rewrite the paths to the files when it responds to the error? But I can't find how to do that.

Here is my init block:

```
Sentry.init({
  Vue,
  dsn: 'https://dc176dd743e44e1bb7252d878f6ba706@o1121417.ingest.sentry.io/6157965',
  logErrors: true,
  release: `${process.env.PACKAGE_NAME}@${process.env.PACKAGE_VERSION}`,
  integrations: [
    new Integrations.BrowserTracing({
      routingInstrumentation: Sentry.vueRouterInstrumentation(router),
      tracingOrigins: ['localhost', 'mydomain.com', /^\//],
    }),
  ],
  // Set tracesSampleRate to 1.0 to capture 100%
  // of transactions for performance monitoring.
  // We recommend adjusting this value in production
  tracesSampleRate: 1.0,
});
```

Should I be adding something more in the `tracingOrigins` so that it shortens/rewrites the paths correctly when being served from my app?

**Comment by kamilogorek** [comment]
What you are looking for is https://docs.sentry.io/platforms/javascript/configuration/integrations/plugin/#rewriteframes

Cheers!

**Comment by vesper8** [comment]
@kamilogorek Thank you! That looks / looked really promising. Unfortunately I cannot get it to work at all.

Here's what I've tried:

First I tried just adding the extra integration to my existing one:

```
import Vue from 'vue';
import * as Sentry from '@sentry/vue';
import { Integrations } from '@sentry/tracing';
import { RewriteFrames } from '@sentry/integrations';

import router from '../router';

Sentry.init({
  Vue,
  dsn: 'redacted',
  logErrors: true,
  release: `${process.env.PACKAGE_NAME}@${process.env.PACKAGE_VERSION}`,
  integrations: [
    new Integrations.BrowserTracing({
      routingInstrumentation: Sentry.vueRouterInstrumentation(router),
      tracingOrigins: ['localhost', 'nomadsoulmates.com', /^\//],
    }),
    new RewriteFrames(
      {
        iteratee: (frame) => `~/js/${frame.substring(frame.lastIndexOf('/') + 1)}`,
      },
    ),
  ],
});
```

Then I thought maybe the `Integrations.BrowserTracing` is interfering so I tried removing it

I also tried with `iteratee: (frame) => `~/js/${frame.substring(frame.lastIndexOf('/') + 1)}`,` as well as just `prefix: 'foo/'`

The paths that get generated look like this `/var/mobile/Containers/Data/Application/080D7B3E-5D65-477E-B5FE-7BF040817F45/Library/NoCloud/codepush/deploy/versions/635d2121aabfff0f2c322e46620e0647823573789871317d2d88856dcd2821bd/www/js/app.ff1b8e0e.js`

And I want them to look like this: `~/js/app.ff1b8e0e.js`

```

import Vue from 'vue';
import * as Sentry from '@sentry/vue';
import { RewriteFrames } from '@sentry/integrations';

Sentry.init({
  Vue,
  dsn: 'redacted',
  logErrors: true,
  release: `${process.env.PACKAGE_NAME}@${process.env.PACKAGE_VERSION}`,
  integrations: [
    new RewriteFrames(
      {
        prefix: 'foo/',
      },
    ),
  ],
});
```

No matter what I do, it basically has zero effect on the generated paths when an error is sent to sentry. See screenshots:
<img width="866" alt="Screen Shot 2022-01-24 at 3 17 15 PM" src="https://user-images.githubusercontent.com/816028/150790458-0958f34c-37ea-44fb-b5f2-36fd79e74ea2.png">

<img width="837" alt="Screen Shot 2022-01-24 at 3 17 32 PM" src="https://user-images.githubusercontent.com/816028/150790472-806f0cc6-6265-4f8b-badc-f0e3552f3812.png">

My artifacts:
<img width="332" alt="Screen Shot 2022-01-24 at 3 17 53 PM" src="https://user-images.githubusercontent.com/816028/150790518-8de0f480-edd4-44cc-bcd6-f481dcb9ffec.png">

Hope you can shed some light! I'm pulling my hair out over this :/

**Comment by kamilogorek** [comment]
> iteratee - function that takes the frame, applies a transformation, and returns it

```js
Sentry.init({
  Vue,
  dsn: 'redacted',
  logErrors: true,
  release: `${process.env.PACKAGE_NAME}@${process.env.PACKAGE_VERSION}`,
  integrations: [
    new Integrations.BrowserTracing({
      routingInstrumentation: Sentry.vueRouterInstrumentation(router),
      tracingOrigins: ['localhost', 'redacted.com', /^\//],
    }),
    new RewriteFrames({
      iteratee: (frame) => {
        frame.filename = `~/js/${frame.filename.substring(frame.filename.lastIndexOf('/') + 1)}`;
        return frame;
      }
    }),
  ],
});
```

This is how you should use it, hope that helps enough to get you going

**Comment by vesper8** [comment]
@kamilogorek Thank you! Hallelujah! That did it... but man... I spent like 30 minutes to set up Sentry and some ridiculous amount like 15 hours to get the sourcemaps working! This was so hard! The above behaviour should be the default or am I crazy? Please add this `frame.filename` to the examples... I still don't know why the `prefix: 'foo/'` didn't do anything... but the last piece you shared finally did the trick.

Now my IOS and Android apps are sending errors with the correct sourcemaps. For some reason the web client has completely stopped sending errors now.. don't know if it's related to the `RewriteFrames`

**Comment by kamilogorek** [comment]
> The above behaviour should be the default or am I crazy?

This integration is only meant for scenarios like yours, where assets are served from local filesystem. In most scenarios, there's no need for it's use, so it's not there by default.

> For some reason the web client has completely stopped sending errors now..

Add `debug: true` to your `Sentry.init` when developing, and utilize `beforeSend` callback to investigate the contents of your events. It'll make everything easier to track.

Added reference to docs: https://github.com/getsentry/sentry-docs/pull/4636
