### ISSUE TITLE
Config Option: Version

### ISSUE THREAD

**Issue by areindl** [getsentry/sentry-webpack-plugin#345]
Hi all! 

First of all: Thank you. The Plugin works great. We are using it with Nuxt 2  and are very happy with it.

One Question:

By default, the version is taken from the git commit:

![image](https://user-images.githubusercontent.com/5536491/152485540-3fef536e-845a-48c8-a0b3-d899f457c353.png)

Is there any option to specify a version (e.g. from package version)?

For our repo we use semantic versioning and automated released. So it would be desirable that Sentry shows the released version instead of the generic commit id.

Thanks for any help.

Best
Anton

**Comment by kamilogorek** [comment]
Hey, thanks, glad you like it! :)

Yes, this is called a "release", which by default is set to `sentry-cli releases propose-version` output, which on the other hand is based on various CI env variables, or if not available, fallbacks to the most recent git commit.

You can change it by providing `release` option in the plugin config.

See `release` field of https://github.com/getsentry/sentry-webpack-plugin#options

Cheers!
