### ISSUE TITLE
Is the plugin compatible with the major release of @sentry/cli?

### ISSUE THREAD

**Issue by sawilde** [getsentry/sentry-webpack-plugin#362]
The current plugin is referencing an older version of `@sentry/cli` however the cli package has a new major release and I want to know if they are compatible ie if my `yarn.lock` has both `@sentry/cli` 1.x (due to plugin) and 2.x (due to dependencies) will this be an issue or should I restrict my package.json to the 1.x version of `@sentry/cli` ?

**Comment by kamilogorek** [comment]
Yes, it is fully backward compatible, no need to change anything. Cheers!
