### ISSUE TITLE
ignoreFile option is not respected

### ISSUE THREAD

**Issue by Saravanan90** [getsentry/sentry-webpack-plugin#37]
This plugin, by default, injects `release id` in all the files under the `include` path.

Need to ignore a file from the above process, because it adds unnecessary reference of `global` in the file.

Hence included `.sentrycliignore` file and added a entry of the file name to be ignored in it.

But it doesn't work. Please suggest how to make this work

**Comment by Saravanan90** [comment]
Any suggestions to fix this?

**Comment by jan-auer** [comment]
Just to double check if I understand correctly: You are trying to exclude a file you have declared as `entrypoint` from being processed by our plugin? 

If so, this is not yet possible. `ignoreFile` only configures the scan for source code but not the injection of the release ID. We could add a new option, then.

**Comment by Saravanan90** [comment]
@jan-auer Yes, you are correct. Can we have a new option for it?

**Comment by jan-auer** [comment]
Released as `v1.5.1`
