### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by zhaoshunchen** [getsentry/sentry-webpack-plugin#371]
### Environment

"@sentry/tracing": "^6.11.0",
"@sentry/vue": "^6.11.0",
 "@sentry/webpack-plugin": "^1.17.1",

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/15214998/165786396-3e41d07c-ecca-4aa6-a54d-ee4ff8793b72.png">

**Comment by kamilogorek** [comment]
Can you provide more details? A reproduction? Environments used? Anything that would help debug this?

This is `sentry-cli` code, that's meant to be used within node environment, it should never be called within browser.

**Comment by zhaoshunchen** [comment]
> Can you provide more details? A reproduction? Environments used? Anything that would help debug this?
> 
> This is `sentry-cli` code, that's meant to be used within node environment, it should never be called within browser.

<img width="606" alt="image" src="https://user-images.githubusercontent.com/15214998/165895422-fdb36ec3-ca18-45aa-9ee1-050f9d144a4b.png">
<img width="486" alt="image" src="https://user-images.githubusercontent.com/15214998/165895563-43e7eb11-a6c6-4385-9193-12afd031f883.png">

node v12.20.0
@vue/cli 4.5.15
webpack@5.72.0

After the installation, run npm run dev, and an error occurs when the browser is opened
Deletion const SentryCliPlugin = require("@sentry/webpack-plugin")  works fine

**Comment by zhaoshunchen** [comment]
> Can you provide more details? A reproduction? Environments used? Anything that would help debug this?
> 
> This is `sentry-cli` code, that's meant to be used within node environment, it should never be called within browser.

<img width="1498" alt="image" src="https://user-images.githubusercontent.com/15214998/165896790-5728b264-d532-479e-a679-acf385f3a0a7.png">

The modification can be used normally，Please help me !

**Comment by kamilogorek** [comment]
I cannot reproduce this behavior locally. Would be great if you'd be able to provide a repro repository that I could use to debug this.
Again, this code should never make it to the bundle in the first place, so your webpack bundling is doing something funky.
I assume its something with devserver, as this is where it fails for you, so you can fix this with changing
```
if (process.env.VUE_APP_ENV = 'pro') {
```

to

```
if (process.env.VUE_APP_ENV = 'pro' && !process.env.WEBPACK_SERVE) {
```

(or `WEBPACK_DEV_SERVER` if you use old webpack version)`
