### ISSUE TITLE
How to match absolute path？

### ISSUE THREAD

**Issue by yutucc** [getsentry/sentry-webpack-plugin#377]
### Environment

```
"electron": "11.1.0",
"@sentry/webpack-plugin": "^1.18.9",
```

### Steps to Reproduce
I have a web page use the electron Renderer Process to render

in this web page, I use the sentry

Before that I had upload the sourcemap like this:
![image](https://user-images.githubusercontent.com/10840542/169277047-6081e4a0-b43d-48ed-b96e-385b3c16879d.png)

when sentry catch error and reported like this:
![image](https://user-images.githubusercontent.com/10840542/169277272-ef4a3257-dd28-447b-bd0b-b8528ba2b552.png)

`~/web/work-test/static/js/index.dfb14657.js` unable to match `/Applications/%E5%A6%99%E5%B0%8F%E7%A8%8B%E5%9B%BE%E5%BD%A2%E5%8C%96%E5%AE%A2%E6%88%B7%E7%AB%AF-%E6%B5%8B%E8%AF%95%E7%89%88.app/Contents/Resources/app/web/work-test/static/js/index.dfb14657.js`

and the sourcemap useless

### Expected Result

I want to match absolute path 

### Actual Result

unable to match  absolute path

**Comment by lforst** [comment]
Closing this because stale. Feel free to reopen any time!
