### ISSUE TITLE
Update sentry/cli to latest version

### ISSUE THREAD

**Issue by JonasJacobsUserspace** [getsentry/sentry-webpack-plugin#378]
Upgrade the package sentry/cli , because sentry/cli uses npmlog@4.1.2, which has vulnerability: Regular Expression Denial of Service (ReDoS) (due to linked ansi-regex@2.1.1)

**Comment by wojtekmaj** [comment]
I used Yarn resolutions to force newer npmlog:

```json
  "resolutions": {
    "npmlog@^4.1.2": "^6.0.0"
  },
```

and it worked. Looks like the only breaking change was dropping Node 6 and 8 support so...

**Comment by gsouf** [comment]
@kamilogorek sorry to ping you here, wondering if this one could get some attention? Thanks!

**Comment by gsouf** [comment]
#383 is awaiting for a merge
