### ISSUE TITLE
releasePromise.then is not a funtion

### ISSUE THREAD

**Issue by yuan2022** [getsentry/sentry-webpack-plugin#380]
### Environment

How do you use Sentry?
@sentry/webpack-plugin  1.18.8

Which SDK and version?
nodejs:16.14,vue-cli:5.0,vue:3.2.21 webpack: 5.72.1

### Steps to Reproduce

1. add config to vue.config.js plugins list
const SentryCliPlugin = require("@sentry/webpack-plugin");
const plugins = [];
process.env.NODE_ENV === "production" &&
  plugins.push(
    new SentryCliPlugin({
      include: "./dist",
      ignoreFile: ".gitignore",
      release: version, 
      ignore: ["node_modules", "webpack.config.js"],
      configFile: "./.sentryclirc", 
      urlPrefix: "~/",
      debug: true,
    })
  );
2. npm run build

### Expected Result

What you thought would happen.

### Actual Result

releasePromise.then is not a funtion
![image](https://user-images.githubusercontent.com/74589938/170909120-1f8ea561-2782-4afb-ba39-2436a3ae2511.png)

and 
![image](https://user-images.githubusercontent.com/74589938/170626076-1fce737a-2fb8-4490-9cde-02916e4d49ce.png)
I'm use Promise.resolve()，wrap it up，it's ok

**Comment by FE-YJP** [comment]
this may help you
https://github.com/getsentry/sentry-webpack-plugin/issues/272

**Comment by FE-YJP** [comment]
> ### Environment
> How do you use Sentry? @sentry/webpack-plugin 1.18.8
> 
> Which SDK and version? nodejs:16.14,vue-cli:5.0,vue:3.2.21 webpack: 5.72.1
> 
> ### Steps to Reproduce
> 1. add config to vue.config.js plugins list
>    const SentryCliPlugin = require("@sentry/webpack-plugin");
>    const plugins = [];
>    process.env.NODE_ENV === "production" &&
>    plugins.push(
>    new SentryCliPlugin({
>    include: "./dist",
>    ignoreFile: ".gitignore",
>    release: version,
>    ignore: ["node_modules", "webpack.config.js"],
>    configFile: "./.sentryclirc",
>    urlPrefix: "~/",
>    debug: true,
>    })
>    );
> 2. npm run build
> 
> ### Expected Result
> What you thought would happen.
> 
> ### Actual Result
> releasePromise.then is not a funtion ![image](https://user-images.githubusercontent.com/74589938/170909120-1f8ea561-2782-4afb-ba39-2436a3ae2511.png)
> 
> and ![image](https://user-images.githubusercontent.com/74589938/170626076-1fce737a-2fb8-4490-9cde-02916e4d49ce.png) I'm use Promise.resolve()，wrap it up，it's ok

this may help you
https://github.com/getsentry/sentry-webpack-plugin/issues/272

**Comment by FE-YJP** [comment]
this may help you
https://github.com/getsentry/sentry-webpack-plugin/issues/272

**Comment by lforst** [comment]
I believe this should be fixed in the newest version of the plugin. Feel free to reopen any time!
