### ISSUE TITLE
Security vulnerability - node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor

### ISSUE THREAD

**Issue by Skrigueztep** [getsentry/sentry-webpack-plugin#382]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

Sentry.io 1.15.1 (according to dep installed)

Which SDK and version?
e.g: JavaScript 5.11.1, .NET 1.2.0

Javascript: 1.15.1 (According to dep installed)

### Steps to Reproduce

1. What
2. you
3. did.

Install @sentry/webpack-plugin v1.15.1 into project with `npm i -D @sentry/webpack-plugin@1.15.1`
Execute `npm audit`

### Expected Result

What you thought would happen.

No vulnerabilities reported

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?

High vulnerability reported

**Please update @sentry/cli dep to v2.1.0**

![image](https://user-images.githubusercontent.com/37033584/171322715-12620a03-2b0a-4e3e-869a-76e11b21d343.png)

**Comment by Skrigueztep** [comment]
Another vulnerability is reported;  **Inefficient Regular Expression Complexity in chalk/ansi-regex** caused by dependencies. Related issue: **[62](https://github.com/iarna/wide-align/issues/62)**

**Comment by morijenab** [comment]
I can see that the latest `sentery-cli` the `node-fetch` version is [2.6.7](https://github.com/getsentry/sentry-cli/blob/master/package.json#L19) please update `sentry-cli` to the newest version. 

we are facing vulnerability bot errors for all our PRs

**Comment by lforst** [comment]
This should be fixed in the newest version of the webpack plugin.
