### ISSUE TITLE
Move @sentry/cli to peer dependencies?

### ISSUE THREAD

**Issue by dimitarnestorov** [getsentry/sentry-webpack-plugin#40]
At the time I'm writing this I can't install `@sentry/cli`@1.30.3 on Windows since the install script searches for an executable which is currently unavailable. That renders `@sentry/webpack-plugin` unavailable for installation on Windows. Do you guys mind specifying `@sentry/cli` as a peer dependency? Something like this could happen in the future.

**Comment by mitsuhiko** [comment]
> Something like this could happen in the future.

Not sure what you mean by that. If the dependency has a bad release then the webpack plugin is unlikely to work. It generally should not happen that a release of the cli goes out like that.

**Comment by kamilogorek** [comment]
@dimitarnestorov you should be able to install it correctly right now. The build has been fixed, so let me close this issue.
