### ISSUE TITLE
Upload fails under node 18

### ISSUE THREAD

**Issue by RobinClowers** [getsentry/sentry-webpack-plugin#409]
### Environment
Node 18.12.0
@sentry/cli 1.73.2
@sentry/webpack-plugin 1.18.8

### Steps to Reproduce
After upgrading to node 18, our existing usage of this plugin stopped working. Here is the webpack config:
```js
    new SentryPlugin({
      include: path.resolve(__dirname, "dist", "frontend"),
      org: "<org name>",
      project: "<project name>",
      release: process.env.SENTRY_RELEASE,
      authToken: process.env.SENTRY_AUTH_TOKEN,
    })
```

### Expected Result
Our build should successfully upload sourcemaps to sentry.

### Actual Result

This error appears to be the culprit. We do not have a sentryclirc file, all our configuration is done through webapack.
> ERROR in Sentry CLI Plugin: Command failed: /node_modules/@sentry/cli/sentry-cli releases new 4719f88c655328052814913183afff7167409c02
error: Failed to load .sentryclirc file from the home folder.
  caused by: Permission denied (os error 13)
thread 'unnamed' panicked at 'Config not bound yet': src/config.rs:87

**Comment by Lms24** [comment]
Hi @RobinClowers thanks for writing in! We'll have to look into this, backlogging for now.
 
I know it's not a perfect solution but for the time being you could probably add an empty `.sentryclirc` file to your project and use the `configFile` option to point towards this file?

**Comment by RobinClowers** [comment]
@Lms24 thanks for responding! Sadly, writing a `.sentryclirc` file did not work either, I still get a permission denied error. I'm going to keep digging on my end, presumably it's something funny about my docker image that's causing this, though I have no idea what.

**Comment by HazAT** [comment]
We need a clear repro here please, closing for now.
