### ISSUE TITLE
Dogfood sentry-webpack-plugin

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-webpack-plugin#410]
### Background
With the [sentry-unplugin](https://github.com/getsentry/sentry-javascript-bundler-plugins) work we will be able to monitor it in Sentry. This allows us to check the performance and tracing of our own product.

[sentry-unplugin Sentry project](https://sentry.io/organizations/sentry/performance/?project=6690737)

### Outcomes:
- able to track quantity of usage
- this we will then be able to compare with sentry-unplugin data to determine which JS bundlers are being used the most
- able to detect any performance issues
- able to trace the different services (projects) involved with upload of source maps

### Requirements:
- a new project in Sentry org
- Bare minimum transactions to be sent to that project
- should be a tag for `bundler:"bundler-name"`
  - obviously on sentry-webpack-plugin this should always be the webpack, but would be nice to have some check if possible
- we should be able to differentiate between CI or test stage transaction and what is sent from production environment
- strip down what is sent to Sentry to a bare minimum to reduce all risk of any PII sent Sentry

**Comment by smeubank** [comment]
@lforst did we decide to not do this? I cannot remember 😓

**Comment by lforst** [comment]
Ah right thanks for reminding me. I think we still wanted to do this.

**Comment by lforst** [comment]
Priorities are somewhere else and we are soon publishing from https://github.com/getsentry/sentry-javascript-bundler-plugins which has telemetry already
