### ISSUE TITLE
customHeader field in SentryWebpackPlugin doesn't work

### ISSUE THREAD

**Issue by ryanhugh** [getsentry/sentry-webpack-plugin#416]
### Environment

What version are you running? Etc.

@sentry/webpack-plugin v1.20.0

### Steps to Reproduce

1. Set up @sentry/webpack-plugin as a plugin to a webpack config
2. Add the customHeader field
3. Run webpack build
(see code screenshot)

### Expected Result

It should send the custom header. It does send the customer header when I set the CUSTOM_HEADER env var, so I'm not blocked on this bug. 

### Actual Result

It doesn't work with field:

<img width="536" alt="image" src="https://user-images.githubusercontent.com/5777995/207497370-b7013ac9-07af-420d-b6f7-3b0e3d4a3be2.png">

<img width="615" alt="image" src="https://user-images.githubusercontent.com/5777995/207497430-24c2db10-1822-423e-b9af-4122b0b2e8f9.png">

It works with env var: 

<img width="505" alt="image" src="https://user-images.githubusercontent.com/5777995/207497679-f64c2f6c-d6b3-4928-b14f-988f5fef314a.png">
<img width="504" alt="image" src="https://user-images.githubusercontent.com/5777995/207497706-17f3bb0f-35aa-4182-82d9-3eeedf43b1c5.png">

**Comment by lforst** [comment]
Hi, is this still an issue for you with the newest version of the plugin?
