### ISSUE TITLE
API key is not valid

### ISSUE THREAD

**Issue by ransomenfor** [getsentry/sentry-webpack-plugin#421]
I have been trying to run the following command but I keep getting the error message "API key is not valid". Please I need guidance on how to get this fixed. Which key should I use and how can I generate it? Thank you for your time.

curl https://sentry.io/api/0/organizations/project-name/releases/ -u $SENTRY_API_KEY:
response: {"detail":"API key is not valid"}

**Comment by lforst** [comment]
You can create auth tokens here: https://sentry.io/settings/account/api/auth-tokens/
