### ISSUE TITLE
sourcemap urlprefix setting

### ISSUE THREAD

**Issue by KobeZhou** [getsentry/sentry-webpack-plugin#426]
Environment
self-hosted (https://develop.sentry.dev/self-hosted/)

Version
23.1.1

Link
No response

DSN
No response

Steps to Reproduce
Example：config.plugin("sentryCliPlugin").use(sentryCliPlugin, [
{
release: "",
include: "",
ignore: [],
configFile: "sentry.properties",
urlPrefix: "www.xx.com/1/static/js",
},
]);

my static resource is deployed by CDN， so the urlPrefix is dynamic；For example， this url of static resource is ‘http:// [www.xx.com/1/static/js’](http://www.xx.com/1/static/js%E2%80%99) this time, and next time, the url of static resource is ‘http:// [www.xx.com/2/static/js’](http://www.xx.com/2/static/js%E2%80%99) ;

how to handle the urlPrefix。

Expected Result
I can use sourcemap correctly in sentry。

Actual Result
I do not konw how to do。

**Comment by lforst** [comment]
If you run into a situation where the url of a resource is dynamic, generally the [RewriteFrames integration](https://docs.sentry.io/platforms/node/configuration/integrations/pluggable-integrations/#rewriteframes) is your friend :)

**Comment by KobeZhou** [comment]
> If you run into a situation where the url of a resource is dynamic, generally the [RewriteFrames integration](https://docs.sentry.io/platforms/node/configuration/integrations/pluggable-integrations/#rewriteframes) is your friend :)

thanks guy,   following my url,  can you write a demo？

**Comment by lforst** [comment]
I recommend you just play around with it a bit. The name of your uploaded artifacts must match with the filename of the stackframe. In your case you probably need the `iteratee` option.

**Comment by lforst** [comment]
Closing because stale
