### ISSUE TITLE
Issues not referenceing sourcemap artifact

### ISSUE THREAD

**Issue by chrisjbrown** [getsentry/sentry-webpack-plugin#437]
I've setup releases and am uploading my .js and .js.map files to sentry through this plugin.
I do see my files are getting to sentry and sentry is creating a release for them.

New issues that come in do reference the release correctly but sentry doesn't seem to connect the error thrown to the artifact file, but is instead trying to get the sourcemap from my server where it does not exist, hence the 403.

my asset files are hosted on a s3 bucket within a subfolder. I'm not sure if this needs to be included via the `urlPrefix` option. but I did try that with the same result ☹️  

<img width="1194" alt="Screen Shot 2023-04-20 at 10 04 24 AM" src="https://user-images.githubusercontent.com/1250638/233395999-abc97274-2bf3-4aa1-94be-9334e82493de.png">

<img width="1148" alt="Screen Shot 2023-04-20 at 10 05 55 AM" src="https://user-images.githubusercontent.com/1250638/233395643-1d9fd07c-8ad9-4eea-b536-b3276aab4027.png">

<img width="406" alt="Screen Shot 2023-04-20 at 10 10 33 AM" src="https://user-images.githubusercontent.com/1250638/233395613-27d0fccf-c1fd-4707-abb2-a2c6d83c91a1.png">

<img width="352" alt="Screen Shot 2023-04-20 at 10 15 33 AM" src="https://user-images.githubusercontent.com/1250638/233395552-78a4d67a-50d1-4bc8-8cb6-16788202c21c.png">

**Comment by lforst** [comment]
Are you on SaaS? If so can you share a link to the event and I can take a look!

**Comment by chrisjbrown** [comment]
yes. thanks!
i've pushed a few new releases trying different things. but here is an issue from the release with the configuration above

https://ithaka.sentry.io/share/issue/01e9fcbb68074a3f912ca04404444ad2/

**Comment by lforst** [comment]
Took a look. `urlPrefix` must include the entire path. So in your case the uploaded artifacts would need to look like: `~/.../.../.../7130.b5f58aacdc41429b0498.js` (where ... are the actual parts of the path)

If the `...` are dynamic you can use the [RewriteFrames integration](https://docs.sentry.io/platforms/node/configuration/integrations/pluggable-integrations/#rewriteframes) to modify the paths before sending them to sentry.

**Comment by chrisjbrown** [comment]
I thought that might be the case. I did try adding 
```urlPrefix: ~/mfe-copper-roof/item-recommender/${gitHash}```

here's an issue with that option
https://ithaka.sentry.io/issues/4112431205/events/b1a9e74597354f93aa31987780368b77/

**Comment by chrisjbrown** [comment]
> I thought that might be the case. I did try adding `urlPrefix: ~/mfe-copper-roof/item-recommender/${gitHash}`
> 
> here's an issue with a release using that option https://ithaka.sentry.io/issues/4112431205/events/b1a9e74597354f93aa31987780368b77/

🤦 i made that change in the prod config but not test. Going to making the change there and retry

**Comment by chrisjbrown** [comment]
that worked! thanks for your help!
