### ISSUE TITLE
Unable to install in CI

### ISSUE THREAD

**Issue by JalilArfaoui** [getsentry/sentry-webpack-plugin#44]
I'm trying to enable Sentry in CI but on `yarn install` I get : 

```
[4/4] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error /builds/project_name/node_modules/@sentry/cli: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments: 
Directory: /builds/project_name/node_modules/@sentry/cli
Output:
fetching sentry-cli-Linux-x86_64 1%
fetching sentry-cli-Linux-x86_64 2%
fetching sentry-cli-Linux-x86_64 3%
...
fetching sentry-cli-Linux-x86_64 99%
fetching sentry-cli-Linux-x86_64 100%
Error: spawn /builds/project_name/node_modules/@sentry/cli/sentry-cli ENOENT
ERROR: Job failed: exit code 1
```

I was using version 1.3.2 but I just tried with 1.5.0 and have the same error ...

Any idea why ?

**Comment by JalilArfaoui** [comment]
Of course, it works on my local Linux machine, and it also works with my local Docker FROM node, but I have the error in gitlab-ci, using docker:latest image (yarn installed with apk)

**Comment by JalilArfaoui** [comment]
OK, I'm back at home. 

I can reproduce the problem with this simple Dockerfile : 

```
FROM docker:latest
RUN apk --update add --no-cache curl git jq nodejs yarn
RUN yarn add @sentry/webpack-plugin
```

**Comment by JalilArfaoui** [comment]
But the same goes if I try to install @sentry/cli : 

```
FROM docker:latest
RUN apk --update add --no-cache nodejs yarn
RUN yarn add @sentry/cli
``` 

The output : 

✘  ~/code/tmp/test-sentry  docker build .
Sending build context to Docker daemon  14.34kB
Step 1/3 : FROM docker:latest
 ---> cf0bbd4500c6
Step 2/3 : RUN apk --update add --no-cache nodejs yarn
 ---> Running in ea8efb65baa7
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/10) Installing nodejs-npm (8.9.3-r1)
(2/10) Installing c-ares (1.13.0-r0)
(3/10) Installing libcrypto1.0 (1.0.2o-r0)
(4/10) Installing libgcc (6.4.0-r5)
(5/10) Installing http-parser (2.7.1-r1)
(6/10) Installing libssl1.0 (1.0.2o-r0)
(7/10) Installing libstdc++ (6.4.0-r5)
(8/10) Installing libuv (1.17.0-r0)
(9/10) Installing nodejs (8.9.3-r1)
(10/10) Installing yarn (1.3.2-r0)
Executing busybox-1.27.2-r7.trigger
OK: 65 MiB in 22 packages
Removing intermediate container ea8efb65baa7
 ---> e3954dde4012
Step 3/3 : RUN yarn add @sentry/cli
 ---> Running in 0ccf32704425
yarn add v1.3.2
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
error /node_modules/@sentry/cli: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments: 
Directory: /node_modules/@sentry/cli
Output:
fetching sentry-cli-Linux-x86_64 1%
fetching sentry-cli-Linux-x86_64 2%
...
fetching sentry-cli-Linux-x86_64 99%
fetching sentry-cli-Linux-x86_64 100%
Error: spawn /node_modules/@sentry/cli/sentry-cli ENOENT
The command '/bin/sh -c yarn add @sentry/cli' returned a non-zero code: 1
 ✘  ~/code/tmp/test-sentry 

**Comment by JalilArfaoui** [comment]
As this seems to come from @sentry/cli, I commented there : 

https://github.com/getsentry/sentry-cli/issues/281

It seems to be unable to install via rpm/yarn on Alpine Linux ...

And it seems it won't be fixed :-(

**Comment by jan-auer** [comment]
Closing this in favor of https://github.com/getsentry/sentry-cli/issues/227
