### ISSUE TITLE
npm install started failing trying to install @sentry/cli@1.75.1

### ISSUE THREAD

**Issue by d3vtoolsmith** [getsentry/sentry-webpack-plugin#441]
### Environment

```
"dependencies": {
  ...
  "@angular/core": "^14.2.9",
  ...
  "@sentry/angular-ivy": "^7.50.0",
  "@sentry/tracing": "^7.50.0",
  ...
},
"devDependencies": {
  "@angular-builders/custom-webpack": "^14.1.0"
  "@sentry/webpack-plugin": "^1.20.1"
  ...
}
```

### Steps to Reproduce

1. Run `npm install` (technically, as part of Azure DevOps build pipeline).

### Expected Result

Should've installed and built as just a couple of days ago.

### Actual Result

`npm install` step fails with the following error (started just a day or so ago):

```
verbose pkgid @sentry/cli@1.75.1
33428 verbose cwd D:\a\1\s
33429 verbose Windows_NT 10.0.20348
33430 verbose argv "C:\\hostedtoolcache\\windows\\node\\14.21.3\\x64\\node.exe" "C:\\hostedtoolcache\\windows\\node\\14.21.3\\x64\\node_modules\\npm\\bin\\npm-cli.js" "install"
33431 verbose node v14.21.3
33432 verbose npm  v6.14.18
33433 error code ELIFECYCLE
33434 error errno 1
33435 error @sentry/cli@1.75.1 install: `node ./scripts/install.js`
33435 error Exit status 1
33436 error Failed at the @sentry/cli@1.75.1 install script.
```

**Comment by Lms24** [comment]
Hi @d3vtoolsmith thanks for reporting! I strongly believe this is related to https://github.com/getsentry/sentry-cli/issues/1597. Please follow the progress there. We're going to release a fix in a couple of hours. Closing this issue in the meantime. Also pleas feel free to tag me if the issue persists after the new fix is released.

**Comment by Lms24** [comment]
The checksum mismatch in the CLI is fixed. Installing the Webpack plugin should work again now on Windows.
