### ISSUE TITLE
Node 4 support

### ISSUE THREAD

**Issue by jalleyne** [getsentry/sentry-webpack-plugin#45]
hey guys, I'm aware node 4 is a legacy version but i have a pretty large codebase on AWS Lambda/ Serverless framework 0.5.6 that im integrating Sentry into and wondering what the effort is like to get the module working for node >= 4.3.x. <= 6.x.x At the moment i get syntax errors, but hoping i can convert these easily. I'll dig into the codebase when i get a moment, but wanted to get initial thoughts.

```
[SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode]
```
thanks

**Comment by kamilogorek** [comment]
We don't support Node v4 just because it's running out of LTS support in 3 weeks from now. However, I've got you covered. Hopefully it helps! :)

https://github.com/getsentry/sentry-webpack-plugin/tree/node-v4

Cheers!

**Comment by jan-auer** [comment]
To follow-up here: Both `webpack` and `webpack-cli` also require at least Node 6. I think we should add a `peerDependency` requirement.
