### ISSUE TITLE
Bump Sentry CLI to newer version

### ISSUE THREAD

**Issue by lforst** [getsentry/sentry-webpack-plugin#454]
Since Sentry CLI v1 will likely face a crash on macOS Sonoma Beta (see https://github.com/alexcrichton/curl-rust/issues/524) we need to come up with a way to upgrade Sentry CLI to v2 in a non-breaking way for the webpack plugin v1.

**Comment by SomeoneToIgnore** [comment]
👋 
Upstream curl issue had been fixed, new `curl-sys` version had been released and seems to work on Sonoma.
See https://github.com/alexcrichton/curl-rust/issues/524#issuecomment-1753070751 for more details.
