### ISSUE TITLE
Add "debug mode" to see all inputs and outputs

### ISSUE THREAD

**Issue by kamilogorek** [getsentry/sentry-webpack-plugin#50]
Ref: https://github.com/getsentry/sentry-webpack-plugin/issues/36#issuecomment-384268710

**Comment by jan-auer** [comment]
This has been resolved via https://github.com/getsentry/sentry-webpack-plugin/commit/6984574fc89f58e2716255359db0484df038f34f

**Comment by rodocontegni** [comment]
Is there going to be a 1.5.3 release that includes `debug mode`?
