### ISSUE TITLE
Does this plugin support refing commit to a Release?

### ISSUE THREAD

**Issue by williamchong007** [getsentry/sentry-webpack-plugin#55]
as written here https://docs.sentry.io/learn/releases/
how can we ref the commit hash using this plugin?

**Comment by jan-auer** [comment]
This will happen automatically when you do not specify a `release` in the configuration. It uses `sentry-cli releases propose-version` under the hood, which will use the current commit hash when running inside a git repository.

**Comment by Cherry** [comment]
If we're using a different `release`, is there no way to pass options to the `set-commits` command in `sentry-cli`? Even when not setting a `release`, I do not see releases tagged with specific git commits in Sentry.

![](https://up.jross.me/f70t5)
The top 2 releases are once switching to this plugin - note there not being any git commits registered.

**Comment by Cherry** [comment]
@jan-auer Could we take another look at this? We're not able to tie releases to git commits.
