### ISSUE TITLE
Delete SourceMaps after upload

### ISSUE THREAD

**Issue by Cherry** [getsentry/sentry-webpack-plugin#56]
Does this support deleting sourcemaps from the local filesystem after they've been successfully uploaded to sentry? I can't seem to find any documentation for how to do this.

**Comment by jan-auer** [comment]
This is not possible right now, as sentry-cli (which is used under the hood) does not support this. Although it might be an interesting idea, I think this is slightly out of scope of that command and would be easy to solve with a separate command or separate webpack plugin. 

The reason this might not be so straight forward is that we would like to add globs to the sourcemap upload soon, and it then would become confusing of only those files get deleted and other remain on the file system. 

A quick fix would be to `rm -rf dist/**/*.js.map` (or use the `rimraf` node module) after your build has succeeded.

**Comment by ahmadalli** [comment]
you can add `"postbuild": "rimraf ./build/**/*.js.map"` script to your package.json file

**Comment by mmnavarr** [comment]
Is there any reason this wouldn't be correct vs. using a DeleteSourceMapsPlugin?

**Comment by verekia** [comment]
This may be hard to fix, but I don't understand how this is not a more talked-about topic. No one cares if uploading sourcemaps to Sentry makes their codebase publicly accessible? Like @rap2hpoutre said, deleting them without removing the reference creates 404 noise, which can be very messy if there are a lot of references. Isn't there any clean solution for this?

**Comment by verekia** [comment]
I wrote my own script, which relies on `klaw-sync` and `replace-in-file`, but it's less than ideal and doesn't work on files that start with `[` like in Next, so some references won't be removed.

```js
const fs = require('fs');

const klawSync = require('klaw-sync');
const replace = require('replace-in-file');

const sourcePaths = klawSync('.next')
  .map((p) => p.path)
  .filter((p) => p.endsWith('.css') || (p.endsWith('.js') && !p.includes('[')));

const mapPaths = klawSync('.next')
  .map((p) => p.path)
  .filter((p) => p.endsWith('.map'));

console.log(`Deleted ${mapPaths.length} sourcemap files.`);
mapPaths.forEach((p) => fs.unlinkSync(p));

const main = async () => {
  try {
    const results = await replace({
      files: sourcePaths,
      from: [/\/\/\# sourceMappingURL=.*/g, /\/\*\#.* sourceMappingURL=.*/g],
      to: '',
    });
    console.log(
      `Removed ${
        results.filter((r) => r.hasChanged).length
      } sourcemap references from .next/`
    );
  } catch (error) {
    console.error('Error occurred:', error);
  }
};

main();
```

**Comment by DaniAkash** [comment]
> ```shell
> # delete sourcemaps
> find .next -type f -name '*.js.map' -delete
> find .next -type f -name '*.css.map' -delete
> 
> # delete sourcemaps refs
> find .next -type f -name '*.js' -exec sed -i -E 's/sourceMappingURL=[^ ]*\.js\.map//g' {} +
> find .next -type f -name '*.css' -exec sed -i -E 's/sourceMappingURL=[^ ]*\.css\.map//g' {} +
> ```

Thanks @anoopmd this solves the issues in a post-build step

mac users should install [gsed](https://formulae.brew.sh/formula/gnu-sed) for the above sed command to work

**Comment by lucas-janon** [comment]
I'm using `rimraf ./.next/**/*.js.map` to delete my sourcemaps post-build and updating to Next.js 12 breaks with the following error:

```bash
[Error: ENOENT: no such file or directory, lstat '/vercel/path0/packages/frontend/catalog/.next/server/webpack-runtime.js.map'] {
--
14:56:44.882 | errno: -2,
14:56:44.882 | code: 'ENOENT',
14:56:44.882 | syscall: 'lstat',
14:56:44.882 | path: '/vercel/path0/packages/frontend/catalog/.next/server/webpack-runtime.js.map'
14:56:44.883 | }
```

Did anybody find a solution?

**Comment by Sparragus** [comment]
I'm having the same problem as @lucas-janon. Has any one found a solution?

**Comment by Sparragus** [comment]
@lucas-janon This discussion helped me a lot: https://github.com/vercel/next.js/discussions/24342#discussioncomment-643887

My solution was to add

```
async rewrites() {
        const isVercel = !!process.env.VERCEL_ENV;
        if (isVercel) {
            return {
                beforeFiles: [
                    {
                        source: "/:path*.map",
                        destination: "/404",
                    },
                ],
            };
        }

        return [];
}
```

to `next.config.js`.

All in all, I think this is a more elegant solution than deleting the source maps post-build.

Happy hacking!

**Comment by lucas-janon** [comment]
That's a great find, thanks @Sparragus!

**Comment by DaniAkash** [comment]
> > ```shell
> > # delete sourcemaps
> > find .next -type f -name '*.js.map' -delete
> > find .next -type f -name '*.css.map' -delete
> > 
> > # delete sourcemaps refs
> > find .next -type f -name '*.js' -exec sed -i -E 's/sourceMappingURL=[^ ]*\.js\.map//g' {} +
> > find .next -type f -name '*.css' -exec sed -i -E 's/sourceMappingURL=[^ ]*\.css\.map//g' {} +
> > ```
> 
> Thanks @anoopmd this solves the issues in a post-build step
> 
> mac users should install [gsed](https://formulae.brew.sh/formula/gnu-sed) for the above sed command to work

Deleting the sourcemap refs following the above method - effectively renders sentry sourcemaps unsuable ([document reference](https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/#verify-sourcemappingurl-is-present))

So i'd recommend deleting sourcemap refs of only the service worker js file

**Comment by kamilogorek** [comment]
@DaniAkash that's not correct for artifacts uploaded via cli. We attach `sourceMappingULR` to the file header, so even without it our maps will work.

**Comment by DaniAkash** [comment]
@kamilogorek i'm on a next.js + vercel environment. There's no header attached to our js files after they are deployed to vercel

**Comment by davidjnelson-bluescape** [comment]
@dcramer this issue makes sentry look buggy.  please have this fixed.

**Comment by ThibaultVlacich** [comment]
> ```shell
> # delete sourcemaps
> find .next -type f -name '*.js.map' -delete
> find .next -type f -name '*.css.map' -delete
> 
> # delete sourcemaps refs
> find .next -type f -name '*.js' -exec sed -i -E 's/sourceMappingURL=[^ ]*\.js\.map//g' {} +
> find .next -type f -name '*.css' -exec sed -i -E 's/sourceMappingURL=[^ ]*\.css\.map//g' {} +
> ```

A more platform-agnostic way of doing it, using a Node script:
`"postbuild": "node ./scripts/postbuild.js"`

```
const fs = require('node:fs/promises')
const glob = require('glob')

// Delete sourcemaps
glob('./dist/**/*.js.map', (_err, files) => {
  files.forEach(fs.unlink)
})

// Delete sourcemaps refs
glob('./dist/**/*.js', (_err, files) => {
  files.forEach(async (filePath) => {
    try {
      const fileContent = await fs.readFile(filePath, 'utf8')
      await fs.writeFile(filePath, fileContent.replace(/\/\/# sourceMappingURL=\S+/g, ''))
    } catch (err) {
      console.error(err)
    }
  })
})
```

**Comment by odini85** [comment]
> If you use node version 13 or lower, you can replace glob with fast-glob.

**Comment by JackZong** [comment]
seems here is the solution:
https://www.npmjs.com/package/@sentry/webpack-plugin
