### ISSUE TITLE
Build takes a long time, then "Command failed" "sentry-cli releases files"

### ISSUE THREAD

**Issue by akinnee** [getsentry/sentry-webpack-plugin#63]
With the plugin configured, the build takes a lot longer, but then it fails with the following error:

> ERROR in Sentry CLI Plugin: Command failed: /Users/alexkinnee/repos/Notion/desktop/node_modules/@sentry/cli/sentry-cli releases files connect-2.24.2-252cbe4ed7e90e59a750d016750055c463f629e4 upload-sourcemaps . --ignore node_modules --ignore **/webpack/** --rewrite

But then I see the release in Sentry:
<img width="872" alt="screen shot 2018-06-21 at 10 21 47 am" src="https://user-images.githubusercontent.com/3019562/41725061-f393bb8a-753c-11e8-9a3a-eb52cb035656.png">

How can I debug/fix whatever is going on?

Thanks!

**Comment by akinnee** [comment]
Bump?

**Comment by akinnee** [comment]
Is this plugin still supported?

**Comment by KevinStong** [comment]
this is pretty concerning we are facing the same issues and this could be a showstopper for us

**Comment by jdmunro** [comment]
Same issue here: takes a long time, then fails. However, the release is actually created in Sentry.

**Comment by kamilogorek** [comment]
Sorry for such a long response time, we are working on the next major release of all our SDKs and we were swamped with work.

To debug issues like this, please run errored command and provide output details to the related repository.

In OPs case it'd be `sentry-cli releases files connect-2.24.2-252cbe4ed7e90e59a750d016750055c463f629e4 upload-sourcemaps . --ignore node_modules --ignore /webpack/ --rewrite` and repository where issue should be reported is https://github.com/getsentry/sentry-cli/

Cheers!
