### ISSUE TITLE
Option to add a suffix 

### ISSUE THREAD

**Issue by miksansegundo** [getsentry/sentry-webpack-plugin#65]
From Sentry's support team asked me to upload the artifacts matching the URL of my JS bundle including the query param with the version number that I'm using for cache busting on each release.

`~/assets/app.bundle.js?v=5.0.10` (notice the part ?v=5.0.10).

Is there any option to add a suffix?

If there is not done yet I'll try to add a PR. Should be simple because we already have an option to add a prefix.

**Comment by kamilogorek** [comment]
Still need to be done in the sentry-cli, but added a PR for this.
