### ISSUE TITLE
Getting access to contenthash and hash in plugin

### ISSUE THREAD

**Issue by manatarms** [getsentry/sentry-webpack-plugin#66]
I was wondering if there is a way to do something like this in the sentry webpack plugin.

```
new SentryPlugin({
        release: '[hash]-[contenthash]',
        include: './dist',
        ignore: ['node_modules', 'webpack.config.js'],
})
```

I'm also using the [mini-css-extract](https://github.com/webpack-contrib/mini-css-extract-plugin) plugin that exposes a [contenthash]. I was wondering if there was a way to get access to the hashes as part of the plugin initialization.

Thanks!

**Comment by kamilogorek** [comment]
Fixed in https://github.com/getsentry/sentry-webpack-plugin/issues/66

**Comment by kamilogorek** [comment]
I completely forgot that we inject global id to the module file that's compiled with the rest of the app. It's impossible to access the hashes prior to the compilation, so we don't have that data on time. Had to revert this change :(

**Comment by uturnr** [comment]
I just thought I would share that after struggling to use my compilation hash to identify Sentry releases,  I have started using timestamps instead.

```
const merge = require('webpack-merge');
const buildConfig = require('./build.config.js');
const SentryCliPlugin = require('@sentry/webpack-plugin');
const sentryHash = Date.now().toString();
const webpack = require('webpack');

module.exports = merge(buildConfig, {
  devtool: 'source-map',
  plugins: [
    new webpack.DefinePlugin({
        'process.env.RAVEN_HASH': sentryHash,
    }),
    new SentryCliPlugin({
      debug: true,
      ignore: ['archive', 'node_modules', 'webpack', 'uturnr_resources', 'functions'],
      include: '.',
      release: sentryHash,
    }),
  ],
});
```

Then I can use the same timestamp to tag my errors in my raven config.

```
let hash = process.env.RAVEN_HASH;
window.Raven.config('https://...my-sentry-url...', {
  release: hash,
}).install();
```
