### ISSUE TITLE
Question: Env vars

### ISSUE THREAD

**Issue by jpic** [getsentry/sentry-webpack-plugin#69]
Hello,

First, thank you very much for maintaining this repository and Sentry, my best companion for years ;)

I don't understand how to configure the plugin. I mean, I have a standard docker deployment and try to abide by 12factor. So, I have an environment variable with the sentry URL including credentials.

If I understand how to use this plugin correctly, I should write a file with my env var in the docker container with the credentials again so that I can link to it with sentry.properties file ? Note that our container is public, so that means I should write this file from runtime, maybe in django settings or something ...

Is there any way it could just configure itself on runtime using env vars instead of configuration file ? 

Thanks

**Comment by kamilogorek** [comment]
Hey, sorry for such a long response-time! 

> Is there any way it could just configure itself on runtime using env vars instead of configuration file?

Yes, you can provide all necessary `sentry.properties` config values through ENV variables - https://docs.sentry.io/learn/cli/configuration/

Available env variables:
```
SENTRY_AUTH_TOKEN
SENTRY_API_KEY
SENTRY_URL
SENTRY_ORG
SENTRY_PROJECT
SENTRY_LOG_LEVEL
SENTRY_DISABLE_UPDATE_CHECK
DEVICE_FAMILY
DEVICE_MODEL
```

Hopefully, that answers your question. Feel free to reopen if still relevant.

**Comment by jpic** [comment]
Hi Kamil!

Thanks a heap your for your feedback, env vars work great :+1:

Keep up the great work !

Best
