### ISSUE TITLE
ENV variables probably are not passed at all

### ISSUE THREAD

**Issue by jardakotesovec** [getsentry/sentry-webpack-plugin#7]
I am trying to use this plugin. I set all the env variables needed before running the webpack:
```
export SENTRY_AUTH_TOKEN=
export SENTRY_URL=
export SENTRY_ORG=
export SENTRY_PROJECT=
```
And still was getting:
```
ERROR in Sentry CLI Plugin: Command failed: /.../node_modules/@sentry/cli/sentry-cli releases new e7007
error: An organization slug is required (provide with --org)
```

After investigating whats going on, I think most likely the issue is that the JS wrapper for sentry does not actually pass the env variables with exception of setting (SENTRY_PROPERTIES).

https://github.com/getsentry/sentry-cli/blob/master/js/index.js#L62

So it seems that only way to pass actual settings are via config file..  which is undesirable as don't want to have auth token in file.

**Comment by jardakotesovec** [comment]
I guess it still should inherit env variables from parent process, which would be webpack. So actually not sure where is the issue. If I run it directly it pick up the env variables just fine:
```
./node_modules/\@sentry/cli/bin/sentry-cli  releases   new 2da95dfb052f477380608d59d32b4ab9
```

**Comment by jardakotesovec** [comment]
Copying env from process.env like this made the trick:
```
SentryCli.prototype.execute = function(args) {
  var env = Object.assign({}, process.env, this.env);
  return new Promise(function(resolve, reject) {
    childProcess.execFile(SentryCli.getPath(), args, { env }, function(err, stdout) {
      if (err) return reject(err);
      // eslint-disable-next-line
      console.log(stdout);
      return resolve();
    });
  });
};
```
So it actually seems that execFile does not inherit the parent process variables. Interesting.

**Comment by jan-auer** [comment]
Will be fixed with the next release of [`@sentry/cli`](https://github.com/getsentry/sentry-cli)
