### ISSUE TITLE
Reference git commit for a release

### ISSUE THREAD

**Issue by Cherry** [getsentry/sentry-webpack-plugin#71]
Continued from #55 as that was closed early.

If we're using a different `release`, is there no way to pass options to the `set-commits` command in `sentry-cli`? Even when not setting a `release`, I do not see releases tagged with specific git commits in Sentry.

![](https://up.jross.me/f70t5)
The top 2 releases are once switching to this plugin - note there not being any git commits registered.

As per [the docs](https://docs.sentry.io/learn/cli/releases/), something like this would be great:

```javascript
"refs": [{
    "repository":"owner-name/repo-name",
    "commit":"2da95dfb052f477380608d59d32b4ab9",
    "previousCommit":"1e6223108647a7bfc040ef0ca5c92f68ff0dd993" // optional
}],
```

**Comment by BotchM** [comment]
PR #507 still needs to be merged to allow this feature.

**Comment by jsanchez034** [comment]
Looks like https://github.com/getsentry/sentry-cli/pull/580 has added the ability to enable this feature

**Comment by dmitryrn** [comment]
@kamilogorek So what remains? As I can see from these PRs we need to add `setCommits` as option in this plugin?

**Comment by dmitryrn** [comment]
I probably can make a PR, just tried to use `this.cli.releases.setCommits` in `src/index.js` with success

**Comment by Cherry** [comment]
Looks like this was implemented in https://github.com/getsentry/sentry-webpack-plugin/pull/139? AWESOME!

It's as simple as doing this, with other options like `previousCommit` available?
```
new SentryCliPlugin({
	release: 'abc,
	ignore: ['node_modules'],
	commit: process.env.GIT_HEAD
})
```

**Comment by kamilogorek** [comment]
You also need `repo` option to be defined, which is the name of repository you configured in the Sentry project options.
