### ISSUE TITLE
Could not automatically determine release name

### ISSUE THREAD

**Issue by MarvinXu** [getsentry/sentry-webpack-plugin#72]
![image](https://user-images.githubusercontent.com/7382357/43638813-c0f7c0ae-974c-11e8-9a99-4fdb558dd8a0.png)

webpack config:
```javascript
const path = require('path');
const SentryCliPlugin = require('@sentry/webpack-plugin');
module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist')
  },
  devtool: 'sourcemap',
  plugins: [
  	new SentryCliPlugin({
  		include: './dist',
  		configFile: `${__dirname}/sentry.properties`
  	})
  ]
};
```

```properties
defaults.url=http://sentry.zhuanzhuan.com/
defaults.org=zhuanzhuan
defaults.project=sentry-test

auth.token=53a6a4e8b6e0400393c9358768e338cac90f9715686546fe89042dcabfa955e0

```

If I set the release name manually, it all works well.

I'm just wondering, how is release name automatically generated? And why did it fail?

**Comment by HazAT** [comment]
It tries to fetch the latest hash with `git`. So I suppose you are not using `git` we should fix this to not error.

**Comment by MarvinXu** [comment]
Thanks for the reply. Adding "git commit required" to the doc would also help~

**Comment by kamilogorek** [comment]
Added here https://github.com/getsentry/sentry-webpack-plugin/pull/76
