### ISSUE TITLE
About Sentry CLI Plugin fail

### ISSUE THREAD

**Issue by my9074** [getsentry/sentry-webpack-plugin#75]
I use `sentry-webpack-plugin` to upload source map, but Error while compiling:

```shell
> client@0.1.0 build /Users/miaoyu3/work/skeletons/client
> vue-cli-service build


⠹  Building for production...

 ERROR  Failed to compile with 1 errors                                                                                                                                  13:53:25

Sentry CLI Plugin: Command failed: /Users/miaoyu3/work/skeletons/client/node_modules/@sentry/cli/sentry-cli releases files sk-testv1 upload-sourcemaps ../server/app --rewrite
error: API request failed
  caused by: sentry reported an error: unknown error (http status: 413)

 ERROR  Build failed with errors.
```

webpack config:
```js
//client/vue.config.js
configureWebpack: {
    plugins: [
      new SentryPlugin({
        include: '../server/app',
        release: 'sk-testv1',
        configFile: 'sentry.properties'
      })
    ]
  },
```

directory structure:
```shell
├── client
│   ├── babel.config.js
│   ├── .sentryclirc
│   ├── package-lock.json
│   ├── package.json
│   ├── public
│   ├── src
│   └── vue.config.js
├── server
│   ├── README.md
│   ├── README.zh-CN.md
│   ├── app
│   ├── appveyor.yml
│   ├── config
│   ├── logs
│   ├── package-lock.json
│   ├── package.json
│   ├── run
│   └── test
```
I found the fault in https://github.com/getsentry/sentry-cli/blob/master/js/helper.js#L143. I guess 413 status code is due to too large file?

**Comment by kamilogorek** [comment]
> I guess 413 status code is due to too large file?

Correct. Can you check how large are your bundled files? I can also see that you include `../server/app`, which is most likely your source directory, not built one (which should be uploaded).

**Comment by my9074** [comment]
@kamilogorek Thx for your reply ~

 I don't know if 3.6M is big? I don't think it's very big
![image](https://user-images.githubusercontent.com/4555635/44716466-effae080-aaec-11e8-9de5-8f89b6956a2a.png)

**Comment by kamilogorek** [comment]
Sorry for such a long response time.

Can you call `sentry-cli releases files sk-testv1 upload-sourcemaps ../server/app --rewrite` directly, and report the output to https://github.com/getsentry/sentry-cli repo? This plugin is just a wrapper for it, and cannot alter its main behavior in any way.

**Comment by xgqfrms** [comment]
https://docs.sentry.io/product/cli/configuration/

**Comment by avegancafe** [comment]
Did you ever find a solution to this? I'm getting:
```

> Found 18 release files
> Analyzing 18 sources
> Analyzing completed in 0.556s
> Rewriting sources
> Rewriting completed in 0.422s
> Adding source map references
> Bundling files for upload... ~/app.bundle.development-2022-09-22.js.map
> Bundling completed in 0.836s
> Optimizing completed in 0.03s
error: API request failed
  caused by: sentry reported an error: unknown error (http status: 413)
```
I moved all of the sourcemaps to their own dir and checked the folder file size and it was 13MB, not sure if this is already too large. The individual source files are ~3MB though, if that helps

**Comment by kamilogorek** [comment]
@avegancafe is this onpremise or saas sentry? 413 is payload too large, which would point to the fact that your onpremise instance might be misconfigured (if you use it). If not, can you run the command with `--log-level=debug` and provide logs? Thanks
