### ISSUE TITLE
Sourcemaps not applied

### ISSUE THREAD

**Issue by NikolaJankovic** [getsentry/sentry-webpack-plugin#83]
This is related to #62 

I've uploaded the sourcemaps using the sentry cli, the output of the cli 
references the minified files and their respective source files and the release is visible on the dashboard but events are still minified.

This is for an angular project, the build is stored in `/dist` with the sourcemaps. 

<img width="582" alt="screen shot 2018-09-22 at 9 37 16 am" src="https://user-images.githubusercontent.com/6041974/45917856-d038ad00-be4b-11e8-8267-06ad2bfa1358.png">

<img width="1271" alt="screen shot 2018-09-22 at 9 40 15 am" src="https://user-images.githubusercontent.com/6041974/45917860-df1f5f80-be4b-11e8-940a-5816e9ec4cc2.png">

This is for a new issue that's only occurred after the release. 

On a semi-related note though, is there any way to have old issues reference the sourcemap? If I delete an issue and wait for it to be raised again will it reference the release?

**Comment by NikolaJankovic** [comment]
I figured out the issue: during the build process angular cli uses a hash of the file as the filename (i.e 1polyfills.c881bab66ac56as0d.bundle.js) for cache busting. As it stands I would build twice - once with sourcemaps generated and once without, deploying the copy without sourcemaps - assuming there would be no difference in the code and therefore the hash. That's obviously not the case since by default the path of the sourcemaps is added as a comment at the end of the file and therefore obviously changes the hash. So the process of

1. Build without sourcemaps 
2. Deploy
3. Build with sourcemaps
4. Create release and upload to sentry

was failing because the file names weren't matching.

**Comment by kamilogorek** [comment]
Thanks for the write-up!
