### ISSUE TITLE
 Warning: a promise was rejected with a non-error: [object Object]

### ISSUE THREAD

**Issue by couds** [getsentry/sentry-webpack-plugin#84]
Hi, Thanks for all the hard work you all does.

This is driving me crazy, when there is an error on the build inside the plugin I this warning from webpack and the build Fail, This happen if you have a configuration error, or if the sentry server its unavailable) I had several configuration issues but because the error was not displayed was really difficult to know what was happening, can we reject an error object instead of a custom object? 

Thanks

**Comment by kamilogorek** [comment]
Hey @couds, we do reject with proper error messages - https://github.com/getsentry/sentry-webpack-plugin/blob/2ece7cdfccabb304a0b1a783d19429f9551a7025/src/index.js#L291-L298

Can you provide a repro case so I can dig into this issue? There's a chance that it's not originating in the plugin itself.

**Comment by couds** [comment]
Hi @kamilogorek this was not caused by the plugin this is an error in parallel-webpack. Thanks!
