### ISSUE TITLE
release not found - @sentry/cli

### ISSUE THREAD

**Issue by Cherry** [getsentry/sentry-webpack-plugin#87]
```
ERROR in Sentry CLI Plugin: Command failed: /home/website/node_modules/@sentry/cli/sentry-cli releases files c146f5320a39d123fb8886276c34d29474a75253 upload-sourcemaps ./assets/ --ignore node_modules --rewrite
error: release not found
```

We haven't made any changes to our webpack configuration and are now seeing this issue in CI when building our application today. Is there anything we can do to fix this? Did something change in the newest @sentry/cli version?

**Comment by Cherry** [comment]
After pinning @sentry/cli to an older version in our package-lock.json and using `npm ci`, the issues have ceased.

We used version 1.35.6. Version 1.36.0 introduces issues.
```
"@sentry/cli": {
	"version": "1.35.6",
	"resolved": "https://registry.npmjs.org/@sentry/cli/-/cli-1.35.6.tgz",
	"integrity": "sha512-gsMJOlgmM55QDl789Rc/UV8OjHFwBhj4R76F3WakgIzqDdFJn9GsWZhSHLI3Ltp8b6yq8UwDyvbfoz3PgHyabw==",
	"dev": true,
	"requires": {
		"https-proxy-agent": "^2.2.1",
		"node-fetch": "^2.1.2",
		"progress": "2.0.0",
		"proxy-from-env": "^1.0.0"
	}
},
```

**Comment by mitsuhiko** [comment]
@Cherry what does `sentry-cli releases -o yourorg -p yourproject list` print out?

**Comment by Cherry** [comment]
Using `sentry-cli 1.36.0`: http://termbin.com/5bc9
Using `sentry-cli 1.35.6`: http://termbin.com/2kzvi

**Comment by mitsuhiko** [comment]
Sorry for that. We found the issue. Going to fix it asap.

**Comment by jan-auer** [comment]
Released as 1.36.1.

**Comment by xgqfrms** [comment]
https://docs.sentry.io/product/cli/configuration/

**Comment by chj-damon** [comment]
> https://docs.sentry.io/product/cli/configuration/

what do you mean by this?

**Comment by sebastiankade** [comment]
Useful incase you're installing in ci via bash

```curl -sL https://sentry.io/get-cli/ | SENTRY_CLI_VERSION="2.3.1" bash```

**Comment by kamilogorek** [comment]
The issue should be fixed in `2.4.1`.

**Comment by jgcjordi** [comment]
It works again for me thanks!

**Comment by ibkadeeko** [comment]
It works correctly with the 2.4.1 update. Thanks.
