### ISSUE TITLE
How to release into specific environment?

### ISSUE THREAD

**Issue by sheerun** [getsentry/sentry-webpack-plugin#88]
I'd like to configure environment to publish to, ideally as an option to webpack plugin. Is it possible?

**Comment by kamilogorek** [comment]
What do you mean by a specific environment? `environment` is always linked to a specific event and/or release and it doesn't have any specific meaning as a standalone thing.

**Comment by sheerun** [comment]
What I mean is how to publish a release with sepecific environment set to sentry. It is because I'd like to publish staging release with `staging` environment set, so errors thrown in staging environment have access to source files.

**Comment by kamilogorek** [comment]
Oh, ok. It's all done through setting a release and environment for the event itself.
Events can have both things set, environment and release.
Where the release itself is just a "dumb box" for a specific group of events and contains artifacts (files) for it. It doesn't contain any information related to the environment.

**Comment by sheerun** [comment]
Tthen it's probably bad UI. The "releases" tab in sentry shows different releases for each environment selected

**Comment by alfredvaa** [comment]
I just experienced the same thing as @sheerun, the releases tab is empty in staging environment. Will it always be?

**Comment by kamilogorek** [comment]
@alfredvaa you have to explicitly set your releases and environments to link them with the event.

If you configure this plugin to create a release called `foo-release`, and use our SDK with config below:

```js
Sentry.init({
  dsn: "your-dsn",
  environment: 'staging',
  release: 'foo-staging'
});
```

Your release will be also visible in `staging` environment. `environment` is just a filter. If there are no events that have `staging` env set, there will be no releases.

https://docs.sentry.io/learn/releases/
https://docs.sentry.io/learn/environments/
https://docs.sentry.io/learn/configuration/

**Comment by tibinvpaul** [comment]
Hey @sheerun,

How did you manage this? I would like to have env specific releases (and artifacts) under the same project. Thanks.

**Comment by sheerun** [comment]
nope, it's still broken
