### ISSUE TITLE
Can I configure this plugin without using env variables or configuration files

### ISSUE THREAD

**Issue by sheerun** [getsentry/sentry-webpack-plugin#89]
I'd like to pass org and project name directly as options to this plugin, is it possible?

**Comment by sheerun** [comment]
(ideally this plugin would set environment variables for me just for calls to sentry-cli)

**Comment by kamilogorek** [comment]
It's unfortunately not possible, because we don't want to make a new release of the plugin, everytime something changes in the config handling of `sentry-cli` itself.

**Comment by sheerun** [comment]
It is not an issue, just introduce `env` option that passes given env variables directly into sentry-cli without whitelisting anything. It should be sufficient even if vars change in the future.

**Comment by kevinfarrugia** [comment]
You may also use a `.sentryclirc` file instead of setting `env`

**Comment by matthijsgroen** [comment]
I would also be interested in this. We use a single webpack config to build multiple frontends. both frontend report to their own sentry project. If it would be possible to pass in the auth token through the plugin, we could use multiple env vars for the multiple sentry endpoints.

**Comment by carestad** [comment]
What if you have separate projects for backend and frontend, like Laravel and Vue? Both the webpack plugin and laravel plugin seem to sue use the `SENTRY_PROJECT` variable, so when I test (in Laravel though) with `php artisan sentry:test` the event is logged in the wrong project.

**Comment by bbugh** [comment]
Has there been any solution created for this in the last year? Our build process does both front and end and back end, so we can't use the webpack plugin as it is. Setting the `SENTRY_PROJECT` or using `.sentryclirc` doesn't work for multiple projects. This plugin is by far the most preferable way to handle the releases for us.

```javascript
new SentryWebpackPlugin({
  // we should be able to do this
  env: {
    SENTRY_PROJECT: 'myproject',
    SENTRY_ORG: 'myorganization'
  }
})
```

**Comment by bbugh** [comment]
Or this:

```javascript
new SentryWebpackPlugin({
  cliOptions: {
    project: 'myproject',
    org: 'myorganization'
  }
})
```

```javascript
SentryCli({ ...userOptions.cliOptions, internalOptions })
```
