### ISSUE TITLE
Upload happens before WriteFilePlugin creates files

### ISSUE THREAD

**Issue by marco-fp** [getsentry/sentry-webpack-plugin#9]
I'm using `webpack-dev-server` along with `WriteFilePlugin` to output the bundle and map, unfortunately, the plugin is looking for the files before they are written into disk.

**Comment by jan-auer** [comment]
The plugin isn’t really meant to constantly upload sourcemaps to sentry during development. Besides, webpack should already serve source maps to your browser, so stack traces in your console should be symbolicated and link to local sources. 

Can’t you just run a webpack build without dev server when generating production assets?

**Comment by marco-fp** [comment]
The idea is to test from a local environment for errors, simulating as much as possible a production build. 
A workaround for this might be to install sentry-cli as an npm package and start the upload using `webpack-shell-plugin` with `onBuildEnd` with the proper command for the upload. 

I wonder if there's an event to start the upload after webpack builds, in a similar manner that works `webpack-shell-plugin`. I don't have experience writing webpack plugins so I cannot give a clear solution for this.

**Comment by jan-auer** [comment]
I am still wondering if it wouldn't be better to simply generate production assets (as this is as close as you get to production) and then serve them without the devserver. That way you completely avoid this issue.

`webpack-shell-plugin` also uses the `after-emit` hook internally when you use `onBuildEnd`, just as we do. The `WriteFilePlugin` however uses the `done` hook, which is executed one step later and corresponds to `onBuildExit`in `webpack-shell-plugin`. You could try to change the hook [here](https://github.com/getsentry/sentry-webpack-plugin/blob/master/src/index.js#L18) and make sure the plugins get executed in the right order. 

Still, to me this looks like a very special case of your setup and I'm not sure if that's something we should change.

**Comment by kamilogorek** [comment]
I'm wondering why `WriteFilePlugin` is not using `after-emit` instead, as it's only concerned about the assets that were emitted.
We should be mostly fine with using `done`, but then again we're only concerned about assets themselves, not when everything finished.

**Comment by jan-auer** [comment]
I was wondering, hot updates are also part of the assets phase. So the only thing after emitting assets are stats, actually. Maybe we should even PR `WriteFilePlugin` instead?

**Comment by marco-fp** [comment]
I've taken the approach mentioned by @jan-auer, thanks for the suggestion. Feel free to close the issue if you see fit.

**Comment by jan-auer** [comment]
@marco-fp just curious, which approach? 😃  

Going to close this for now, but if this pops up again we should consider a change (cc @kamilogorek ).
