### ISSUE TITLE
Sourcemap not applied for node app

### ISSUE THREAD

**Issue by aheissenberger** [getsentry/sentry-webpack-plugin#90]
### Problem:
source map is not used
![sentry-src](https://user-images.githubusercontent.com/200095/46703842-c921e500-cc28-11e8-83c4-c5f24cfa55d7.png)

### Environment 
 * Webpack minified node source code on AWS lambda
 * rave 2.6.4
 * @sentry/webpack-plugin 1.6.1

**raven config**
```javascript
const ravenConfig = {
  dataCallback: function (data) {
    var stacktrace = data.exception && data.exception[0].stacktrace;

    if (stacktrace && stacktrace.frames) {
      stacktrace.frames.forEach(function(frame) {
        if (frame.filename.startsWith('/')) {
          frame.filename = '~/' + path.basename(frame.filename);
        }
      });
    }

    return data;
  },
  captureErrors: true,
  captureUnhandledRejections: true,
  captureMemoryWarnings: true,
  captureTimeoutWarnings: true,
  ravenClient: require("raven") // don't forget!
};
```

1. Upload of Artifacts with Webpack-plugin
2. Artifacts exist in latest release
```
sentry-cli releases files 537dfb2 list
+-------------------+--------------+-----------------+--------+
| Name              | Distribution | Source Map      | Size   |
+-------------------+--------------+-----------------+--------+
| ~/handlers.js     |              | handlers.js.map | 1.97MB |
| ~/handlers.js.map |              |                 | 4.21MB |
+-------------------+--------------+-----------------+--------+
```

**Comment by kamilogorek** [comment]
Can you provide a link to the event in Sentry?

**Comment by aheissenberger** [comment]
> Can you provide a link to the event in Sentry?

https://sentry.io/andreas-heissenberger/test-sourcemap/issues/724087941/events/32937662534/

source code to repeat: https://github.com/aheissenberger/sentry-node-sourcemap

I did tried to upload the artifacts with sentry-cli but the result is a mix bag. I got it to not complain about not finding the source code but it is not capable to show me the original source code and always point to the wrong line similar to the upload with the Webpack plugin.

**Comment by jpic** [comment]
Maybe related ?
https://github.com/getsentry/sentry/issues/10136

**Comment by aheissenberger** [comment]
@kamilogorek Hi Kamil - did you had time to take a look on the events? 

Does the new lib support a dataCallback like the old one:
https://docs.sentry.io/clients/node/sourcemaps/#updating-raven-configuration-to-support-source-maps

**Comment by kamilogorek** [comment]
@aheissenberger yes, and unfortunately found out that it's not Sentry SDK issue, but a node and webpack as a whole. If you'll use this simplest scenario (https://github.com/evanw/node-source-map-support is required for node sourcemaps), it's still reading stack incorrectly. (using express to just prove the point)

```js
require("source-map-support").install();

const express = require("express");
console.log(express);

function foo() {
  bar();
}

foo();
```

and

```js
const path = require("path");
const webpack = require("webpack");

module.exports = {
  entry: "./app.js",
  target: "node",
  output: {
    filename: "app.js",
    path: path.resolve(__dirname, "dist")
  },
  devtool: "source-map"
};
```

> Does the new lib support a dataCallback like the old one:

Sure - https://docs.sentry.io/learn/filtering/?platform=browser#before-send

To configure Sentry to rewrite frames as in docs you linked, there's a new integration for this now:
```js
Sentry.init({
  dsn: "__YOUR_DSN__",
  integrations: [new Sentry.Integrations.RewriteFrames()]
});
```

It'll take the basename of every frame and prepend it with `~/` so it can be used with SentryCli with ease.

**Comment by aheissenberger** [comment]
@kamilogorek after many hours :-)

**The problem is the minimization in Webpack running in production mode.** I did not found any way to create a source map with proper line numbering.

**Temporal Fix:**  for now I deactivate the minimizer (webpack.config.js):
```javascript
optimization: {
    // if mode: production - this Uglify needs to be disabled for sourcmap to create valid line numbers
    minimizer: [],
  },
```

I was not able to use `Sentry.Integrations.RewriteFrames()` as it has not been published on npm.
I used this code:
```javascript
Sentry.init({
  dsn: process.env.DSN,
  // webpack.config.js:
  // if mode: production -  Uglify needs to be disabled for sourcmap to create valid line numbers
  //   optimization: {
  //     minimizer: [],
  //   },
  beforeSend(event, hint) {
    const exception = event.exception;

    if (exception) {
      try {
        const { basename, relative } = require("@sentry/utils/path");
        // without this setting __dirname will be "/"
        // https://github.com/webpack/webpack/issues/1599
        // webpack.config.js:
        // node: {
        //     __dirname: true,
        //   },
        // needs to be the folder where the current main.js is running
        const root = __dirname + "/";
        console.log("root: ", root);
        const frames = exception.values[0].stacktrace.frames;
        frames.forEach(frame => {
          if (frame.filename && frame.filename.startsWith("/")) {
            //console.log('filename:', frame.filename)
            const base = root
              ? relative(root, frame.filename)
              : basename(frame.filename);
            frame.filename = `app:///${base}`;
            console.log("filename changed:", frame.filename);
          }
        });
      } catch (err) {
        console.log(err);
      }
    }

    return event;
  },
  // does not exist in current version on npm - but would replace "beforeSend()"
  // monorepo - no way to yarn add github version
  //integrations: [new Sentry.Integrations.RewriteFrames()],
  release: process.env.SVERSION // 'release009'
});
```

It seems that `sentry-webpack-plugin` is currently broken as it is been called bevor the creation of the final output files. It looks like there are new hooks in webpack.

all details can be found here:
https://github.com/aheissenberger/sentry-node-sourcemap

# working source map for Webpack node apps

![screenshot](https://github.com/aheissenberger/sentry-node-sourcemap/raw/master/readme_sentry.jpg)

**Comment by kamilogorek** [comment]
Oh my, that's a rough one. Thanks for the investigation and sharing with your findings @aheissenberger! It'll definitely come in handy for us. Cheers!
