### ISSUE TITLE
Separate build time from release time

### ISSUE THREAD

**Issue by jpic** [getsentry/sentry-webpack-plugin#91]
Currently, the plugin will release during build time only. If you build a container, or a linux distribution package, you don't want to rebuild when you deploy.

This issue proposes to change that:

- during build, generate a json report (somewhat like "webpack-bundle-tracker")
- let the release command be fed by this

For example:

```
SENTRY_REPORT=.sentry-tracker.json 
npm prepare  # will not do the release on sentry, but just fill up $SENTRY_REPORT with data about the sourcemaps etc
npm run sentry-cli releases upload # will use $SENTRY_REPORT to generate a sentry release with the uploads     
```

**Comment by kamilogorek** [comment]
Thanks for the feedback @jpic! Could you please report this to https://github.com/getsentry/sentry-cli repo? This plugin is only a webpack wrapper on top what sentry-cli can already do :) Thanks!
