### ISSUE TITLE
webpack devtool option needed?

### ISSUE THREAD

**Issue by tonymaibox** [getsentry/sentry-webpack-plugin#94]
Hi, I've added the plugin as described in the docs like so:

```javascript
// webpack.config.productionBuild.js
// ...skipping the imports...

module.exports = Object.assign(commonWebpack, {
	mode: 'production',
	output: {
		path: path.resolve(__dirname, 'build'),
		filename: `bundle-${now}.js`,
		publicPath: '/',
	},
	plugins: commonWebpack.plugins.concat([
		new SentryWebpackPlugin({
			include: '.',
			ignoreFile: '.sentrycliignore',
			ignore: [
				'ci',
				'.circleci',
				'src/__mocks__',
			],
			configFile: '.sentryclirc',
		}),
	]).concat(showComponents),
})
```
I did have to make a root `./sentryclirc` file replacing what the docs suggested: `sentry.properties`

My `./sentryclirc` file:
```
[defaults]
project=the-project-name-here
org=my-org-name-here

[auth]
token=my-super-secret-token-and-i-am-not-telling-you
```

After building this in production, my sentry logs still don't have a sourcemap. It's just referencing the bundled code from webpack. I see here that some are using the `devtool` option in their webpack configurations. Is that what I'm missing?

Thanks!

**Comment by ha-D** [comment]
I think you need `devtool` to tell webpack to actually create the source-maps.

See here: https://webpack.js.org/configuration/devtool/

**Comment by kamilogorek** [comment]
Yes, `devtool` option is required, otherwise there will be no source-maps that we'll be able to upload.
