### ISSUE TITLE
Adopt an incremental approach when uploading releases

### ISSUE THREAD

**Issue by rtarnaud** [getsentry/sentry-webpack-plugin#96]
Hi,
It seems that every build triggers a complete upload of the source files, even if they have already been uploaded to Sentry, from a previous build.
Would it be possible to have only the files that have not been uploaded yet, actually sent by the plugin?
Thanks!

**Comment by kamilogorek** [comment]
Hey, unfortunately, it's not possible right now, as sentry-cli doesn't support it.
We will eventually add this feature there, and it won't require any updates to the sentry-webpack-plugin itself.
Please refer to https://github.com/getsentry/sentry-cli for future questions/discussions about this feature. Cheers!
