### ISSUE TITLE
Sourcemaps not applied

### ISSUE THREAD

**Issue by CacaoRick** [getsentry/sentry-webpack-plugin#97]
This is a react project.

My webpack config is:
```javascript
new SentryPlugin({
      release: process.env.RELEASE,
      include: './build',
      ignore: ['node_modules', 'config']
})
```

After webpack build, the `/build` is like this:
![2018-11-27 6 14 44](https://user-images.githubusercontent.com/20147386/49074838-85cf1480-f270-11e8-8246-afe728e56ab4.png)

I think webpack build and upload sourcemap success and artifacts is show those files.
<img width="692" alt="2018-11-27 6 00 28" src="https://user-images.githubusercontent.com/20147386/49073889-6f27be00-f26e-11e8-9b45-b13dd901ca64.png">
![2018-11-27 5 57 33](https://user-images.githubusercontent.com/20147386/49074007-ba41d100-f26e-11e8-91d0-6951286de8a5.png)

This is my issue, Look like sourcemap are not applied and line number is wrong.
[https://sentry.io/share/issue/202de92fd72340e488e7a3d11c4b6ab8/](https://sentry.io/share/issue/202de92fd72340e488e7a3d11c4b6ab8/)

But in broswer console, the source map is applied well.
<img width="611" alt="2018-11-27 6 06 09" src="https://user-images.githubusercontent.com/20147386/49074387-89ae6700-f26f-11e8-99c2-c5452bc92e6a.png">

Any help would be much appreciated.

**Comment by kamilogorek** [comment]
Can you provide a link to the event in the Sentry? (full one, not shareable page)

**Comment by CacaoRick** [comment]
@kamilogorek Thank you for your reply, here is the link:
https://sentry.io/cxrick/order-client-web/issues/780283115/events/37702825349/

**Comment by CacaoRick** [comment]
@kamilogorek Thank you very much, after add release to Sentry.init call sourcemap is effective.
